import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { sha256OfText } from "../src/lib/hash.ts";
const root = fileURLToPath(new URL("../", import.meta.url));
const unitDir = join(root, "corpus", "units", "ntc2018");
const assetDir = join(root, "corpus", "assets", "ntc2018");
const sourceId = "gu-so8-2018-ntc";
const workId = "it-mit:dm:2018-01-17:ntc2018";
const expressionId = "it-mit:dm:2018-01-17:ntc2018:original-it";
const profile = "ntc42-editorial-profile-0.1.0";
const createdAt = "2026-08-09T00:00:00Z";
type Region = { coordinateSystem: "pdf-points-top-left"; x: number; y: number; width: number; height: number };
type Opt = { page: number; printedPage: string; wrap?: boolean; discretionaryHyphen?: boolean; manual?: boolean };
type Inline = { kind: "text" | "math"; value: string; latex?: string };
const uid = (n: string) => "urn:structural-codes:it:unit:ntc2018:" + n;
const fid = (n: string) => "urn:structural-codes:it:asset:formula:ntc2018:" + n;
const tid = (n: string) => "urn:structural-codes:it:asset:table:ntc2018:" + n;
const reg = (x: number, y: number, width: number, height: number): Region => ({ coordinateSystem: "pdf-points-top-left", x, y, width, height });
const p = (page: number, printedPage: string, options: Omit<Opt, "page" | "printedPage"> = {}): Opt => ({ page, printedPage, ...options });
const t = (value: string): Inline => ({ kind: "text", value });
const m = (value: string, latex: string): Inline => ({ kind: "math", value, latex });
function trans(o: Opt) { const a: Array<{ operation: string; ruleVersion: string; note: string }> = []; if (o.wrap) a.push({ operation: "join-line-wrap", ruleVersion: profile, note: "Unite le righe del capoverso e normalizza gli spazi." }, { operation: "normalize-whitespace", ruleVersion: profile, note: "Uniformati gli spazi dopo la ricomposizione." }); if (o.discretionaryHyphen) a.push({ operation: "remove-discretionary-hyphen", ruleVersion: profile, note: "Ricomposte le parole spezzate dal trattino tipografico." }); if (o.manual) a.push({ operation: "manual-correction", ruleVersion: profile, note: "Ripristinati accenti, simboli e matematica confrontati con il render ufficiale." }); if (o.wrap || o.manual) a.push({ operation: "unicode-nfc", ruleVersion: profile, note: "Testo normalizzato in Unicode NFC." }); return a; }
function ev(o: Opt, r: Region, raw: string, normalized: string) { return { sourceId, pdfPage: o.page, printedPage: o.printedPage, region: r, extraction: { method: "pdf-text", tool: "pdfjs-dist", toolVersion: "4.10.38" }, transformations: trans(o), rawSha256: sha256OfText(raw), normalizedSha256: sha256OfText(normalized) }; }
function block(n: string, s: string, kind: "heading" | "paragraph" | "list-item", o: Opt, r: Region, raw: string, normalized: string, inline: Inline[] = [t(normalized)]) { return { blockId: uid(n) + "#block-" + s, kind, origin: "official", text: { raw, normalized, normalizationVersion: profile, inline }, evidence: ev(o, r, raw, normalized) }; }
function formula(n: string, num: string, o: Opt, r: Region) { return { blockId: uid(n) + "#block-formula-" + num.replaceAll(".", "-"), kind: "formula-ref", origin: "official", assetId: fid(num), evidence: { ...ev({ ...o, manual: true }, r, "[" + num + "]", "[" + num + "]"), extraction: { method: "manual-transcription", tool: "codex-source-transcription", toolVersion: profile } } }; }
function tableBlock(n: string, num: string, o: Opt, r: Region) { const note = "Tabella strutturata dal render ufficiale; revisione umana cella per cella ancora obbligatoria."; return { blockId: uid(n) + "#block-table-" + num.replaceAll(".", "-"), kind: "table-ref", origin: "official", assetId: tid(num), evidence: { ...ev({ ...o, manual: true }, r, note, note), extraction: { method: "manual-transcription", tool: "codex-source-transcription", toolVersion: profile } } }; }
function parent(n: string) { const a = n.split("."); return a.length === 1 ? null : uid(a.slice(0, -1).join(".")); }
function ancestors(n: string) { const a = n.split("."); return a.slice(1).map((_, i) => uid(a.slice(0, i + 1).join("."))); }
function unit(n: string, title: string, blocks: unknown[], formulas: string[] = [], tables: string[] = []) { return { $schema: "urn:structural-codes:schema:canonical-unit:v2", schemaVersion: "2.0.0-alpha.2", recordType: "canonical-unit", id: uid(n), workId, expressionId, kind: "subparagraph", numbering: { official: n, sortKey: n.split(".").map((x) => x.padStart(3, "0")).join(".") }, title, titleBlockId: uid(n) + "#block-heading", hierarchy: { parentId: parent(n), ancestorIds: ancestors(n), position: Number(n.split(".").at(-1)) }, validity: { from: "2018-03-22", to: null, status: "in-force", asOf: "2026-08-09" }, blocks, citations: [], relations: [], assets: { formulaIds: formulas.map(fid), tableIds: tables.map(tid), figureIds: [] }, workflow: { status: "extracted", createdBy: { actorId: "codex:ntc42-step4c", kind: "automated-agent", toolVersion: profile }, createdAt, reviews: [], openIssues: [{ issueId: "ntc2018-" + n.replaceAll(".", "-") + "-source-review", type: "normalization-review", severity: "blocking", note: "Record trascritto dall’evidence ufficiale ma non ancora confrontato integralmente da un revisore umano con il render della fonte." }, ...tables.map(() => ({ issueId: "ntc2018-" + n.replaceAll(".", "-") + "-assets", type: "asset-review", severity: "blocking", note: "La tabella è strutturata e richiede verifica umana cella per cella." }))] } }; }
const formulaRows = [
    ["4.2.54", "4.2.4.1.4", 108, "\\Delta_d\\le\\frac{\\Delta_R}{\\gamma_{Mf}}"],
    ["4.2.55", "4.2.4.1.4", 109, "\\Delta\\sigma_{max,d}=\\gamma_{Mf}\\cdot\\Delta\\sigma_{max}\\le\\Delta\\sigma_D"],
    ["4.2.56", "4.2.4.1.4", 109, "\\Delta\\tau_{max,d}=\\gamma_{Mf}\\cdot\\Delta\\tau_{max}\\le\\Delta\\tau_D=\\Delta\\tau_L"],
    ["4.2.57", "4.2.4.1.4", 109, "D=\\sum_i\\frac{n_i}{N_i}\\le1{,}0"],
    ["4.2.58", "4.2.4.1.5", 109, "T_{Ed}=T_{min}"],
    ["4.2.59", "4.2.4.1.5", 110, "T_{Ed}=T_{min}+15\\ ^\\circ\\mathrm{C}"],
    ["4.2.60", "4.2.4.2.1", 110, "\\delta_{tot}=\\delta_1+\\delta_2"],
] as const;
const tXI = tid("4.2.xi");
const tableXI = { id: tXI, unitId: uid("4.2.4.1.4"), officialNumber: "4.2.XI", pdfPage: 109, caption: "Coefficienti di sicurezza da assumere per le verifiche a fatica", columnCount: 3, headers: [[{ text: "Conseguenze della rottura" }, { text: "Conseguenze moderate" }, { text: "Conseguenze significative" }]], rows: [[{ text: "Strutture poco sensibili alla rottura per fatica" }, { text: "γMf = 1,00", latex: "\\gamma_{Mf}=1{,}00" }, { text: "γMf = 1,15", latex: "\\gamma_{Mf}=1{,}15" }], [{ text: "Strutture sensibili alla rottura per fatica" }, { text: "γMf = 1,15", latex: "\\gamma_{Mf}=1{,}15" }, { text: "γMf = 1,35", latex: "\\gamma_{Mf}=1{,}35" }]], notes: [] };
const tX = tid("4.2.x");
const tableX = { id: tX, unitId: uid("4.2.4.1.4"), officialNumber: "4.2.X", pdfPage: 108, caption: "Coefficiente correttivo del momento flettente per la verifica a stabilità delle travi inflesse", columnCount: 2, headers: [[{ text: "Distribuzione del momento flettente" }, { text: "Fattore correttivo kc", latex: "k_c" }]], rows: [[{ text: "ψ = Mmin/Mmax = 1", latex: "\\psi=M_{min}/M_{max}=1" }, { text: "1,0", latex: "1{,}0" }], [{ text: "−1 ≤ ψ ≤ 1", latex: "-1\\le\\psi\\le1" }, { text: "1/(1,33 − 0,33ψ)", latex: "\\frac{1}{1{,}33-0{,}33\\psi}" }], [{ text: "diagramma di momento flettente (schema grafico 1)" }, { text: "0,94" }], [{ text: "diagramma di momento flettente (schema grafico 2)" }, { text: "0,90" }], [{ text: "diagramma di momento flettente (schema grafico 3)" }, { text: "0,91" }], [{ text: "diagramma di momento flettente (schema grafico 4)" }, { text: "0,86" }], [{ text: "diagramma di momento flettente (schema grafico 5)" }, { text: "0,77" }], [{ text: "diagramma di momento flettente (schema grafico 6)" }, { text: "0,82" }]], notes: ["I diagrammi della fonte sono rappresentati provvisoriamente come descrizioni testuali; revisione visuale obbligatoria."] };
const units = [
    unit("4.2.4.1.4", "Stato limite di fatica", [
        block("4.2.4.1.4", "heading", "heading", p(108, "104", { manual: true }), reg(82.954, 265, 160, 7.476), "4.2.4.1.4 Stato limite di fatica", "4.2.4.1.4 Stato limite di fatica"),
        block("4.2.4.1.4", "p1", "paragraph", p(108, "104"), reg(82.954, 278, 428.6, 7.482), "Per le strutture soggette a carichi ciclici deve essere verificata la resistenza a fatica imponendo che:", "Per le strutture soggette a carichi ciclici deve essere verificata la resistenza a fatica imponendo che:"),
        formula("4.2.4.1.4", "4.2.54", p(108, "104"), reg(180, 292, 220, 25)),
        block("4.2.4.1.4", "p2-intro", "paragraph", p(108, "104"), reg(82.954, 284.2, 80, 7.482), "essendo", "essendo"),
        block("4.2.4.1.4", "p2-delta-d", "paragraph", p(108, "104", { wrap: true }), reg(82.954, 294, 428.6, 17.6), "Δd l’escursione di tensione (effettiva o equivalente allo spettro di tensione) prodotta dalle azioni cicliche di progetto che inducono fenomeni di fatica con coefficienti parziali γMf = 1;", "Δd l’escursione di tensione (effettiva o equivalente allo spettro di tensione) prodotta dalle azioni cicliche di progetto che inducono fenomeni di fatica con coefficienti parziali γMf = 1;", [m("Δd", "\\Delta_d"), t(" l’escursione di tensione (effettiva o equivalente allo spettro di tensione) prodotta dalle azioni cicliche di progetto che inducono fenomeni di fatica con coefficienti parziali "), m("γMf = 1", "\\gamma_{Mf}=1"), t(";")]),
        block("4.2.4.1.4", "p2-delta-r", "paragraph", p(108, "104", { wrap: true }), reg(82.954, 319.8, 428.6, 17.6), "ΔR la resistenza a fatica per la relativa categoria dei dettagli costruttivi, come desumibile dalle curve S-N di resistenza a fatica, per il numero totale di cicli di sollecitazione N applicati durante la vita di progetto richiesta,", "ΔR la resistenza a fatica per la relativa categoria dei dettagli costruttivi, come desumibile dalle curve S-N di resistenza a fatica, per il numero totale di cicli di sollecitazione N applicati durante la vita di progetto richiesta,", [m("ΔR", "\\Delta_R"), t(" la resistenza a fatica per la relativa categoria dei dettagli costruttivi, come desumibile dalle curve S-N di resistenza a fatica, per il numero totale di cicli di sollecitazione "), m("N", "N"), t(" applicati durante la vita di progetto richiesta,")]),
        block("4.2.4.1.4", "p2-gamma", "paragraph", p(108, "104"), reg(82.954, 343.9, 428.6, 7.482), "γMf il coefficiente parziale definito nella Tab. 4.2.XI.", "γMf il coefficiente parziale definito nella Tab. 4.2.XI.", [m("γMf", "\\gamma_{Mf}"), t(" il coefficiente parziale definito nella Tab. 4.2.XI.")]),
        block("4.2.4.1.4", "p3", "paragraph", p(108, "104", { wrap: true }), reg(82.954, 385, 428.6, 17.6), "Nel caso degli edifici la verifica a fatica delle membrature non è generalmente necessaria, salvo per quelle alle quali sono applicati dispositivi di sollevamento dei carichi o macchine vibranti.", "Nel caso degli edifici la verifica a fatica delle membrature non è generalmente necessaria, salvo per quelle alle quali sono applicati dispositivi di sollevamento dei carichi o macchine vibranti."),
        tableBlock("4.2.4.1.4", "4.2.x", p(108, "104"), reg(82.954, 410, 330, 185)),
        block("4.2.4.1.4", "p4", "paragraph", p(108, "104"), reg(82.954, 581.1, 428.6, 7.482), "Nel caso dei ponti gli spettri dei carichi da impiegare per le verifiche a fatica sono fissati nel Capitolo 5 delle presenti norme.", "Nel caso dei ponti gli spettri dei carichi da impiegare per le verifiche a fatica sono fissati nel Capitolo 5 delle presenti norme."),
        block("4.2.4.1.4", "p5", "paragraph", p(108, "104", { wrap: true }), reg(82.954, 593.6, 428.6, 17.6), "Per valutare gli effetti della fatica è innanzitutto necessario classificare le strutture nei confronti della loro sensibilità al fenomeno.", "Per valutare gli effetti della fatica è innanzitutto necessario classificare le strutture nei confronti della loro sensibilità al fenomeno."),
        block("4.2.4.1.4", "p6", "paragraph", p(108, "104"), reg(82.954, 616.3, 428.6, 7.482), "Si definiscono strutture poco sensibili alla rottura per fatica quelle in cui si verifichino tutte le seguenti circostanze:", "Si definiscono strutture poco sensibili alla rottura per fatica quelle in cui si verifichino tutte le seguenti circostanze:"),
        block("4.2.4.1.4", "l1", "list-item", p(108, "104", { wrap: true }), reg(88, 628.9, 420, 17.6), "– dettagli costruttivi, materiali e livelli di tensione tali che le eventuali lesioni presentino bassa velocità di propagazione e significativa lunghezza critica;", "– dettagli costruttivi, materiali e livelli di tensione tali che le eventuali lesioni presentino bassa velocità di propagazione e significativa lunghezza critica;"),
        block("4.2.4.1.4", "l2", "list-item", p(108, "104"), reg(88, 651.6, 420, 7.482), "– disposizioni costruttive che permettano la ridistribuzione degli sforzi;", "– disposizioni costruttive che permettano la ridistribuzione degli sforzi;"),
        block("4.2.4.1.4", "l3", "list-item", p(108, "104"), reg(88, 664.1, 420, 7.482), "– dettagli idonei ad arrestare la propagazione delle lesioni;", "– dettagli idonei ad arrestare la propagazione delle lesioni;"),
        block("4.2.4.1.4", "l4", "list-item", p(108, "104"), reg(88, 676.7, 420, 7.482), "– dettagli facilmente ispezionabili e riparabili;", "– dettagli facilmente ispezionabili e riparabili;"),
        block("4.2.4.1.4", "l5", "list-item", p(108, "104"), reg(88, 689.3, 420, 7.482), "– prestabilite procedure di ispezione e di manutenzione atte a rilevare e riparare le eventuali lesioni.", "– prestabilite procedure di ispezione e di manutenzione atte a rilevare e riparare le eventuali lesioni."),
        block("4.2.4.1.4", "p7", "paragraph", p(108, "104"), reg(82.954, 701.9, 428.6, 7.482), "Si definiscono strutture sensibili alla rottura per fatica quelle che non ricadono nei punti precedenti.", "Si definiscono strutture sensibili alla rottura per fatica quelle che non ricadono nei punti precedenti."),
        block("4.2.4.1.4", "fatigue-curve", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 98.9, 428.6, 17.6), "La resistenza a fatica di un dettaglio è individuata mediante una curva caratteristica, detta curva S-N, che esprime il numero di cicli a rottura N in funzione delle variazioni di tensione nel ciclo Δσ o Δτ.", "La resistenza a fatica di un dettaglio è individuata mediante una curva caratteristica, detta curva S-N, che esprime il numero di cicli a rottura N in funzione delle variazioni di tensione nel ciclo Δσ o Δτ.", [t("La resistenza a fatica di un dettaglio è individuata mediante una curva caratteristica, detta curva S-N, che esprime il numero di cicli a rottura "), m("N", "N"), t(" in funzione delle variazioni di tensione nel ciclo "), m("Δσ", "\\Delta\\sigma"), t(" o "), m("Δτ", "\\Delta\\tau"), t(".")]),
        block("4.2.4.1.4", "fatigue-reference", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 136.4, 428.6, 17.6), "Per indicazioni riguardanti le modalità di realizzazione dei dettagli costruttivi e la loro classificazione, con le rispettive curve S-N si può fare riferimento al documento UNI EN1993-1-9.", "Per indicazioni riguardanti le modalità di realizzazione dei dettagli costruttivi e la loro classificazione, con le rispettive curve S-N si può fare riferimento al documento UNI EN1993-1-9."),
        tableBlock("4.2.4.1.4", "4.2.xi", p(109, "105"), reg(82.954, 171.6, 310, 64)),
        block("4.2.4.1.4", "fatigue-types", "paragraph", p(109, "105"), reg(82.954, 243.9, 428.6, 7.482), "Le verifiche a fatica possono essere a vita illimitata o a danneggiamento.", "Le verifiche a fatica possono essere a vita illimitata o a danneggiamento."),
        block("4.2.4.1.4", "heading-life", "heading", p(109, "105", { manual: true }), reg(82.954, 269.1, 160, 7.476), "Verifica a vita illimitata.", "Verifica a vita illimitata."),
        block("4.2.4.1.4", "p8", "paragraph", p(109, "105"), reg(82.954, 281.6, 428.6, 7.482), "La verifica a vita illimitata si esegue controllando che sia:", "La verifica a vita illimitata si esegue controllando che sia:"),
        formula("4.2.4.1.4", "4.2.55", p(109, "105"), reg(180, 293.8, 250, 25)),
        block("4.2.4.1.4", "p9", "paragraph", p(109, "105"), reg(82.954, 310.7, 120, 7.482), "oppure che:", "oppure che:"),
        formula("4.2.4.1.4", "4.2.56", p(109, "105"), reg(180, 322.8, 250, 25)),
        block("4.2.4.1.4", "p10", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 340.8, 428.6, 27.6), "dove Δσmax,d e Δτmax,d sono, rispettivamente, i valori di progetto delle massime escursioni di tensioni normali e di tensioni tangenziali indotte nel dettaglio considerato dallo spettro di carico, e ΔσD e ΔτD i limiti di fatica ad ampiezza costante.", "dove Δσmax,d e Δτmax,d sono, rispettivamente, i valori di progetto delle massime escursioni di tensioni normali e di tensioni tangenziali indotte nel dettaglio considerato dallo spettro di carico, e ΔσD e ΔτD i limiti di fatica ad ampiezza costante.", [t("dove "), m("Δσmax,d", "\\Delta\\sigma_{max,d}"), t(" e "), m("Δτmax,d", "\\Delta\\tau_{max,d}"), t(" sono, rispettivamente, i valori di progetto delle massime escursioni di tensioni normali e di tensioni tangenziali indotte nel dettaglio considerato dallo spettro di carico, e "), m("ΔσD", "\\Delta\\sigma_D"), t(" e "), m("ΔτD", "\\Delta\\tau_D"), t(" i limiti di fatica ad ampiezza costante.")]),
        block("4.2.4.1.4", "p11", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 369.7, 428.6, 17.6), "La verifica a vita illimitata è esclusa per tutti i dettagli le cui curve S-N non presentino limite di fatica ad ampiezza costante (per es., i connettori a piolo).", "La verifica a vita illimitata è esclusa per tutti i dettagli le cui curve S-N non presentino limite di fatica ad ampiezza costante (per es., i connettori a piolo)."),
        block("4.2.4.1.4", "heading-damage", "heading", p(109, "105", { manual: true }), reg(82.954, 404.9, 170, 7.476), "Verifica a danneggiamento", "Verifica a danneggiamento"),
        block("4.2.4.1.4", "p12", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 417.5, 428.6, 7.482), "La verifica a danneggiamento si esegue mediante la formula di Palmgren-Miner, controllando che il danneggiamento D risulti:", "La verifica a danneggiamento si esegue mediante la formula di Palmgren-Miner, controllando che il danneggiamento D risulti:", [t("La verifica a danneggiamento si esegue mediante la formula di Palmgren-Miner, controllando che il danneggiamento "), m("D", "D"), t(" risulti:")]),
        formula("4.2.4.1.4", "4.2.57", p(109, "105"), reg(180, 429.6, 220, 25)),
        block("4.2.4.1.4", "p13", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 459.8, 428.6, 30), "dove ni è il numero dei cicli di ampiezza Δσi,d indotti dallo spettro di carico per le verifiche a danneggiamento nel corso della vita prevista per il dettaglio e Ni è il numero di cicli di ampiezza Δσi,d a rottura, ricavato dalla curva S-N caratteristica del dettaglio.", "dove ni è il numero dei cicli di ampiezza Δσi,d indotti dallo spettro di carico per le verifiche a danneggiamento nel corso della vita prevista per il dettaglio e Ni è il numero di cicli di ampiezza Δσi,d a rottura, ricavato dalla curva S-N caratteristica del dettaglio.", [t("dove "), m("ni", "n_i"), t(" è il numero dei cicli di ampiezza "), m("Δσi,d", "\\Delta\\sigma_{i,d}"), t(" indotti dallo spettro di carico per le verifiche a danneggiamento nel corso della vita prevista per il dettaglio e "), m("Ni", "N_i"), t(" è il numero di cicli di ampiezza "), m("Δσi,d", "\\Delta\\sigma_{i,d}"), t(" a rottura, ricavato dalla curva S-N caratteristica del dettaglio.")]),
        block("4.2.4.1.4", "p14", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 501.7, 428.6, 17.6), "La verifica a danneggiamento può essere eseguita anche con il metodo dei coefficienti di danneggiamento equivalente λ. Per l’impiego di tale metodo si deve fare riferimento a normative di comprovata validità, di cui al capitolo 12.", "La verifica a danneggiamento può essere eseguita anche con il metodo dei coefficienti di danneggiamento equivalente λ. Per l’impiego di tale metodo si deve fare riferimento a normative di comprovata validità, di cui al capitolo 12.", [t("La verifica a danneggiamento può essere eseguita anche con il metodo dei coefficienti di danneggiamento equivalente "), m("λ", "\\lambda"), t(". Per l’impiego di tale metodo si deve fare riferimento a normative di comprovata validità, di cui al capitolo 12.")]),
        block("4.2.4.1.4", "p15", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 524.4, 428.6, 17.6), "Nel caso di combinazioni di tensioni normali e tangenziali, la valutazione della resistenza a fatica dovrà considerare i loro effetti congiunti adottando idonei criteri di combinazione del danno.", "Nel caso di combinazioni di tensioni normali e tangenziali, la valutazione della resistenza a fatica dovrà considerare i loro effetti congiunti adottando idonei criteri di combinazione del danno."),
        block("4.2.4.1.4", "p16", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 547, 428.6, 17.6), "Nella valutazione della resistenza a fatica dovrà tenersi conto dello spessore del metallo base nel quale può innescarsi una potenziale lesione.", "Nella valutazione della resistenza a fatica dovrà tenersi conto dello spessore del metallo base nel quale può innescarsi una potenziale lesione."),
        block("4.2.4.1.4", "p17", "paragraph", p(109, "105"), reg(82.954, 569.7, 428.6, 7.482), "Le curve S-N reperibili nella letteratura consolidata sono riferite ai valori nominali delle tensioni.", "Le curve S-N reperibili nella letteratura consolidata sono riferite ai valori nominali delle tensioni."),
        block("4.2.4.1.4", "p18", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 582.3, 428.6, 27.6), "Per i dettagli costruttivi dei quali non sia nota la curva di resistenza a fatica, le escursioni tensionali potranno riferirsi alle tensioni geometriche o di picco, cioè alle tensioni principali nel metallo base in prossimità della potenziale lesione, secondo le modalità e le limitazioni specifiche del metodo, nell’ambito della meccanica della frattura.", "Per i dettagli costruttivi dei quali non sia nota la curva di resistenza a fatica, le escursioni tensionali potranno riferirsi alle tensioni geometriche o di picco, cioè alle tensioni principali nel metallo base in prossimità della potenziale lesione, secondo le modalità e le limitazioni specifiche del metodo, nell’ambito della meccanica della frattura."),
        block("4.2.4.1.4", "p19", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 615, 428.6, 17.6), "Nelle verifiche a fatica è consentito tenere conto degli effetti favorevoli di eventuali trattamenti termici o meccanici, purché adeguatamente comprovati.", "Nelle verifiche a fatica è consentito tenere conto degli effetti favorevoli di eventuali trattamenti termici o meccanici, purché adeguatamente comprovati."),
    ], ["4.2.54", "4.2.55", "4.2.56", "4.2.57"], ["4.2.x", "4.2.xi"]),
    unit("4.2.4.1.5", "Fragilità alle basse temperature", [
        block("4.2.4.1.5", "heading", "heading", p(109, "105", { manual: true }), reg(82.954, 646, 240, 7.476), "4.2.4.1.5 Fragilità alle basse temperature", "4.2.4.1.5 Fragilità alle basse temperature"),
        block("4.2.4.1.5", "p1", "paragraph", p(109, "105", { wrap: true, discretionaryHyphen: true }), reg(82.954, 657.8, 428.6, 27.6), "La temperatura minima alla quale l’acciaio per impiego strutturale può essere utilizzato senza pericolo di rottura fragile, in assenza di dati più precisi, deve essere stimata sulla base della temperatura T alla quale per detto acciaio può essere garantita la resilienza KV, richiesta secondo le norme europee applicabili.", "La temperatura minima alla quale l’acciaio per impiego strutturale può essere utilizzato senza pericolo di rottura fragile, in assenza di dati più precisi, deve essere stimata sulla base della temperatura T alla quale per detto acciaio può essere garantita la resilienza KV, richiesta secondo le norme europee applicabili.", [t("La temperatura minima alla quale l’acciaio per impiego strutturale può essere utilizzato senza pericolo di rottura fragile, in assenza di dati più precisi, deve essere stimata sulla base della temperatura "), m("T", "T"), t(" alla quale per detto acciaio può essere garantita la resilienza "), m("KV", "KV"), t(", richiesta secondo le norme europee applicabili.")]),
        block("4.2.4.1.5", "p2", "paragraph", p(109, "105", { wrap: true }), reg(82.954, 690.5, 428.6, 17.6), "Per quanto riguarda le caratteristiche di tenacità, nel caso di strutture non protette, si assumono come temperatura di riferimento TEd quella minima del luogo di installazione della struttura, con un periodo di ritorno di cinquant’anni Tmin definita al §3.5.2", "Per quanto riguarda le caratteristiche di tenacità, nel caso di strutture non protette, si assumono come temperatura di riferimento TEd quella minima del luogo di installazione della struttura, con un periodo di ritorno di cinquant’anni Tmin definita al §3.5.2", [t("Per quanto riguarda le caratteristiche di tenacità, nel caso di strutture non protette, si assumono come temperatura di riferimento "), m("TEd", "T_{Ed}"), t(" quella minima del luogo di installazione della struttura, con un periodo di ritorno di cinquant’anni "), m("Tmin", "T_{min}"), t(" definita al §3.5.2")]),
        formula("4.2.4.1.5", "4.2.58", p(109, "105"), reg(180, 714.1, 220, 25)),
        block("4.2.4.1.5", "p3", "paragraph", p(110, "106"), reg(82.954, 99, 428.6, 17.6), "Nel caso di strutture protette verrà invece adottata la temperatura Tmin aumentata di 15 °C", "Nel caso di strutture protette verrà invece adottata la temperatura Tmin aumentata di 15 °C", [t("Nel caso di strutture protette verrà invece adottata la temperatura "), m("Tmin", "T_{min}"), t(" aumentata di 15 °C")]),
        formula("4.2.4.1.5", "4.2.59", p(110, "106"), reg(180, 120, 220, 25)),
        block("4.2.4.1.5", "p4", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 154, 428.6, 17.6), "In assenza di dati statistici locali si potrà assumere come temperatura di riferimento il valore TEd = −25 °C per strutture non protette e TEd = −10 °C per strutture protette.", "In assenza di dati statistici locali si potrà assumere come temperatura di riferimento il valore TEd = −25 °C per strutture non protette e TEd = −10 °C per strutture protette.", [t("In assenza di dati statistici locali si potrà assumere come temperatura di riferimento il valore "), m("TEd = −25 °C", "T_{Ed}=-25\\ ^\\circ\\mathrm{C}"), t(" per strutture non protette e "), m("TEd = −10 °C", "T_{Ed}=-10\\ ^\\circ\\mathrm{C}"), t(" per strutture protette.")]),
        block("4.2.4.1.5", "p5", "paragraph", p(110, "106"), reg(82.954, 188, 428.6, 7.482), "Per la determinazione dei massimi spessori di utilizzo degli acciai in funzione", "Per la determinazione dei massimi spessori di utilizzo degli acciai in funzione"),
        block("4.2.4.1.5", "l1", "list-item", p(110, "106"), reg(88, 202, 420, 7.482), "– della temperatura minima di servizio,", "– della temperatura minima di servizio,"),
        block("4.2.4.1.5", "l2", "list-item", p(110, "106"), reg(88, 216, 420, 7.482), "– dei livelli di sollecitazione di progetto σEd col metodo agli stati limiti,", "– dei livelli di sollecitazione di progetto σEd col metodo agli stati limiti,", [t("– dei livelli di sollecitazione di progetto "), m("σEd", "\\sigma_{Ed}"), t(" col metodo agli stati limiti,")]),
        block("4.2.4.1.5", "l3", "list-item", p(110, "106"), reg(88, 230, 420, 7.482), "– del tipo e del grado dell’acciaio,", "– del tipo e del grado dell’acciaio,"),
        block("4.2.4.1.5", "p6", "paragraph", p(110, "106"), reg(82.954, 244, 428.6, 17.6), "può essere utilizzato il prospetto 2.1 di UNI EN 1993-1-10:2005.", "può essere utilizzato il prospetto 2.1 di UNI EN 1993-1-10:2005."),
        block("4.2.4.1.5", "p7", "paragraph", p(110, "106"), reg(82.954, 276, 428.6, 17.6), "Per membrature compresse valgono le prescrizioni del prospetto 2.1 della UNI EN 1993-1-10 con σEd = 0,25 fy.", "Per membrature compresse valgono le prescrizioni del prospetto 2.1 della UNI EN 1993-1-10 con σEd = 0,25 fy.", [t("Per membrature compresse valgono le prescrizioni del prospetto 2.1 della UNI EN 1993-1-10 con "), m("σEd = 0,25 fy", "\\sigma_{Ed}=0{,}25f_y"), t(".")]),
        block("4.2.4.1.5", "p8", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 310, 428.6, 17.6), "Tale tabella è valida per velocità di deformazione non superiori a ε̇0 = 4×10−4/s e per materiali che non abbiano subito incrudimenti e/o invecchiamenti tali da alterarne le caratteristiche di tenacità.", "Tale tabella è valida per velocità di deformazione non superiori a ε̇0 = 4×10−4/s e per materiali che non abbiano subito incrudimenti e/o invecchiamenti tali da alterarne le caratteristiche di tenacità.", [t("Tale tabella è valida per velocità di deformazione non superiori a "), m("ε̇0 = 4×10−4/s", "\\dot{\\varepsilon}_0=4\\times10^{-4}/\\mathrm{s}"), t(" e per materiali che non abbiano subito incrudimenti e/o invecchiamenti tali da alterarne le caratteristiche di tenacità.")]),
    ], ["4.2.58", "4.2.59"]),
    unit("4.2.4.1.6", "Resistenza di cavi, barre e funi", [
        block("4.2.4.1.6", "heading", "heading", p(110, "106", { manual: true }), reg(82.954, 350, 230, 7.476), "4.2.4.1.6 Resistenza di cavi, barre e funi", "4.2.4.1.6 Resistenza di cavi, barre e funi"),
        block("4.2.4.1.6", "p1", "paragraph", p(110, "106", { wrap: true, discretionaryHyphen: true }), reg(82.954, 363, 428.6, 37.6), "La verifica di cavi, barre e funi dovrà tener conto della specificità di tali elementi sia per quanto riguarda le caratteristiche dei materiali, sia per i dettagli costruttivi e potrà essere condotta con riferimento a specifiche indicazioni contenute in normative di comprovata validità, quali UNI EN 12385, UNI EN 10059 e UNI EN 10060, adottando fattori parziali γM che garantiscano i livelli di sicurezza stabiliti nelle presenti norme.", "La verifica di cavi, barre e funi dovrà tener conto della specificità di tali elementi sia per quanto riguarda le caratteristiche dei materiali, sia per i dettagli costruttivi e potrà essere condotta con riferimento a specifiche indicazioni contenute in normative di comprovata validità, quali UNI EN 12385, UNI EN 10059 e UNI EN 10060, adottando fattori parziali γM che garantiscano i livelli di sicurezza stabiliti nelle presenti norme.", [t("La verifica di cavi, barre e funi dovrà tener conto della specificità di tali elementi sia per quanto riguarda le caratteristiche dei materiali, sia per i dettagli costruttivi e potrà essere condotta con riferimento a specifiche indicazioni contenute in normative di comprovata validità, quali UNI EN 12385, UNI EN 10059 e UNI EN 10060, adottando fattori parziali "), m("γM", "\\gamma_M"), t(" che garantiscano i livelli di sicurezza stabiliti nelle presenti norme.")]),
    ]),
    unit("4.2.4.1.7", "Resistenza degli apparecchi di appoggio", [
        block("4.2.4.1.7", "heading", "heading", p(110, "106", { manual: true }), reg(82.954, 435, 250, 7.476), "4.2.4.1.7 Resistenza degli apparecchi di appoggio", "4.2.4.1.7 Resistenza degli apparecchi di appoggio"),
        block("4.2.4.1.7", "p1", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 448, 428.6, 27.6), "Le verifiche degli apparecchi di appoggio devono essere condotte tenendo conto della specificità dei materiali impiegati e della tipologia delle apparecchiature.", "Le verifiche degli apparecchi di appoggio devono essere condotte tenendo conto della specificità dei materiali impiegati e della tipologia delle apparecchiature."),
        block("4.2.4.1.7", "p2", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 480, 428.6, 27.6), "Si può fare riferimento a modelli di calcolo contenuti in normative di comprovata validità, quali le norme della serie UNI EN 1337, adottando fattori parziali γM che garantiscano i livelli di sicurezza stabiliti nelle presenti norme.", "Si può fare riferimento a modelli di calcolo contenuti in normative di comprovata validità, quali le norme della serie UNI EN 1337, adottando fattori parziali γM che garantiscano i livelli di sicurezza stabiliti nelle presenti norme.", [t("Si può fare riferimento a modelli di calcolo contenuti in normative di comprovata validità, quali le norme della serie UNI EN 1337, adottando fattori parziali "), m("γM", "\\gamma_M"), t(" che garantiscano i livelli di sicurezza stabiliti nelle presenti norme.")]),
    ]),
    unit("4.2.4.2", "VERIFICHE AGLI STATI LIMITE DI ESERCIZIO", [block("4.2.4.2", "heading", "heading", p(110, "106", { manual: true }), reg(82.954, 535, 290, 7.476), "4.2.4.2 V ERIFICHE AGLI STATI LIMITE DI ESERCIZIO", "4.2.4.2 VERIFICHE AGLI STATI LIMITE DI ESERCIZIO")]),
    unit("4.2.4.2.1", "Spostamenti verticali", [
        block("4.2.4.2.1", "heading", "heading", p(110, "106", { manual: true }), reg(82.954, 570, 180, 7.476), "4.2.4.2.1 Spostamenti verticali", "4.2.4.2.1 Spostamenti verticali"),
        block("4.2.4.2.1", "p1", "paragraph", p(110, "106"), reg(82.954, 583, 428.6, 7.482), "Il valore totale dello spostamento ortogonale all’asse dell’elemento (Fig. 4.2.3) è definito come", "Il valore totale dello spostamento ortogonale all’asse dell’elemento (Fig. 4.2.3) è definito come"),
        formula("4.2.4.2.1", "4.2.60", p(110, "106"), reg(180, 597, 220, 25)),
        block("4.2.4.2.1", "p2", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 650, 428.6, 37.6), "essendo: δC la monta iniziale della trave, δ1 lo spostamento elastico dovuto ai carichi permanenti, δ2 lo spostamento elastico dovuto ai carichi variabili, δmax lo spostamento nello stato finale, depurato della monta iniziale = δtot − δC.", "essendo: δC la monta iniziale della trave, δ1 lo spostamento elastico dovuto ai carichi permanenti, δ2 lo spostamento elastico dovuto ai carichi variabili, δmax lo spostamento nello stato finale, depurato della monta iniziale = δtot − δC.", [t("essendo: "), m("δC", "\\delta_C"), t(" la monta iniziale della trave, "), m("δ1", "\\delta_1"), t(" lo spostamento elastico dovuto ai carichi permanenti, "), m("δ2", "\\delta_2"), t(" lo spostamento elastico dovuto ai carichi variabili, "), m("δmax", "\\delta_{max}"), t(" lo spostamento nello stato finale, depurato della monta iniziale = "), m("δtot − δC", "\\delta_{tot}-\\delta_C"), t(".")]),
        block("4.2.4.2.1", "p3", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 695, 428.6, 27.6), "Nel caso di coperture, solai e travi di edifici ordinari, i valori limite di δmax e δ2, riferiti alle combinazioni caratteristiche delle azioni, sono espressi come funzione della luce L dell’elemento.", "Nel caso di coperture, solai e travi di edifici ordinari, i valori limite di δmax e δ2, riferiti alle combinazioni caratteristiche delle azioni, sono espressi come funzione della luce L dell’elemento.", [t("Nel caso di coperture, solai e travi di edifici ordinari, i valori limite di "), m("δmax", "\\delta_{max}"), t(" e "), m("δ2", "\\delta_2"), t(", riferiti alle combinazioni caratteristiche delle azioni, sono espressi come funzione della luce "), m("L", "L"), t(" dell’elemento.")]),
        block("4.2.4.2.1", "p4", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 730, 428.6, 37.6), "I valori di tali limiti sono da definirsi in funzione degli effetti sugli elementi portati, della qualità del comfort richiesto alla costruzione, delle caratteristiche degli elementi strutturali e non strutturali gravanti sull’elemento considerato, delle eventuali implicazioni di una eccessiva deformabilità sul valore dei carichi agenti.", "I valori di tali limiti sono da definirsi in funzione degli effetti sugli elementi portati, della qualità del comfort richiesto alla costruzione, delle caratteristiche degli elementi strutturali e non strutturali gravanti sull’elemento considerato, delle eventuali implicazioni di una eccessiva deformabilità sul valore dei carichi agenti."),
        block("4.2.4.2.1", "p5", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 775, 428.6, 27.6), "In carenza di più precise indicazioni si possono adottare i limiti indicati nella Tab. 4.2.XII, dove L è la luce dell’elemento o, nel caso di mensole, il doppio dello sbalzo.", "In carenza di più precise indicazioni si possono adottare i limiti indicati nella Tab. 4.2.XII, dove L è la luce dell’elemento o, nel caso di mensole, il doppio dello sbalzo.", [t("In carenza di più precise indicazioni si possono adottare i limiti indicati nella Tab. 4.2.XII, dove "), m("L", "L"), t(" è la luce dell’elemento o, nel caso di mensole, il doppio dello sbalzo.")]),
    ], ["4.2.60"]),
    unit("4.2.4.2.2", "Spostamenti laterali", [
        block("4.2.4.2.2", "heading", "heading", p(110, "106", { manual: true }), reg(82.954, 820, 180, 7.476), "4.2.4.2.2 Spostamenti laterali", "4.2.4.2.2 Spostamenti laterali"),
        block("4.2.4.2.2", "p1", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 833, 428.6, 37.6), "Negli edifici gli spostamenti laterali alla sommità delle colonne per le combinazioni caratteristiche delle azioni devono generalmente limitarsi ad una frazione dell’altezza della colonna e dell’altezza complessiva dell’edificio da valutarsi in funzione degli effetti sugli elementi portati, della qualità del comfort richiesto alla costruzione, delle eventuali implicazioni di una eccessiva deformabilità sul valore dei carichi agenti.", "Negli edifici gli spostamenti laterali alla sommità delle colonne per le combinazioni caratteristiche delle azioni devono generalmente limitarsi ad una frazione dell’altezza della colonna e dell’altezza complessiva dell’edificio da valutarsi in funzione degli effetti sugli elementi portati, della qualità del comfort richiesto alla costruzione, delle eventuali implicazioni di una eccessiva deformabilità sul valore dei carichi agenti."),
    ]),
];
const manifest = { $schema: "urn:structural-codes:schema:asset-manifest:v2", schemaVersion: "2.0.0-alpha.1", recordType: "asset-manifest", document: "ntc2018", section: "4.2-step4c", sourceId, status: "transcribed-unreviewed", formulas: formulaRows.map(([n, u, page, latex]) => ({ id: fid(n), unitId: uid(u), officialNumber: n, pdfPage: page, latex })), tables: [tableXI, tableX], figures: [] };
await mkdir(unitDir, { recursive: true });
await mkdir(assetDir, { recursive: true });
await Promise.all([...units.map((u) => writeFile(join(unitDir, u.numbering.official + ".json"), JSON.stringify(u, null, 2) + "\n", "utf8")), writeFile(join(assetDir, "4.2-step4c.json"), JSON.stringify(manifest, null, 2) + "\n", "utf8")]);
console.log("NTC 4.2 step4c: generate " + units.length + " unità, " + formulaRows.length + " formule e 1 tabella.");
