import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd(); const EVIDENCE = join(ROOT, "evidence", "circ-7-2019", "pages"); const UNITS = join(ROOT, "corpus", "units", "circ2019"); const ASSETS = join(ROOT, "corpus", "assets", "circ2019"); const SOURCE_ID = "circ-7-2019"; const WORK_ID = "it-mit:circ:2019-01-21:7-csllpp"; const EXPRESSION_ID = WORK_ID + ":original-it"; const TODAY = "2026-08-09"; const CREATED_AT = "2026-08-09T12:00:00Z"; const VERSION = "circ8-editorial-profile-0.2.0";
type Range = { page: number; start: number; end: number }; type Inline = { kind: "text" | "math"; value: string; latex?: string }; type Block = Record<string, unknown>; const cache = new Map<number, string[]>();
function lines(page: number): string[] { let v = cache.get(page); if (!v) { v = readFileSync(join(EVIDENCE, `page-${String(page).padStart(4, "0")}.raw.txt`), "utf8").replace(/\r\n/g, "\n").split("\n"); cache.set(page, v); } return v; }
function raw(rs: Range[]): string { return rs.map(({ page, start, end }) => lines(page).slice(start - 1, end).join("\n")).join("\n"); }
function sha256(v: string): string { return createHash("sha256").update(v, "utf8").digest("hex"); }
function clean(rs: Range[]): string { return raw(rs).replace(/\u0003/gu, "-").replace(/[ \t]*\n[ \t]*/gu, " ").replace(/[\u0000-\u001f\u007f]/gu, "").replace(/\s+/gu, " ").trim(); }
function printedPage(page: number): string { return String(page - 4); }
const mathMap: Record<string, string> = { "V_R": "V_R", "M_y": "M_y", "θ_y": "\\theta_y", "θ_u": "\\theta_u", "V_j": "V_j", "f_{yw}": "f_{yw}", "f_c": "f_c", "f_{cc}": "f_{cc}", "α_n": "\\alpha_n", "α_s": "\\alpha_s", "ρ_s": "\\rho_s", "d": "d", "t_j": "t_j", "b": "b", "s": "s", "θ": "\\theta", "R": "R", "h": "h", "h_s": "h_s", "A_s": "A_s", "f_y": "f_y", "ε_{cu}": "\\varepsilon_{cu}", "C8": "\\mathrm{C8}" };
function escapeRegExp(v: string): string { return v.replace(/[.*+?^$()|[\]\\]/gu, "\\$&").replace(/[{}]/gu, "\\$&"); }
const fixed = Object.keys(mathMap).sort((a, b) => b.length - a.length).map(escapeRegExp); const singles = ["θ", "α", "ρ", "ε"];
const inlinePattern = new RegExp(fixed.concat(singles.map(escapeRegExp)).concat(["(?<![\\p{L}\\p{N}_])R(?![\\p{L}\\p{N}_])", "(?<![\\p{L}\\p{N}_])M(?![\\p{L}\\p{N}_])", "(?<![\\p{L}\\p{N}_])V(?![\\p{L}\\p{N}_])", "(?<![\\p{L}\\p{N}_])I(?![\\p{L}\\p{N}_])"]).join("|"), "gu");
function inline(text: string): Inline[] | undefined { const out: Inline[] = []; let last = 0; for (const m of text.matchAll(inlinePattern)) { const i = m.index ?? 0; const v = m[0]; if (i > last) out.push({ kind: "text", value: text.slice(last, i) }); out.push({ kind: "math", value: v, latex: mathMap[v] ?? v }); last = i + v.length; } if (last < text.length) out.push({ kind: "text", value: text.slice(last) }); return out.some((x) => x.kind === "math") ? out : undefined; }
function transformations(rawText: string, normalized: string) { return [ ...(rawText.includes("\n") ? [{ operation: "join-line-wrap", ruleVersion: VERSION, note: "Rimossi gli a capo introdotti dall’impaginazione, conservando il capoverso." }] : []), ...(/[\u0000-\u001f\u007f]/u.test(rawText) ? [{ operation: "remove-control-character", ruleVersion: VERSION, note: "Rimossi i caratteri di controllo introdotti dall’estrazione del PDF." }] : []), ...(rawText !== normalized ? [{ operation: "manual-correction", ruleVersion: VERSION, note: "Ripristinati accenti, apostrofi, numerazione, glifi matematici e punteggiatura verificati sul render ufficiale." }] : []), { operation: "unicode-nfc", ruleVersion: VERSION, note: "Testo normalizzato in Unicode NFC." } ]; }
function evidence(rs: Range[], normalized: string) { const first = rs[0]; if (!first) throw new Error("Evidence senza pagina"); const rawText = raw(rs); return { sourceId: SOURCE_ID, pdfPage: first.page, printedPage: printedPage(first.page), region: null, extraction: { method: "manual-transcription", tool: "codex-render-transcription", toolVersion: VERSION }, transformations: transformations(rawText, normalized), rawSha256: sha256(rawText), normalizedSha256: sha256(normalized) }; }
function unitId(o: string): string { return `urn:structural-codes:it:unit:circ2019:${o.toLowerCase()}`; } function formulaId(o: string): string { return `urn:structural-codes:it:asset:formula:circ2019:${o.toLowerCase()}`; }
function relation(o: string, headingBlockId: string) { const parts = o.slice(1).toLowerCase().split("."); while (parts.length && !existsSync(join(ROOT, "corpus", "units", "ntc2018", `${parts.join(".")}.json`))) parts.pop(); return [{ relationId: unitId(o) + "#relation-001", type: "clarifies", targetUnitId: `urn:structural-codes:it:unit:ntc2018:${parts.join(".")}`, basis: "editorial", evidenceBlockIds: [headingBlockId], rationale: "Corrispondenza proposta tra numerazione omologa della Circolare e delle NTC; richiede conferma umana sul contenuto completo.", review: { status: "proposed", reviewedBy: null, reviewedAt: null } }]; }
let currentUnit = "";
function addBlock(blocks: Block[], normalized: string, kind: "heading" | "paragraph" | "list-item", ev: unknown, rawText: string) { const blockId = currentUnit + "#block-" + (blocks.length === 0 ? "heading" : String(blocks.length).padStart(3, "0")); const text: Record<string, unknown> = { raw: rawText, normalized, normalizationVersion: VERSION }; const seg = inline(normalized); if (seg) text.inline = seg; blocks.push({ blockId, kind, origin: "official", text, evidence: ev }); return blockId; }
function addText(blocks: Block[], rs: Range[], normalized: string, kind: "heading" | "paragraph" | "list-item" = "paragraph") { return addBlock(blocks, normalized, kind, evidence(rs, normalized), raw(rs)); } function addProse(blocks: Block[], rs: Range[], kind: "paragraph" | "list-item" = "paragraph") { return addText(blocks, rs, clean(rs), kind); }
function addFormulaRef(blocks: Block[], rs: Range[], o: string) { const blockId = currentUnit + "#block-" + String(blocks.length).padStart(3, "0"); blocks.push({ blockId, kind: "formula-ref", origin: "official", assetId: formulaId(o), evidence: evidence(rs, `[${o}]`) }); return formulaId(o); }
function makeUnit(o: string, title: string, parent: string, ancestors: string[], position: number, location: [number, number], build: (blocks: Block[]) => void, assets: string[] = []) { currentUnit = unitId(o); const blocks: Block[] = []; const heading = o + " " + title; const headingBlockId = addText(blocks, [{ page: location[0], start: location[1], end: location[1] }], heading, "heading"); build(blocks); const record = { $schema: "urn:structural-codes:schema:canonical-unit:v2", schemaVersion: "2.0.0-alpha.2", recordType: "canonical-unit", id: currentUnit, workId: WORK_ID, expressionId: EXPRESSION_ID, kind: "paragraph", numbering: { official: o, sortKey: o.slice(1).split(".").map((x) => x.padStart(3, "0")).join(".") }, title, titleBlockId: headingBlockId, hierarchy: { parentId: unitId(parent), ancestorIds: ancestors.map(unitId), position }, validity: { from: null, to: null, status: "unknown", asOf: TODAY }, blocks, citations: [], relations: relation(o, headingBlockId), assets: { formulaIds: assets, tableIds: [], figureIds: [] }, workflow: { status: "extracted", createdBy: { actorId: "generator:circ87:step3a", kind: "script", toolVersion: VERSION }, createdAt: CREATED_AT, reviews: [], openIssues: [{ issueId: `circ2019-${o.toLowerCase()}-source-review`, type: "normalization-review", severity: "blocking", note: "Trascrizione confrontata con il render ufficiale; resta obbligatoria la revisione umana indipendente." }, { issueId: `circ2019-${o.toLowerCase()}-relation`, type: "relation-review", severity: "blocking", note: "Il collegamento Circolare-NTC per numerazione omologa richiede conferma umana." }, ...(assets.length ? [{ issueId: `circ2019-${o.toLowerCase()}-formula-review`, type: "asset-review", severity: "blocking", note: "Le formule devono essere sottoposte a verifica umana, glifo per glifo, sul render ufficiale." }] : [])] } }; writeFileSync(join(UNITS, `${o.toLowerCase()}.json`), JSON.stringify(record, null, 2) + "\n", "utf8"); }
const r = (page: number, start: number, end = start): Range[] => [{ page, start, end }];
const F1 = formulaId("C8.7.4.1"), F2 = formulaId("C8.7.4.2"), F3 = formulaId("C8.7.4.3"), F4 = formulaId("C8.7.4.4"), F5 = formulaId("C8.7.4.5"), F6 = formulaId("C8.7.4.6"), F7a = formulaId("C8.7.4.7a"), F7b = formulaId("C8.7.4.7b"), F8 = formulaId("C8.7.4.8");

makeUnit("C8.7.4.1", "CRITERI PER GLI INTERVENTI DI CONSOLIDAMENTO DEGLI EDIFICI IN MURATURA", "C8.7.4", ["C8", "C8.7", "C8.7.4"], 1, [290, 3], (blocks) => {
  addProse(blocks, r(290, 4, 8)); addProse(blocks, r(290, 9, 10)); addProse(blocks, r(290, 11), "list-item"); addProse(blocks, r(290, 12), "list-item"); addProse(blocks, r(290, 13), "list-item"); addProse(blocks, r(290, 14), "list-item"); addProse(blocks, r(290, 15), "list-item"); addProse(blocks, r(290, 16));
  addText(blocks, r(290, 17), "1. Formazione dei diaframmi di piano", "heading"); addProse(blocks, r(290, 18, 20)); addProse(blocks, r(290, 21, 23)); addProse(blocks, r(290, 24, 28)); addProse(blocks, r(290, 29, 34)); addProse(blocks, r(290, 35, 38)); addProse(blocks, r(290, 39, 43));
  addText(blocks, r(290, 44), "2. Connessioni delle pareti tra loro e ai diaframmi di piano", "heading"); addProse(blocks, r(290, 45, 49)); addProse(blocks, r(290, 50, 55)); addProse(blocks, [...r(290, 56, 58), ...r(291, 3, 4)]); addProse(blocks, r(291, 5, 8)); addProse(blocks, r(291, 9, 16)); addProse(blocks, r(291, 17, 21)); addProse(blocks, r(291, 22)); addProse(blocks, r(291, 23), "list-item"); addProse(blocks, r(291, 24), "list-item"); addProse(blocks, r(291, 25), "list-item"); addProse(blocks, r(291, 26), "list-item"); addProse(blocks, r(291, 27, 31));
  addText(blocks, r(291, 32), "3. Collegamenti nello spessore della parete in presenza di paramenti multipli", "heading"); addProse(blocks, r(291, 33, 36)); addProse(blocks, r(291, 37, 40)); addProse(blocks, r(291, 41, 42));
  addText(blocks, r(291, 43), "4. Incremento della capacità delle pareti", "heading"); addProse(blocks, r(291, 44, 48)); addProse(blocks, r(291, 49, 51)); addProse(blocks, r(291, 52, 56)); addProse(blocks, [...r(291, 57), ...r(292, 3, 6)]); addProse(blocks, r(292, 7, 9)); addProse(blocks, r(292, 10, 11)); addProse(blocks, r(292, 12)); addProse(blocks, r(292, 13, 16)); addProse(blocks, r(292, 17, 20));
  addText(blocks, r(292, 21), "5. Contenimento delle spinte e consolidamento di archi e volte", "heading"); addProse(blocks, r(292, 22, 26)); addProse(blocks, r(292, 27, 28)); addProse(blocks, r(292, 29, 30)); addProse(blocks, r(292, 31, 32));
  addText(blocks, r(292, 33), "6. Altri interventi", "heading"); addText(blocks, r(292, 34), "Interventi su pilastri e colonne", "heading"); addProse(blocks, r(292, 35, 36)); addProse(blocks, r(292, 37), "list-item"); addProse(blocks, r(292, 38), "list-item"); addProse(blocks, r(292, 39, 43)); addText(blocks, r(292, 44), "Interventi sulle scale", "heading"); addProse(blocks, r(292, 45, 49)); addText(blocks, r(292, 50), "Realizzazione di giunti sismici", "heading"); addProse(blocks, r(292, 51, 52)); addText(blocks, r(292, 53), "Interventi in fondazione", "heading"); addProse(blocks, [...r(292, 54, 55), ...r(293, 3, 14)]); addText(blocks, r(293, 15), "Allargamento della fondazione mediante cordoli o platee in c.a.", "heading"); addProse(blocks, r(293, 16, 19)); addText(blocks, r(293, 20), "Consolidamento dei terreni di fondazione.", "heading"); addProse(blocks, r(293, 21)); addText(blocks, r(293, 22), "Inserimento di sottofondazioni profonde (micropali, pali radice).", "heading"); addProse(blocks, r(293, 23, 26)); addProse(blocks, r(293, 27, 31));
});

makeUnit("C8.7.4.2", "CRITERI PER GLI INTERVENTI DI CONSOLIDAMENTO DEGLI EDIFICI IN CALCESTRUZZO", "C8.7.4", ["C8", "C8.7", "C8.7.4"], 2, [293, 32], () => {});
makeUnit("C8.7.4.2.1", "Incamiciatura in c.a.", "C8.7.4.2", ["C8", "C8.7", "C8.7.4", "C8.7.4.2"], 1, [293, 37], (blocks) => { addProse(blocks, r(293, 38, 42)); addProse(blocks, r(293, 43, 44)); addProse(blocks, r(293, 45, 46)); addProse(blocks, r(293, 47)); addProse(blocks, r(293, 48, 49)); addProse(blocks, r(293, 50, 51)); addProse(blocks, r(293, 52, 54)); addFormulaRef(blocks, r(294, 3), "C8.7.4.1"); addText(blocks, r(294, 4), "capacità in termini di resistenza a flessione:", "list-item"); addFormulaRef(blocks, r(294, 5), "C8.7.4.2"); addText(blocks, r(294, 6), "capacità in termini di deformabilità allo snervamento:", "list-item"); addFormulaRef(blocks, r(294, 7), "C8.7.4.3"); addText(blocks, r(294, 8), "capacità in termini di deformabilità ultima:", "list-item"); addFormulaRef(blocks, r(294, 9), "C8.7.4.4"); addProse(blocks, r(294, 10)); addProse(blocks, r(294, 11, 15), "list-item"); addProse(blocks, r(294, 16, 20)); }, [F1, F2, F3, F4]);
makeUnit("C8.7.4.2.2", "Incamiciatura in acciaio", "C8.7.4.2", ["C8", "C8.7", "C8.7.4", "C8.7.4.2"], 2, [294, 21], (blocks) => { addProse(blocks, r(294, 22, 26)); addProse(blocks, r(294, 27, 30)); addText(blocks, r(294, 31), "Aumento della resistenza a taglio", "heading"); addProse(blocks, r(294, 32, 35)); addProse(blocks, r(294, 36, 37)); addFormulaRef(blocks, r(294, 38, 40), "C8.7.4.5"); addProse(blocks, r(294, 41, 43)); addText(blocks, r(294, 44), "Azione di confinamento", "heading"); addProse(blocks, r(294, 45, 49)); addFormulaRef(blocks, r(295, 3), "C8.7.4.6"); addProse(blocks, r(295, 4, 12)); addFormulaRef(blocks, r(295, 13), "C8.7.4.7a"); addFormulaRef(blocks, r(295, 14), "C8.7.4.7b"); addProse(blocks, r(295, 15, 17)); addText(blocks, r(295, 18), "per la deformazione ultima del calcestruzzo confinato:", "heading"); addFormulaRef(blocks, r(295, 19, 21), "C8.7.4.8"); addProse(blocks, r(295, 22, 25)); addProse(blocks, r(295, 26, 33)); }, [F5, F6, F7a, F7b, F8]);
makeUnit("C8.7.4.2.3", "Placcatura e fasciatura in materiali compositi", "C8.7.4.2", ["C8", "C8.7", "C8.7.4", "C8.7.4.2"], 3, [295, 34], (blocks) => { addProse(blocks, r(295, 35, 36)); addProse(blocks, r(295, 37, 38), "list-item"); addProse(blocks, r(295, 39, 41), "list-item"); addProse(blocks, r(295, 42, 43), "list-item"); addProse(blocks, r(295, 44, 45)); });
makeUnit("C8.7.5", "ELABORATI DEL PROGETTO DELL’INTERVENTO", "C8.7", ["C8", "C8.7"], 5, [295, 46], (blocks) => { addProse(blocks, r(295, 47, 48)); addProse(blocks, r(295, 49), "list-item"); addProse(blocks, r(295, 50), "list-item"); addProse(blocks, r(295, 51), "list-item"); addProse(blocks, r(295, 52), "list-item"); addProse(blocks, r(295, 53), "list-item"); });

const formulas = [
  { id: F1, unitId: unitId("C8.7.4.2.1"), officialNumber: "C8.7.4.1", pdfPage: 294, latex: "\\widetilde{V}_R=0.9V_R" },
  { id: F2, unitId: unitId("C8.7.4.2.1"), officialNumber: "C8.7.4.2", pdfPage: 294, latex: "\\widetilde{M}_y=0.9M_y" },
  { id: F3, unitId: unitId("C8.7.4.2.1"), officialNumber: "C8.7.4.3", pdfPage: 294, latex: "\\widetilde{\\theta}_y=0.9\\theta_y" },
  { id: F4, unitId: unitId("C8.7.4.2.1"), officialNumber: "C8.7.4.4", pdfPage: 294, latex: "\\widetilde{\\theta}_u=\\theta_u" },
  { id: F5, unitId: unitId("C8.7.4.2.2"), officialNumber: "C8.7.4.5", pdfPage: 294, latex: "V_j=0.5\\frac{2t_j}{s}bf_{yw}0.9d\\cot\\theta" },
  { id: F6, unitId: unitId("C8.7.4.2.2"), officialNumber: "C8.7.4.6", pdfPage: 295, latex: "f_{cc}=f_c\\left[1+3.7\\left(\\frac{0.5\\alpha_n\\alpha_s\\rho_sf_y}{f_c}\\right)^{0.86}\\right]" },
  { id: F7a, unitId: unitId("C8.7.4.2.2"), officialNumber: "C8.7.4.7a", pdfPage: 295, latex: "\\alpha_n=1-\\frac{(b-2R)^2+(h-2R)^2}{3bh}" },
  { id: F7b, unitId: unitId("C8.7.4.2.2"), officialNumber: "C8.7.4.7b", pdfPage: 295, latex: "\\alpha_s=\\left(1-\\frac{s-h_s}{2b}\\right)\\left(1-\\frac{s-h_s}{2h}\\right)" },
  { id: F8, unitId: unitId("C8.7.4.2.2"), officialNumber: "C8.7.4.8", pdfPage: 295, latex: "\\varepsilon_{cu}=0.0035+0.5\\frac{\\alpha_n\\alpha_s\\rho_sf_y}{f_{cc}}" },
];
mkdirSync(UNITS, { recursive: true }); mkdirSync(ASSETS, { recursive: true }); writeFileSync(join(ASSETS, "C8.7-step3a.json"), JSON.stringify({ $schema: "urn:structural-codes:schema:asset-manifest:v2", schemaVersion: "2.0.0-alpha.1", recordType: "asset-manifest", document: "circ2019", section: "C8.7-step3a", sourceId: SOURCE_ID, status: "transcribed-unreviewed", formulas, tables: [], figures: [] }, null, 2) + "\n", "utf8");
