import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { sha256OfText } from "../src/lib/hash.ts";

const repoRoot = fileURLToPath(new URL("../", import.meta.url));
const unitDirectory = join(repoRoot, "corpus", "units", "ntc2018");
const assetDirectory = join(repoRoot, "corpus", "assets", "ntc2018");
const sourceId = "gu-so8-2018-ntc";
const workId = "it-mit:dm:2018-01-17:ntc2018";
const expressionId = "it-mit:dm:2018-01-17:ntc2018:original-it";
const profile = "ntc42-editorial-profile-0.1.0";
const createdAt = "2026-08-09T00:00:00Z";

type Region = { coordinateSystem: "pdf-points-top-left"; x: number; y: number; width: number; height: number };
type TextOptions = { page: number; printedPage: string; wrap?: boolean; discretionaryHyphen?: boolean; manual?: boolean };
type Inline = { kind: "text" | "math"; value: string; latex?: string };
const unitId = (n: string) => `urn:structural-codes:it:unit:ntc2018:${n}`;
const formulaId = (n: string) => `urn:structural-codes:it:asset:formula:ntc2018:${n}`;
const tableId = (n: string) => `urn:structural-codes:it:asset:table:ntc2018:${n}`;
const reg = (x: number, y: number, width: number, height: number): Region => ({ coordinateSystem: "pdf-points-top-left", x, y, width, height });
const p = (page: number, printedPage: string, options: Omit<TextOptions, "page" | "printedPage"> = {}): TextOptions => ({ page, printedPage, ...options });
const t = (value: string): Inline => ({ kind: "text", value });
const m = (value: string, latex: string): Inline => ({ kind: "math", value, latex });

function transformations(options: TextOptions) {
    const result: Array<{ operation: string; ruleVersion: string; note: string }> = [];
    if (options.wrap) result.push({ operation: "join-line-wrap", ruleVersion: profile, note: "Unite le righe appartenenti allo stesso capoverso; i capoversi distinti restano blocchi separati." }, { operation: "normalize-whitespace", ruleVersion: profile, note: "Uniformati gli spazi dopo la ricomposizione delle righe." });
    if (options.discretionaryHyphen) result.push({ operation: "remove-discretionary-hyphen", ruleVersion: profile, note: "Ricomposte le parole spezzate dal trattino tipografico a fine riga." });
    if (options.manual) result.push({ operation: "manual-correction", ruleVersion: profile, note: "Ripristinati accenti, apostrofi, simboli e notazione matematica confrontati con il render ufficiale." });
    if (options.wrap || options.manual) result.push({ operation: "unicode-nfc", ruleVersion: profile, note: "Testo normalizzato in Unicode NFC." });
    return result;
}
function ev(options: TextOptions, region: Region | null, raw: string, normalized: string) {
    return { sourceId, pdfPage: options.page, printedPage: options.printedPage, region, extraction: { method: "pdf-text", tool: "pdfjs-dist", toolVersion: "4.10.38" }, transformations: transformations(options), rawSha256: sha256OfText(raw), normalizedSha256: sha256OfText(normalized) };
}
function block(number: string, suffix: string, kind: "heading" | "paragraph" | "list-item", options: TextOptions, region: Region, raw: string, normalized: string, inline: Inline[] = [{ kind: "text", value: normalized }]) {
    return { blockId: `${unitId(number)}#block-${suffix}`, kind, origin: "official", text: { raw, normalized, normalizationVersion: profile, inline }, evidence: ev(options, region, raw, normalized) };
}
function formulaBlock(number: string, suffix: string, asset: string, options: TextOptions, region: Region, raw: string) {
    return { blockId: `${unitId(number)}#block-${suffix}`, kind: "formula-ref", origin: "official", assetId: asset, evidence: { ...ev({ ...options, manual: true }, region, raw, raw), extraction: { method: "manual-transcription", tool: "codex-source-transcription", toolVersion: profile } } };
}
function tableBlock(number: string, suffix: string, asset: string, options: TextOptions, region: Region) {
    const note = "Tabella strutturata dal render ufficiale; revisione umana cella per cella ancora obbligatoria.";
    return { blockId: `${unitId(number)}#block-${suffix}`, kind: "table-ref", origin: "official", assetId: asset, evidence: { ...ev({ ...options, manual: true }, region, note, note), extraction: { method: "manual-transcription", tool: "codex-source-transcription", toolVersion: profile } } };
}
function parent(n: string) { const parts = n.split("."); return parts.length === 1 ? null : unitId(parts.slice(0, -1).join(".")); }
function ancestors(n: string) { const parts = n.split("."); return parts.slice(1).map((_, i) => unitId(parts.slice(0, i + 1).join("."))); }
function makeUnit(number: string, title: string, blocks: unknown[], formulas: string[] = [], tables: string[] = []) {
    return {
        $schema: "urn:structural-codes:schema:canonical-unit:v2", schemaVersion: "2.0.0-alpha.2", recordType: "canonical-unit", id: unitId(number), workId, expressionId,
        kind: number === "4.2.4" ? "section" : "subparagraph", numbering: { official: number, sortKey: number.split(".").map((x) => x.padStart(3, "0")).join(".") }, title, titleBlockId: `${unitId(number)}#block-heading`,
        hierarchy: { parentId: parent(number), ancestorIds: ancestors(number), position: Number(number.split(".").at(-1)) }, validity: { from: "2018-03-22", to: null, status: "in-force", asOf: "2026-08-09" }, blocks, citations: [], relations: [], assets: { formulaIds: formulas, tableIds: tables, figureIds: [] },
        workflow: { status: "extracted", createdBy: { actorId: "codex:ntc42-step4a", kind: "automated-agent", toolVersion: profile }, createdAt, reviews: [], openIssues: [{ issueId: `ntc2018-${number.replaceAll(".", "-")}-source-review`, type: "normalization-review", severity: "blocking", note: "Record trascritto dall’evidence ufficiale ma non ancora confrontato integralmente da un revisore umano con il render della fonte." }, ...(tables.length ? [{ issueId: `ntc2018-${number.replaceAll(".", "-")}-assets`, type: "asset-review", severity: "blocking", note: "La tabella è strutturata e collocata nel punto originario; resta obbligatorio il confronto umano cella per cella con la fonte ufficiale." }] : [])] },
    };
}

const f = (n: string) => formulaId(n);
const formulas = [
    ["4.2.3", "4.2.4.1.1", 101, "R_d=\\frac{R_k}{\\gamma_M}"],
    ["4.2.4", "4.2.4.1.2", 101, "\\sigma_{x,Ed}^2+\\sigma_{z,Ed}^2-\\sigma_{x,Ed}\\sigma_{z,Ed}+3\\tau_{Ed}^2\\le\\left(\\frac{f_{yk}}{\\gamma_{M0}}\\right)^2"],
    ["4.2.5", "4.2.4.1.2.1", 102, "\\frac{N_{Ed}}{N_{t,Rd}}\\le1"],
    ["4.2.6", "4.2.4.1.2.1", 102, "N_{pl,Rd}=\\frac{A f_{yk}}{\\gamma_{M0}}"],
    ["4.2.7", "4.2.4.1.2.1", 102, "N_{u,Rd}=\\frac{0{,}9\\cdot A_{net}\\cdot f_{tk}}{\\gamma_{M2}}"],
    ["4.2.8", "4.2.4.1.2.1", 102, "N_{pl,Rd}\\le N_{u,Rd}"],
    ["4.2.9", "4.2.4.1.2.2", 102, "\\frac{N_{Ed}}{N_{c,Rd}}\\le1"],
    ["4.2.10", "4.2.4.1.2.2", 102, "\\begin{aligned}N_{c,Rd}&=\\frac{A f_{yk}}{\\gamma_{M0}}&&\\text{per le sezioni di classe 1, 2 e 3}\\\\N_{c,Rd}&=\\frac{A_{eff}f_{yk}}{\\gamma_{M0}}&&\\text{per le sezioni di classe 4}\\end{aligned}"],
    ["4.2.11", "4.2.4.1.2.3", 102, "\\frac{M_{Ed}}{M_{c,Rd}}\\le1"],
    ["4.2.12", "4.2.4.1.2.3", 102, "M_{c,Rd}=M_{pl,Rd}=\\frac{W_{pl}\\cdot f_{yk}}{\\gamma_{M0}}\\quad\\text{per le sezioni di classe 1 e 2}"],
    ["4.2.13", "4.2.4.1.2.3", 102, "M_{c,Rd}=M_{el,Rd}=\\frac{W_{el,min}\\cdot f_{yk}}{\\gamma_{M0}}\\quad\\text{per le sezioni di classe 3}"],
    ["4.2.14", "4.2.4.1.2.3", 102, "M_{c,Rd}=\\frac{W_{eff,min}\\cdot f_{yk}}{\\gamma_{M0}}\\quad\\text{per le sezioni di classe 4}"],
    ["4.2.15", "4.2.4.1.2.3", 103, "\\frac{0{,}9\\cdot A_{f,net}\\cdot f_{tk}}{\\gamma_{M2}}\\ge\\frac{A_f\\cdot f_{yk}}{\\gamma_{M0}}"],
    ["4.2.16", "4.2.4.1.2.4", 103, "\\frac{V_{Ed}}{V_{c,Rd}}\\le1"],
    ["4.2.17", "4.2.4.1.2.4", 103, "V_{c,Rd}=\\frac{A_v\\cdot f_{yk}}{\\sqrt{3}\\cdot\\gamma_{M0}}"],
    ["4.2.18", "4.2.4.1.2.4", 103, "A_v=A-2bt_f+(t_w+2r)t_f"],
    ["4.2.19", "4.2.4.1.2.4", 103, "A_v=A-2bt_f+(t_w+r)t_f"],
    ["4.2.20", "4.2.4.1.2.4", 103, "A_v=A-\\sum(h_w\\cdot t_w)"],
    ["4.2.21", "4.2.4.1.2.4", 103, "A_v=0{,}9(A-bt_f)"],
    ["4.2.22", "4.2.4.1.2.4", 103, "A_v=\\frac{Ah}{b+h}\\quad\\text{quando il carico è parallelo all’altezza del profilo};\\qquad A_v=\\frac{Ab}{b+h}\\quad\\text{quando il carico è parallelo alla base del profilo}"],
    ["4.2.23", "4.2.4.1.2.4", 103, "A_v=\\frac{2A}{\\pi}"],
    ["4.2.24", "4.2.4.1.2.4", 103, "V_{c,Rd,red}=V_{c,Rd}\\sqrt{1-\\frac{\\tau_{t,Ed}}{1{,}25\\cdot f_{yk}/(\\sqrt{3}\\cdot\\gamma_{M0})}}"],
    ["4.2.25", "4.2.4.1.2.4", 103, "V_{c,Rd,red}=\\left[1-\\frac{\\tau_{t,Ed}}{f_{yk}/(\\sqrt{3}\\cdot\\gamma_{M0})}\\right]V_{c,Rd}"],
    ["4.2.26", "4.2.4.1.2.4", 103, "\\frac{\\tau_{t,Ed}}{f_{yk}/(\\sqrt{3}\\cdot\\gamma_{M0})}\\le1{,}0"],
    ["4.2.27", "4.2.4.1.2.4", 104, "\\frac{h_w}{t}>\\frac{72}{\\eta}\\sqrt{\\frac{235}{f_{yk}}}"],
    ["4.2.28", "4.2.4.1.2.5", 104, "\\frac{T_{Ed}}{T_{Rd}}\\le1{,}0"],
    ["4.2.29", "4.2.4.1.2.5", 104, "T_{Ed}=T_{t,Ed}+T_{w,Ed}"],
    ["4.2.30", "4.2.4.1.2.6", 104, "V_{Ed}\\le0{,}5\\,V_{c,Rd}"],
    ["4.2.31", "4.2.4.1.2.6", 104, "\\rho=\\left[\\frac{2V_{Ed}}{V_{c,Rd}}-1\\right]^2"],
    ["4.2.32", "4.2.4.1.2.6", 104, "M_{y,V,Rd}=\\frac{\\left[W_{pl,y}-\\frac{\\rho A_w^2}{4t_w}\\right]\\cdot f_{yk}}{\\gamma_{M0}}\\le M_{y,c,Rd}"],
    ["4.2.33", "4.2.4.1.2.7", 104, "M_{N,y,Rd}=M_{pl,y,Rd}\\frac{1-n}{1-0{,}5a}\\le M_{pl,y,Rd}"],
    ["4.2.34", "4.2.4.1.2.7", 104, "M_{N,z,Rd}=M_{pl,z,Rd}\\quad\\text{per }n\\le a"],
    ["4.2.35", "4.2.4.1.2.7", 104, "M_{N,z,Rd}=M_{pl,z,Rd}\\left[1-\\left(\\frac{n-a}{1-a}\\right)^2\\right]\\quad\\text{per }n>a"],
    ["4.2.36", "4.2.4.1.2.7", 104, "n=\\frac{N_{Ed}}{N_{pl,Rd}}"],
    ["4.2.37", "4.2.4.1.2.7", 104, "a=\\frac{A-2bt_f}{A}\\le0{,}5"],
    ["4.2.38", "4.2.4.1.2.8", 105, "\\left(\\frac{M_{y,Ed}}{M_{N,y,Rd}}\\right)^2+\\left(\\frac{M_{z,Ed}}{M_{N,z,Rd}}\\right)^{5n}\\le1"],
    ["4.2.39", "4.2.4.1.2.8", 105, "\\frac{M_{y,Ed}}{M_{N,y,Rd}}+\\frac{M_{z,Ed}}{M_{N,z,Rd}}\\le1"],
    ["4.2.40", "4.2.4.1.2.9", 105, "\\rho=\\left[\\frac{2V_{Ed}}{V_{c,Rd}}-1\\right]^2"],
] as const;
const tableVII = tableId("4.2.vii");
const table = { id: tableVII, unitId: unitId("4.2.4.1.1"), officialNumber: "4.2.VII", pdfPage: 101, caption: "Coefficienti di sicurezza per la resistenza delle membrature e la stabilità", columnCount: 2, headers: [[{ text: "" }, { text: "" }]], rows: [[{ text: "Resistenza delle Sezioni di Classe 1-2-3-4" }, { text: "γM0 = 1,05", latex: "\\gamma_{M0}=1{,}05" }], [{ text: "Resistenza all’instabilità delle membrature" }, { text: "γM1 = 1,05", latex: "\\gamma_{M1}=1{,}05" }], [{ text: "Resistenza all’instabilità delle membrature di ponti stradali e ferroviari" }, { text: "γM1 = 1,10", latex: "\\gamma_{M1}=1{,}10" }], [{ text: "Resistenza, nei riguardi della frattura, delle sezioni tese (indebolite dai fori)" }, { text: "γM2 = 1,25", latex: "\\gamma_{M2}=1{,}25" }]], notes: ["Trascritta dal render ufficiale; revisione umana cella per cella ancora obbligatoria."] };

const units = [
    makeUnit("4.2.4", "VERIFICHE", [
        block("4.2.4", "heading", "heading", p(101, "97", { manual: true }), reg(82.954, 260.264, 100, 7.476), "4.2.4. VERIFICHE", "4.2.4 VERIFICHE"),
        block("4.2.4", "editorial-001", "paragraph", p(101, "97", { wrap: true }), reg(82.954, 272.218, 428.6, 17.6), "Le azioni caratteristiche (carichi, distorsioni, variazioni termiche, ecc.) devono essere definite in accordo con quanto indicato nei\nCapitoli 3 e 5 delle presenti norme.", "Le azioni caratteristiche (carichi, distorsioni, variazioni termiche, ecc.) devono essere definite in accordo con quanto indicato nei Capitoli 3 e 5 delle presenti norme."),
        block("4.2.4", "editorial-002", "paragraph", p(101, "97", { wrap: true }), reg(82.954, 294.9, 428.6, 17.6), "Per costruzioni civili o industriali di tipo corrente e per le quali non esistano regolamentazioni specifiche, le azioni di progetto si\not tengono, per le verifiche statiche, secondo quanto indicato nel Capitolo 2.", "Per costruzioni civili o industriali di tipo corrente e per le quali non esistano regolamentazioni specifiche, le azioni di progetto si ottengono, per le verifiche statiche, secondo quanto indicato nel Capitolo 2."),
        block("4.2.4", "editorial-003", "paragraph", p(101, "97"), reg(82.954, 317.5, 363.53, 7.482), "Il calcolo deve condursi con appropriati metodi della meccanica strutturale, secondo i criteri indicati in § 4.2.3.", "Il calcolo deve condursi con appropriati metodi della meccanica strutturale, secondo i criteri indicati in § 4.2.3."),
    ]),
    makeUnit("4.2.4.1", "VERIFICHE AGLI STATI LIMITE ULTIMI", [block("4.2.4.1", "heading", "heading", p(101, "97", { manual: true }), reg(82.954, 340, 260, 7.476), "4.2.4.1 V ERIFICHE AGLI STATI LIMITE ULTIMI", "4.2.4.1 VERIFICHE AGLI STATI LIMITE ULTIMI")]),
    makeUnit("4.2.4.1.1", "Resistenza di progetto", [
        block("4.2.4.1.1", "heading", "heading", p(101, "97"), reg(82.954, 362, 125, 7.476), "4.2.4.1.1 Resistenza di progetto", "4.2.4.1.1 Resistenza di progetto"),
        block("4.2.4.1.1", "editorial-001", "paragraph", p(101, "97"), reg(82.954, 374, 270, 7.482), "La resistenza di progetto delle membrature Rd si pone nella forma:", "La resistenza di progetto delle membrature Rd si pone nella forma:", [t("La resistenza di progetto delle membrature "), m("Rd", "R_d"), t(" si pone nella forma:")]),
        formulaBlock("4.2.4.1.1", "formula-4-2-3", f("4.2.3"), p(101, "97", { manual: true }), reg(190, 388, 160, 30), "Rdk/Rd = Rk/γM [4.2.3]"),
        block("4.2.4.1.1", "editorial-002", "paragraph", p(101, "97"), reg(82.954, 425, 40, 7.482), "dove:", "dove:"),
        block("4.2.4.1.1", "editorial-003", "paragraph", p(101, "97", { wrap: true, discretionaryHyphen: true }), reg(83.004, 437, 428.6, 37.8), "Rk è il valore caratteristico della resistenza (trazione, compressione, flessione, taglio e torsione ) della membratura, determinata\ndai valori caratteristici delle resistenze dei materiali fyk e dalle caratteristiche geometriche degli elementi strutturali, dipen-\ndenti dalla classe della sezione.", "Rk è il valore caratteristico della resistenza (trazione, compressione, flessione, taglio e torsione) della membratura, determinata dai valori caratteristici delle resistenze dei materiali fyk e dalle caratteristiche geometriche degli elementi strutturali, dipendenti dalla classe della sezione.", [m("Rk", "R_k"), t(" è il valore caratteristico della resistenza (trazione, compressione, flessione, taglio e torsione) della membratura, determinata dai valori caratteristici delle resistenze dei materiali "), m("fyk", "f_{yk}"), t(" e dalle caratteristiche geometriche degli elementi strutturali, dipendenti dalla classe della sezione.")]),
        block("4.2.4.1.1", "editorial-004", "paragraph", p(101, "97"), reg(83.004, 478, 400, 7.482), "γM è il fattore parziale globale relativo al modello di resistenza adottato.", "γM è il fattore parziale globale relativo al modello di resistenza adottato.", [m("γM", "\\gamma_M"), t(" è il fattore parziale globale relativo al modello di resistenza adottato.")]),
        block("4.2.4.1.1", "editorial-005", "paragraph", p(101, "97", { wrap: true, discretionaryHyphen: true }), reg(83.004, 499, 428.6, 58), "Nel caso in cui si abbiamo elementi con sezioni di classe 4 può farsi riferimento alle caratteristiche geometriche “efficaci”, area\nefficace A eff, modulo di resistenza efficace Weff, modulo di inerzia efficace Jeff, valutati seguendo il procedimento indicato in UNI\nEN 1993-1-5. Nel caso di elementi strutturali formati a freddo e lamiere sottili, per valutare le caratteristiche “efficaci” si può fare\nriferimento a quanto indicato in UNI EN1993-1-3. In alternativa al metodo delle caratteristiche geometriche efficaci si potrà uti-\nlizzare il metodo delle tensioni ridotte, indicato in UNI EN 1993-1-5.", "Nel caso in cui si abbiamo elementi con sezioni di classe 4 può farsi riferimento alle caratteristiche geometriche “efficaci”, area efficace Aeff, modulo di resistenza efficace Weff, modulo di inerzia efficace Jeff, valutati seguendo il procedimento indicato in UNI EN 1993-1-5. Nel caso di elementi strutturali formati a freddo e lamiere sottili, per valutare le caratteristiche “efficaci” si può fare riferimento a quanto indicato in UNI EN1993-1-3. In alternativa al metodo delle caratteristiche geometriche efficaci si potrà utilizzare il metodo delle tensioni ridotte, indicato in UNI EN 1993-1-5.", [t("Nel caso in cui si abbiamo elementi con sezioni di classe 4 può farsi riferimento alle caratteristiche geometriche “efficaci”, area efficace "), m("Aeff", "A_{eff}"), t(", modulo di resistenza efficace "), m("Weff", "W_{eff}"), t(", modulo di inerzia efficace "), m("Jeff", "J_{eff}"), t(", valutati seguendo il procedimento indicato in UNI EN 1993-1-5. Nel caso di elementi strutturali formati a freddo e lamiere sottili, per valutare le caratteristiche “efficaci” si può fare riferimento a quanto indicato in UNI EN1993-1-3. In alternativa al metodo delle caratteristiche geometriche efficaci si potrà utilizzare il metodo delle tensioni ridotte, indicato in UNI EN 1993-1-5.")]),
        block("4.2.4.1.1", "editorial-006", "paragraph", p(101, "97", { wrap: true, discretionaryHyphen: true }), reg(83.004, 565, 428.6, 37.8), "Per le verifiche di resistenza delle sezioni delle membrature, con riferimento ai modelli di resistenza esposti nella presente nor-\nmativa ed utilizzando acciai dal grado S 235 al grado S 460 di cui al § 11.3, si adottano i fattori parziali γM0 e γM2 indicati nella\nTab. 4.2.VII. Il coefficiente di sicurezza γM2, in particolare, deve essere impiegato qualora si eseguano verifiche di elementi tesi\nnelle zone di unione delle membrature indebolite dai fori.", "Per le verifiche di resistenza delle sezioni delle membrature, con riferimento ai modelli di resistenza esposti nella presente normativa ed utilizzando acciai dal grado S 235 al grado S 460 di cui al § 11.3, si adottano i fattori parziali γM0 e γM2 indicati nella Tab. 4.2.VII. Il coefficiente di sicurezza γM2, in particolare, deve essere impiegato qualora si eseguano verifiche di elementi tesi nelle zone di unione delle membrature indebolite dai fori.", [t("Per le verifiche di resistenza delle sezioni delle membrature, con riferimento ai modelli di resistenza esposti nella presente normativa ed utilizzando acciai dal grado S 235 al grado S 460 di cui al § 11.3, si adottano i fattori parziali "), m("γM0", "\\gamma_{M0}"), t(" e "), m("γM2", "\\gamma_{M2}"), t(" indicati nella Tab. 4.2.VII. Il coefficiente di sicurezza "), m("γM2", "\\gamma_{M2}"), t(", in particolare, deve essere impiegato qualora si eseguano verifiche di elementi tesi nelle zone di unione delle membrature indebolite dai fori.")]),
        block("4.2.4.1.1", "editorial-007", "paragraph", p(101, "97", { wrap: true }), reg(83.004, 610, 428.6, 17.6), "Per valutare la stabilità degli elementi strutturali compressi, inflessi e presso-inflessi, si utilizza il coefficiente parziale di sicurezza\nγM1 indicato nella seguente tabella.", "Per valutare la stabilità degli elementi strutturali compressi, inflessi e presso-inflessi, si utilizza il coefficiente parziale di sicurezza γM1 indicato nella seguente tabella.", [t("Per valutare la stabilità degli elementi strutturali compressi, inflessi e presso-inflessi, si utilizza il coefficiente parziale di sicurezza "), m("γM1", "\\gamma_{M1}"), t(" indicato nella seguente tabella.")]),
        tableBlock("4.2.4.1.1", "table-4-2-vii", tableVII, p(101, "97", { manual: true }), reg(82.954, 645, 275, 70)),
    ], [f("4.2.3")], [tableVII]),
    makeUnit("4.2.4.1.2", "Resistenza delle membrature", [
        block("4.2.4.1.2", "heading", "heading", p(101, "97"), reg(82.954, 725, 150, 7.476), "4.2.4.1.2 Resistenza delle membrature", "4.2.4.1.2 Resistenza delle membrature"),
        block("4.2.4.1.2", "editorial-001", "paragraph", p(101, "97"), reg(82.954, 737, 370, 7.482), "Per la verifica delle travi la resistenza di progetto da considerare dipende dalla classificazione delle sezioni.", "Per la verifica delle travi la resistenza di progetto da considerare dipende dalla classificazione delle sezioni."),
        block("4.2.4.1.2", "editorial-002", "paragraph", p(101, "97", { wrap: true }), reg(82.954, 749, 428.6, 17.6), "La verifica in campo elastico è ammessa per tutti i tipi di sezione, con l’avvertenza di tener conto degli effetti di instabilità locale\nper le sezioni di classe 4.", "La verifica in campo elastico è ammessa per tutti i tipi di sezione, con l’avvertenza di tener conto degli effetti di instabilità locale per le sezioni di classe 4."),
        block("4.2.4.1.2", "editorial-003", "paragraph", p(101, "97"), reg(82.954, 773, 405, 7.482), "Le verifiche in campo elastico, per gli stati di sforzo piani tipici delle travi, si eseguono con riferimento al seguente criterio:", "Le verifiche in campo elastico, per gli stati di sforzo piani tipici delle travi, si eseguono con riferimento al seguente criterio:"),
        formulaBlock("4.2.4.1.2", "formula-4-2-4", f("4.2.4"), p(101, "97", { manual: true }), reg(180, 790, 240, 25), "σx,Ed² + σz,Ed² − σx,Edσz,Ed + 3τEd² ≤ (fyk/γM0)² [4.2.4]"),
        block("4.2.4.1.2", "editorial-004", "paragraph", p(101, "97", { wrap: true }), reg(82.954, 817, 428.6, 30), "dove:\nσx,Ed è il valore di progetto della tensione normale nel punto in esame, agente in direzione parallela all’asse della membratura;\nσz,Ed è il valore di progetto della tensione normale nel punto in esame, agente in direzione ortogonale all’asse della membratura;\nτEd è il valore di progetto della tensione tangenziale nel punto in esame, agente nel piano della sezione della membratura.", "dove: σx,Ed è il valore di progetto della tensione normale nel punto in esame, agente in direzione parallela all’asse della membratura; σz,Ed è il valore di progetto della tensione normale nel punto in esame, agente in direzione ortogonale all’asse della membratura; τEd è il valore di progetto della tensione tangenziale nel punto in esame, agente nel piano della sezione della membratura.", [t("dove: "), m("σx,Ed", "\\sigma_{x,Ed}"), t(" è il valore di progetto della tensione normale nel punto in esame, agente in direzione parallela all’asse della membratura; "), m("σz,Ed", "\\sigma_{z,Ed}"), t(" è il valore di progetto della tensione normale nel punto in esame, agente in direzione ortogonale all’asse della membratura; "), m("τEd", "\\tau_{Ed}"), t(" è il valore di progetto della tensione tangenziale nel punto in esame, agente nel piano della sezione della membratura.")]),
        block("4.2.4.1.2", "editorial-005", "paragraph", p(102, "98", { wrap: true }), reg(82.954, 98.928, 428.6, 27.6), "La verifica in campo plastico richiede che si determini una distribuzione di tensioni interne “staticamente ammissibile”, cioè in\nequilibrio con le sollecitazioni applicate (N, M, T, ecc.) e rispettosa della condizione di plasticità.\nI modelli resistenti esposti nei paragrafi seguenti definiscono la resistenza delle sezioni delle membrature nei confronti delle sollecitazioni interne, agenti separatamente o contemporaneamente.", "La verifica in campo plastico richiede che si determini una distribuzione di tensioni interne “staticamente ammissibile”, cioè in equilibrio con le sollecitazioni applicate (N, M, T, ecc.) e rispettosa della condizione di plasticità. I modelli resistenti esposti nei paragrafi seguenti definiscono la resistenza delle sezioni delle membrature nei confronti delle sollecitazioni interne, agenti separatamente o contemporaneamente."),
        block("4.2.4.1.2", "editorial-006", "paragraph", p(102, "98", { wrap: true }), reg(82.954, 130, 428.6, 17.6), "Per le sezioni di classe 4, in alternativa alle formule impiegate nel seguito, si possono impiegare altri procedimenti di comprovata\nvalidità.", "Per le sezioni di classe 4, in alternativa alle formule impiegate nel seguito, si possono impiegare altri procedimenti di comprovata validità."),
    ], [f("4.2.4")]),
];

function addSubunit(number: string, title: string, blocks: unknown[], formulaNumbers: string[]) { return makeUnit(number, title, blocks, formulaNumbers.map(f)); }

units.push(
    addSubunit("4.2.4.1.2.1", "Trazione", [
        block("4.2.4.1.2.1", "heading", "heading", p(102, "98", { manual: true }), reg(82.954, 159, 160, 7.476), "4.2.4.1.2.1 Trazione", "4.2.4.1.2.1 Trazione"),
        block("4.2.4.1.2.1", "editorial-001", "paragraph", p(102, "98"), reg(82.954, 171, 390, 7.482), "L’azione assiale di progetto NEd deve rispettare la seguente condizione:", "L’azione assiale di progetto NEd deve rispettare la seguente condizione:", [t("L’azione assiale di progetto "), m("NEd", "N_{Ed}"), t(" deve rispettare la seguente condizione:")]),
        formulaBlock("4.2.4.1.2.1", "formula-4-2-5", f("4.2.5"), p(102, "98", { manual: true }), reg(200, 185, 150, 25), "NEd/Nt,Rd ≤ 1 [4.2.5]"),
        block("4.2.4.1.2.1", "editorial-002", "paragraph", p(102, "98", { wrap: true }), reg(82.954, 218, 428.6, 17.6), "dove la resistenza di progetto a trazione Nt,Rd di membrature con sezioni indebolite da fori per collegamenti bullonati o chiodati\ndeve essere assunta pari al minore dei valori seguenti:", "dove la resistenza di progetto a trazione Nt,Rd di membrature con sezioni indebolite da fori per collegamenti bullonati o chiodati deve essere assunta pari al minore dei valori seguenti:"),
        block("4.2.4.1.2.1", "editorial-003", "paragraph", p(102, "98"), reg(82.954, 241, 400, 7.482), "a)  la resistenza plastica di progetto della sezione lorda, A,", "a)  la resistenza plastica di progetto della sezione lorda, A,"),
        formulaBlock("4.2.4.1.2.1", "formula-4-2-6", f("4.2.6"), p(102, "98", { manual: true }), reg(180, 254, 220, 25), "Npl,Rd = A fyk/γM0 [4.2.6]"),
        block("4.2.4.1.2.1", "editorial-004", "paragraph", p(102, "98", { wrap: true }), reg(82.954, 287, 428.6, 17.6), "b)  la resistenza di progetto a rottura della sezione netta, Anet, in corrispondenza dei fori per i collegamenti.", "b)  la resistenza di progetto a rottura della sezione netta, Anet, in corrispondenza dei fori per i collegamenti."),
        formulaBlock("4.2.4.1.2.1", "formula-4-2-7", f("4.2.7"), p(102, "98", { manual: true }), reg(180, 309, 220, 25), "Nu,Rd = 0,9 Anet ftk/γM2 [4.2.7]"),
        block("4.2.4.1.2.1", "editorial-005", "paragraph", p(102, "98", { wrap: true }), reg(82.954, 342, 428.6, 27.6), "Qualora il progetto preveda la gerarchia delle resistenze, come avviene in presenza di azioni sismiche, la resistenza di progetto\nplastica della sezione lorda, Npl,Rd, deve risultare minore della resistenza di progetto a rottura delle sezioni indebolite dai fori per\ni collegamenti, Nu,Rd:", "Qualora il progetto preveda la gerarchia delle resistenze, come avviene in presenza di azioni sismiche, la resistenza di progetto plastica della sezione lorda, Npl,Rd, deve risultare minore della resistenza di progetto a rottura delle sezioni indebolite dai fori per i collegamenti, Nu,Rd:"),
        formulaBlock("4.2.4.1.2.1", "formula-4-2-8", f("4.2.8"), p(102, "98", { manual: true }), reg(180, 376, 220, 18), "Npl,Rd ≤ Nu,Rd [4.2.8]"),
    ], ["4.2.5", "4.2.6", "4.2.7", "4.2.8"]),
    addSubunit("4.2.4.1.2.2", "Compressione", [
        block("4.2.4.1.2.2", "heading", "heading", p(102, "98", { manual: true }), reg(82.954, 400, 170, 7.476), "4.2.4.1.2.2 Compressione", "4.2.4.1.2.2 Compressione"),
        block("4.2.4.1.2.2", "editorial-001", "paragraph", p(102, "98"), reg(82.954, 412, 390, 7.482), "La forza di compressione di progetto NEd deve rispettare la seguente condizione:", "La forza di compressione di progetto NEd deve rispettare la seguente condizione:", [t("La forza di compressione di progetto "), m("NEd", "N_{Ed}"), t(" deve rispettare la seguente condizione:")]),
        formulaBlock("4.2.4.1.2.2", "formula-4-2-9", f("4.2.9"), p(102, "98", { manual: true }), reg(200, 426, 150, 25), "NEd/Nc,Rd ≤ 1 [4.2.9]"),
        block("4.2.4.1.2.2", "editorial-002", "paragraph", p(102, "98"), reg(82.954, 459, 428.6, 17.6), "dove la resistenza di progetto a compressione della sezione Nc,Rd vale:", "dove la resistenza di progetto a compressione della sezione Nc,Rd vale:", [t("dove la resistenza di progetto a compressione della sezione "), m("Nc,Rd", "N_{c,Rd}"), t(" vale:")]),
        formulaBlock("4.2.4.1.2.2", "formula-4-2-10", f("4.2.10"), p(102, "98", { manual: true }), reg(180, 480, 270, 40), "Nc,Rd = A fyk/γM0 per le sezioni di classe 1, 2 e 3; Nc,Rd = Aeff fyk/γM0 per le sezioni di classe 4 [4.2.10]"),
        block("4.2.4.1.2.2", "editorial-003", "paragraph", p(102, "98", { wrap: true }), reg(82.954, 530, 428.6, 27.6), "Non è necessario dedurre l’area dei fori per i collegamenti bullonati o chiodati, purché in tutti i fori siano presenti gli elementi di\ncollegamento e non siano presenti fori sovradimensionati o asolati.", "Non è necessario dedurre l’area dei fori per i collegamenti bullonati o chiodati, purché in tutti i fori siano presenti gli elementi di collegamento e non siano presenti fori sovradimensionati o asolati."),
    ], ["4.2.9", "4.2.10"]),
    addSubunit("4.2.4.1.2.3", "Flessione monoassiale (retta)", [
        block("4.2.4.1.2.3", "heading", "heading", p(102, "98", { manual: true }), reg(82.954, 565, 230, 7.476), "4.2.4.1.2.3 Flessione monoassiale (retta)", "4.2.4.1.2.3 Flessione monoassiale (retta)"),
        block("4.2.4.1.2.3", "editorial-001", "paragraph", p(102, "98"), reg(82.954, 577, 390, 7.482), "Il momento flettente di progetto MEd deve rispettare la seguente condizione:", "Il momento flettente di progetto MEd deve rispettare la seguente condizione:", [t("Il momento flettente di progetto "), m("MEd", "M_{Ed}"), t(" deve rispettare la seguente condizione:")]),
        formulaBlock("4.2.4.1.2.3", "formula-4-2-11", f("4.2.11"), p(102, "98", { manual: true }), reg(200, 590, 150, 25), "MEd/Mc,Rd ≤ 1 [4.2.11]"),
        block("4.2.4.1.2.3", "editorial-002", "paragraph", p(102, "98", { wrap: true }), reg(82.954, 623, 428.6, 17.6), "dove la resistenza di progetto a flessione retta della sezione Mc,Rd si valuta tenendo conto della presenza di eventuali fori in zona\ntesa per collegamenti bullonati o chiodati.", "dove la resistenza di progetto a flessione retta della sezione Mc,Rd si valuta tenendo conto della presenza di eventuali fori in zona tesa per collegamenti bullonati o chiodati."),
        block("4.2.4.1.2.3", "editorial-003", "paragraph", p(102, "98"), reg(82.954, 646, 400, 7.482), "La resistenza di progetto a flessione retta della sezione Mc,Rd vale:", "La resistenza di progetto a flessione retta della sezione Mc,Rd vale:"),
        formulaBlock("4.2.4.1.2.3", "formula-4-2-12", f("4.2.12"), p(102, "98", { manual: true }), reg(180, 660, 260, 25), "Mc,Rd = Mpl,Rd = Wpl fyk/γM0 per le sezioni di classe 1 e 2 [4.2.12]"),
        block("4.2.4.1.2.3", "editorial-004", "paragraph", p(102, "98"), reg(82.954, 694, 350, 7.482), "in cui Wpl rappresenta il modulo di resistenza plastico della sezione", "in cui Wpl rappresenta il modulo di resistenza plastico della sezione:", [t("in cui "), m("Wpl", "W_{pl}"), t(" rappresenta il modulo di resistenza plastico della sezione:")]),
        formulaBlock("4.2.4.1.2.3", "formula-4-2-13", f("4.2.13"), p(102, "98", { manual: true }), reg(180, 710, 270, 25), "Mc,Rd = Mel,Rd = Wel,min fyk/γM0 per le sezioni di classe 3 [4.2.13]"),
        formulaBlock("4.2.4.1.2.3", "formula-4-2-14", f("4.2.14"), p(102, "98", { manual: true }), reg(180, 735, 250, 25), "Mc,Rd = Weff,min fyk/γM0 per le sezioni di classe 4 [4.2.14]"),
        block("4.2.4.1.2.3", "editorial-005", "paragraph", p(102, "98", { wrap: true, discretionaryHyphen: true }), reg(82.954, 765, 428.6, 37), "per le sezioni di classe 3, Wel,min è il modulo resistente elastico minimo della sezione in acciaio; per le sezioni di classe 4, invece, il\nmodulo Weff,min è calcolato eliminando le parti della sezione inattive a causa dei fenomeni di instabilità locali, secondo il procedimen-\nto esposto in UNI EN1993-1-5, e scegliendo il minore tra i moduli così ottenuti.", "per le sezioni di classe 3, Wel,min è il modulo resistente elastico minimo della sezione in acciaio; per le sezioni di classe 4, invece, il modulo Weff,min è calcolato eliminando le parti della sezione inattive a causa dei fenomeni di instabilità locali, secondo il procedimento esposto in UNI EN1993-1-5, e scegliendo il minore tra i moduli così ottenuti."),
        block("4.2.4.1.2.3", "editorial-006", "paragraph", p(102, "98"), reg(82.954, 808, 200, 7.482), "Per la flessione biassiale si veda oltre.", "Per la flessione biassiale si veda oltre."),
        block("4.2.4.1.2.3", "editorial-007", "paragraph", p(103, "99", { wrap: true, discretionaryHyphen: true }), reg(82.954, 98.928, 428.6, 17.6), "Negli elementi inflessi caratterizzati da giunti strutturali bullonati, la presenza dei fori nelle piattabande tese dei profili può esse-\nre trascurata nel calcolo del momento resistente se è verificata la relazione", "Negli elementi inflessi caratterizzati da giunti strutturali bullonati, la presenza dei fori nelle piattabande tese dei profili può essere trascurata nel calcolo del momento resistente se è verificata la relazione"),
        formulaBlock("4.2.4.1.2.3", "formula-4-2-15", f("4.2.15"), p(103, "99", { manual: true }), reg(180, 120, 260, 25), "0,9 Af,net ftk/γM2 ≥ Af fyk/γM0 [4.2.15]"),
        block("4.2.4.1.2.3", "editorial-008", "paragraph", p(103, "99", { wrap: true }), reg(82.954, 153, 428.6, 17.6), "dove Af è l’area lorda della piattabanda tesa, Af,net è l’area della piattabanda al netto dei fori e ftk è la resistenza ultima dell’acciaio.", "dove Af è l’area lorda della piattabanda tesa, Af,net è l’area della piattabanda al netto dei fori e ftk è la resistenza ultima dell’acciaio."),
    ], ["4.2.11", "4.2.12", "4.2.13", "4.2.14", "4.2.15"]),
    addSubunit("4.2.4.1.2.4", "Taglio", [
        block("4.2.4.1.2.4", "heading", "heading", p(103, "99", { manual: true }), reg(82.954, 159, 75, 7.476), "4.2.4.1.2.4 Taglio", "4.2.4.1.2.4 Taglio"),
        block("4.2.4.1.2.4", "editorial-001", "paragraph", p(103, "99"), reg(82.954, 171, 400, 7.482), "Il valore di progetto dell’azione tagliante VEd deve rispettare la condizione", "Il valore di progetto dell’azione tagliante VEd deve rispettare la condizione", [t("Il valore di progetto dell’azione tagliante "), m("VEd", "V_{Ed}"), t(" deve rispettare la condizione")]),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-16", f("4.2.16"), p(103, "99", { manual: true }), reg(180, 185, 220, 25), "VEd/Vc,Rd ≤ 1 [4.2.16]"),
        block("4.2.4.1.2.4", "editorial-002", "paragraph", p(103, "99"), reg(82.954, 218, 428.6, 7.482), "dove la resistenza di progetto a taglio Vc,Rd, in assenza di torsione, vale", "dove la resistenza di progetto a taglio Vc,Rd, in assenza di torsione, vale", [t("dove la resistenza di progetto a taglio "), m("Vc,Rd", "V_{c,Rd}"), t(", in assenza di torsione, vale")]),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-17", f("4.2.17"), p(103, "99", { manual: true }), reg(180, 231, 220, 28), "Vc,Rd = Av fyk/(√3 γM0) [4.2.17]"),
        block("4.2.4.1.2.4", "editorial-003", "paragraph", p(103, "99", { wrap: true }), reg(82.954, 267, 428.6, 17.6), "dove Av è l’area resistente a taglio. Per profilati ad I e ad H caricati nel piano dell’anima si può assumere", "dove Av è l’area resistente a taglio. Per profilati ad I e ad H caricati nel piano dell’anima si può assumere", [t("dove "), m("Av", "A_v"), t(" è l’area resistente a taglio. Per profilati ad I e ad H caricati nel piano dell’anima si può assumere")]),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-18", f("4.2.18"), p(103, "99", { manual: true }), reg(180, 288, 220, 25), "Av = A − 2btf + (tw + 2r)tf [4.2.18]"),
        block("4.2.4.1.2.4", "editorial-004", "paragraph", p(103, "99"), reg(82.954, 320, 390, 7.482), "per profilati a C o ad U caricati nel piano dell’anima si può assumere", "per profilati a C o ad U caricati nel piano dell’anima si può assumere"),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-19", f("4.2.19"), p(103, "99", { manual: true }), reg(180, 333, 220, 25), "Av = A − 2btf + (tw + r)tf [4.2.19]"),
        block("4.2.4.1.2.4", "editorial-005", "paragraph", p(103, "99"), reg(82.954, 365, 390, 7.482), "per profilati ad I e ad H caricati nel piano delle ali si può assumere", "per profilati ad I e ad H caricati nel piano delle ali si può assumere"),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-20", f("4.2.20"), p(103, "99", { manual: true }), reg(180, 378, 220, 25), "Av = A − Σ(hw tw) [4.2.20]"),
        block("4.2.4.1.2.4", "editorial-006", "paragraph", p(103, "99"), reg(82.954, 410, 390, 7.482), "per profilati a T caricati nel piano dell’anima si può assumere", "per profilati a T caricati nel piano dell’anima si può assumere"),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-21", f("4.2.21"), p(103, "99", { manual: true }), reg(180, 423, 220, 25), "Av = 0,9(A − btf) [4.2.21]"),
        block("4.2.4.1.2.4", "editorial-007", "paragraph", p(103, "99"), reg(82.954, 455, 428.6, 17.6), "per profili rettangolari cavi “profilati a caldo” di spessore uniforme si può assumere", "per profili rettangolari cavi “profilati a caldo” di spessore uniforme si può assumere"),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-22", f("4.2.22"), p(103, "99", { manual: true }), reg(150, 478, 300, 45), "Av = Ah/(b+h) quando il carico è parallelo all’altezza del profilo; Av = Ab/(b+h) quando il carico è parallelo alla base del profilo [4.2.22]"),
        block("4.2.4.1.2.4", "editorial-008", "paragraph", p(103, "99"), reg(82.954, 532, 390, 7.482), "per sezioni circolari cave e tubi di spessore uniforme:", "per sezioni circolari cave e tubi di spessore uniforme:"),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-23", f("4.2.23"), p(103, "99", { manual: true }), reg(180, 545, 220, 25), "Av = 2A/π [4.2.23]"),
        block("4.2.4.1.2.4", "editorial-009", "paragraph", p(103, "99", { wrap: true }), reg(82.954, 578, 428.6, 58), "dove:\nA è l’area lorda della sezione del profilo,\nb è la larghezza delle ali per i profilati e la larghezza per le sezioni cave,\nhw è l’altezza dell’anima,\nh è l’altezza delle sezioni cave,\nr è il raggio di raccordo tra anima ed ala,\ntf è lo spessore delle ali,\ntw è lo spessore dell’anima.", "dove: A è l’area lorda della sezione del profilo, b è la larghezza delle ali per i profilati e la larghezza per le sezioni cave, hw è l’altezza dell’anima, h è l’altezza delle sezioni cave, r è il raggio di raccordo tra anima ed ala, tf è lo spessore delle ali, tw è lo spessore dell’anima.", [t("dove: "), m("A", "A"), t(" è l’area lorda della sezione del profilo, "), m("b", "b"), t(" è la larghezza delle ali per i profilati e la larghezza per le sezioni cave, "), m("hw", "h_w"), t(" è l’altezza dell’anima, "), m("h", "h"), t(" è l’altezza delle sezioni cave, "), m("r", "r"), t(" è il raggio di raccordo tra anima ed ala, "), m("tf", "t_f"), t(" è lo spessore delle ali, "), m("tw", "t_w"), t(" è lo spessore dell’anima.")]),
        block("4.2.4.1.2.4", "editorial-010", "paragraph", p(103, "99", { wrap: true }), reg(82.954, 645, 428.6, 27.6), "In presenza di torsione, la resistenza a taglio del profilo deve essere opportunamente ridotta. Per le sezioni ad I o H la resistenza di progetto a taglio ridotta è data dalla formula", "In presenza di torsione, la resistenza a taglio del profilo deve essere opportunamente ridotta. Per le sezioni ad I o H la resistenza di progetto a taglio ridotta è data dalla formula"),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-24", f("4.2.24"), p(103, "99", { manual: true }), reg(150, 680, 300, 30), "Vc,Rd,red = Vc,Rd √(1 − τt,Ed/(1,25 fyk/(√3 γM0))) [4.2.24]"),
        block("4.2.4.1.2.4", "editorial-011", "paragraph", p(103, "99"), reg(82.954, 720, 428.6, 7.482), "dove τt,Ed è la tensione tangenziale massima dovuta alla torsione uniforme. Per sezioni cave, invece, la formula è", "dove τt,Ed è la tensione tangenziale massima dovuta alla torsione uniforme. Per sezioni cave, invece, la formula è", [t("dove "), m("τt,Ed", "\\tau_{t,Ed}"), t(" è la tensione tangenziale massima dovuta alla torsione uniforme. Per sezioni cave, invece, la formula è")]),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-25", f("4.2.25"), p(103, "99", { manual: true }), reg(150, 735, 300, 35), "Vc,Rd,red = [1 − τt,Ed/(fyk/(√3 γM0))] Vc,Rd [4.2.25]"),
        block("4.2.4.1.2.4", "editorial-012", "paragraph", p(103, "99", { wrap: true, discretionaryHyphen: true }), reg(82.954, 778, 428.6, 17.6), "La verifica a taglio della sezione può anche essere condotta in termini tensionali (verifica elastica) nel punto più sollecitato della se-zione trasversale utilizzando la formula", "La verifica a taglio della sezione può anche essere condotta in termini tensionali (verifica elastica) nel punto più sollecitato della sezione trasversale utilizzando la formula"),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-26", f("4.2.26"), p(103, "99", { manual: true }), reg(180, 812, 220, 25), "τt,Ed/(fyk/(√3 γM0)) ≤ 1,0 [4.2.26]"),
        block("4.2.4.1.2.4", "editorial-013", "paragraph", p(103, "99", { manual: true }), reg(82.954, 840, 240, 7.482), "dove ΘEd è valutata in campo elastico lineare.", "dove τt,Ed è valutata in campo elastico lineare.", [t("dove "), m("τt,Ed", "\\tau_{t,Ed}"), t(" è valutata in campo elastico lineare.")]),
        block("4.2.4.1.2.4", "editorial-014", "paragraph", p(104, "100", { wrap: true }), reg(82.954, 98.925, 428.6, 17.6), "La verifica all’instabilità dell’anima della sezione soggetta a taglio e priva di irrigidimenti deve essere condotta in accordo con § 4.2.4.1.3.4 se", "La verifica all’instabilità dell’anima della sezione soggetta a taglio e priva di irrigidimenti deve essere condotta in accordo con § 4.2.4.1.3.4 se"),
        formulaBlock("4.2.4.1.2.4", "formula-4-2-27", f("4.2.27"), p(104, "100", { manual: true }), reg(180, 132, 220, 25), "hw/t ≤ (72/η) √(235/fyk) [4.2.27]"),
        block("4.2.4.1.2.4", "editorial-015", "paragraph", p(104, "100"), reg(82.954, 166, 428.6, 17.6), "con η assunto cautelativamente pari a 1,00 oppure valutato secondo quanto previsto in norme di comprovata validità.", "con η assunto cautelativamente pari a 1,00 oppure valutato secondo quanto previsto in norme di comprovata validità.", [t("con "), m("η", "\\eta"), t(" assunto cautelativamente pari a 1,00 oppure valutato secondo quanto previsto in norme di comprovata validità.")]),
    ], ["4.2.16", "4.2.17", "4.2.18", "4.2.19", "4.2.20", "4.2.21", "4.2.22", "4.2.23", "4.2.24", "4.2.25", "4.2.26", "4.2.27"]),
    addSubunit("4.2.4.1.2.5", "Torsione", [
        block("4.2.4.1.2.5", "heading", "heading", p(104, "100", { manual: true }), reg(82.954, 198, 75, 7.476), "4.2.4.1.2.5 Torsione", "4.2.4.1.2.5 Torsione"),
        block("4.2.4.1.2.5", "editorial-001", "paragraph", p(104, "100", { wrap: true, discretionaryHyphen: true }), reg(82.954, 210, 428.6, 37.6), "Per gli elementi soggetti a torsione, quando possano essere trascurate le distorsioni della sezione, la sollecitazione torcente di progetto, TEd, deve soddisfare la relazione", "Per gli elementi soggetti a torsione, quando possano essere trascurate le distorsioni della sezione, la sollecitazione torcente di progetto, TEd, deve soddisfare la relazione", [t("Per gli elementi soggetti a torsione, quando possano essere trascurate le distorsioni della sezione, la sollecitazione torcente di progetto, "), m("TEd", "T_{Ed}"), t(", deve soddisfare la relazione")]),
        formulaBlock("4.2.4.1.2.5", "formula-4-2-28", f("4.2.28"), p(104, "100", { manual: true }), reg(180, 252, 220, 25), "TEd/TRd ≤ 1,0 [4.2.28]"),
        block("4.2.4.1.2.5", "editorial-002", "paragraph", p(104, "100", { wrap: true }), reg(82.954, 286, 428.6, 27.6), "essendo TRd la resistenza torsionale di progetto della sezione trasversale. La torsione agente TEd può essere considerata come la somma di due contributi", "essendo TRd la resistenza torsionale di progetto della sezione trasversale. La torsione agente TEd può essere considerata come la somma di due contributi", [t("essendo "), m("TRd", "T_{Rd}"), t(" la resistenza torsionale di progetto della sezione trasversale. La torsione agente "), m("TEd", "T_{Ed}"), t(" può essere considerata come la somma di due contributi")]),
        formulaBlock("4.2.4.1.2.5", "formula-4-2-29", f("4.2.29"), p(104, "100", { manual: true }), reg(180, 320, 220, 25), "TEd = Tt,Ed + Tw,Ed [4.2.29]"),
        block("4.2.4.1.2.5", "editorial-003", "paragraph", p(104, "100"), reg(82.954, 354, 428.6, 7.482), "dove Tt,Ed è la torsione uniforme e Tw,Ed è la torsione per ingobbamento impedito.", "dove Tt,Ed è la torsione uniforme e Tw,Ed è la torsione per ingobbamento impedito.", [t("dove "), m("Tt,Ed", "T_{t,Ed}"), t(" è la torsione uniforme e "), m("Tw,Ed", "T_{w,Ed}"), t(" è la torsione per ingobbamento impedito.")]),
    ], ["4.2.28", "4.2.29"]),
    addSubunit("4.2.4.1.2.6", "Flessione e taglio", [
        block("4.2.4.1.2.6", "heading", "heading", p(104, "100", { manual: true }), reg(82.954, 388, 110, 7.476), "4.2.4.1.2.6 Flessione e taglio", "4.2.4.1.2.6 Flessione e taglio"),
        block("4.2.4.1.2.6", "editorial-001", "paragraph", p(104, "100", { wrap: true }), reg(82.954, 400, 428.6, 27.6), "Se il taglio di progetto VEd è inferiore a metà della resistenza di progetto a taglio Vc,Rd", "Se il taglio di progetto VEd è inferiore a metà della resistenza di progetto a taglio Vc,Rd", [t("Se il taglio di progetto "), m("VEd", "V_{Ed}"), t(" è inferiore a metà della resistenza di progetto a taglio "), m("Vc,Rd", "V_{c,Rd}")]),
        formulaBlock("4.2.4.1.2.6", "formula-4-2-30", f("4.2.30"), p(104, "100", { manual: true }), reg(180, 435, 220, 25), "VEd ≤ 0,5 Vc,Rd [4.2.30]"),
        block("4.2.4.1.2.6", "editorial-002", "paragraph", p(104, "100", { wrap: true }), reg(82.954, 468, 428.6, 37.6), "si può trascurare l’influenza del taglio sulla resistenza a flessione, eccetto nei casi in cui l’instabilità per taglio riduca la resistenza a flessione della sezione. Se il taglio di progetto VEd è superiore a metà della resistenza di progetto a taglio Vc,Rd bisogna tener conto dell’influenza del taglio sulla resistenza a flessione.", "si può trascurare l’influenza del taglio sulla resistenza a flessione, eccetto nei casi in cui l’instabilità per taglio riduca la resistenza a flessione della sezione. Se il taglio di progetto VEd è superiore a metà della resistenza di progetto a taglio Vc,Rd bisogna tener conto dell’influenza del taglio sulla resistenza a flessione."),
        block("4.2.4.1.2.6", "editorial-003", "paragraph", p(104, "100"), reg(82.954, 514, 90, 7.482), "Posto", "Posto"),
        formulaBlock("4.2.4.1.2.6", "formula-4-2-31", f("4.2.31"), p(104, "100", { manual: true }), reg(180, 526, 220, 30), "ρ = [2VEd/Vc,Rd − 1]² [4.2.31]"),
        block("4.2.4.1.2.6", "editorial-004", "paragraph", p(104, "100", { wrap: true }), reg(82.954, 565, 428.6, 27.6), "la resistenza a flessione si determina assumendo per l’area resistente a taglio Av la tensione di snervamento ridotta (1 − ρ) fyk.", "la resistenza a flessione si determina assumendo per l’area resistente a taglio Av la tensione di snervamento ridotta (1 − ρ) fyk.", [t("la resistenza a flessione si determina assumendo per l’area resistente a taglio "), m("Av", "A_v"), t(" la tensione di snervamento ridotta (1 − "), m("ρ", "\\rho"), t(") "), m("fyk", "f_{yk}"), t(".")]),
        block("4.2.4.1.2.6", "editorial-005", "paragraph", p(104, "100", { wrap: true, discretionaryHyphen: true }), reg(82.954, 600, 428.6, 27.6), "Per le sezioni ad I o ad H di classe 1 e 2 doppiamente simmetriche, soggette a flessione e taglio nel piano dell’anima, la corrispondente resistenza convenzionale di progetto a flessione retta può essere valutata come:", "Per le sezioni ad I o ad H di classe 1 e 2 doppiamente simmetriche, soggette a flessione e taglio nel piano dell’anima, la corrispondente resistenza convenzionale di progetto a flessione retta può essere valutata come:"),
        formulaBlock("4.2.4.1.2.6", "formula-4-2-32", f("4.2.32"), p(104, "100", { manual: true }), reg(150, 635, 300, 35), "My,V,Rd = [(Wpl,y − ρAw²/(4tw)) fyk]/γM0 ≤ My,c,Rd [4.2.32]"),
        block("4.2.4.1.2.6", "editorial-006", "paragraph", p(104, "100"), reg(82.954, 680, 260, 7.482), "in cui Aw rappresenta l’area dell’anima del profilo.", "in cui Aw rappresenta l’area dell’anima del profilo.", [t("in cui "), m("Aw", "A_w"), t(" rappresenta l’area dell’anima del profilo.")]),
    ], ["4.2.30", "4.2.31", "4.2.32"]),
    addSubunit("4.2.4.1.2.7", "Presso o tenso-flessione retta", [
        block("4.2.4.1.2.7", "heading", "heading", p(104, "100", { manual: true }), reg(82.954, 708, 180, 7.476), "4.2.4.1.2.7 Presso o tenso-flessione retta", "4.2.4.1.2.7 Presso o tenso-flessione retta"),
        block("4.2.4.1.2.7", "editorial-001", "paragraph", p(104, "100"), reg(82.954, 720, 428.6, 17.6), "La presso- o tenso-flessione retta può essere trattata con riferimento a metodi di comprovata validità.", "La presso- o tenso-flessione retta può essere trattata con riferimento a metodi di comprovata validità."),
        block("4.2.4.1.2.7", "editorial-002", "paragraph", p(104, "100", { wrap: true, discretionaryHyphen: true }), reg(82.954, 744, 428.6, 27.6), "Per le sezioni ad I o ad H di classe 1 e 2 doppiamente simmetriche, soggette a presso o tenso-flessione nel piano dell’anima, la corrispondente resistenza convenzionale di progetto a flessione retta può essere valutata come:", "Per le sezioni ad I o ad H di classe 1 e 2 doppiamente simmetriche, soggette a presso o tenso-flessione nel piano dell’anima, la corrispondente resistenza convenzionale di progetto a flessione retta può essere valutata come:"),
        formulaBlock("4.2.4.1.2.7", "formula-4-2-33", f("4.2.33"), p(104, "100", { manual: true }), reg(150, 780, 300, 30), "MN,y,Rd = Mpl,y,Rd (1 − n)/(1 − 0,5a) ≤ Mpl,y,Rd [4.2.33]"),
        block("4.2.4.1.2.7", "editorial-003", "paragraph", p(104, "100", { wrap: true }), reg(82.954, 818, 428.6, 17.6), "Per le sezioni ad I o ad H di classe 1 e 2 doppiamente simmetriche, soggette a presso o tenso-flessione nel piano delle ali, la corrispondente resistenza convenzionale di progetto a flessione retta può essere valutata come:", "Per le sezioni ad I o ad H di classe 1 e 2 doppiamente simmetriche, soggette a presso o tenso-flessione nel piano delle ali, la corrispondente resistenza convenzionale di progetto a flessione retta può essere valutata come:"),
        formulaBlock("4.2.4.1.2.7", "formula-4-2-34", f("4.2.34"), p(104, "100", { manual: true }), reg(150, 840, 300, 25), "MN,z,Rd = Mpl,z,Rd per n ≤ a [4.2.34]"),
        block("4.2.4.1.2.7", "editorial-004", "paragraph", p(104, "100"), reg(82.954, 870, 80, 7.482), "o per n > a", "o per n > a"),
        formulaBlock("4.2.4.1.2.7", "formula-4-2-35", f("4.2.35"), p(104, "100", { manual: true }), reg(150, 885, 300, 35), "MN,z,Rd = Mpl,z,Rd [1 − ((n − a)/(1 − a))²] per n > a [4.2.35]"),
        block("4.2.4.1.2.7", "editorial-005", "paragraph", p(104, "100"), reg(82.954, 925, 180, 7.482), "essendo", "essendo"),
        block("4.2.4.1.2.7", "editorial-006", "paragraph", p(104, "100", { wrap: true }), reg(82.954, 938, 428.6, 27.6), "Mpl,y,Rd il momento resistente plastico di progetto a flessione semplice nel piano dell’anima, Mpl,z,Rd il momento resistente plastico di progetto a flessione semplice nel piano delle ali,", "Mpl,y,Rd il momento resistente plastico di progetto a flessione semplice nel piano dell’anima, Mpl,z,Rd il momento resistente plastico di progetto a flessione semplice nel piano delle ali,", [m("Mpl,y,Rd", "M_{pl,y,Rd}"), t(" il momento resistente plastico di progetto a flessione semplice nel piano dell’anima, "), m("Mpl,z,Rd", "M_{pl,z,Rd}"), t(" il momento resistente plastico di progetto a flessione semplice nel piano delle ali,")]),
        block("4.2.4.1.2.7", "editorial-007", "paragraph", p(104, "100"), reg(82.954, 970, 90, 7.482), "e posto:", "e posto:"),
        formulaBlock("4.2.4.1.2.7", "formula-4-2-36", f("4.2.36"), p(104, "100", { manual: true }), reg(150, 985, 220, 25), "n = NEd/Npl,Rd [4.2.36]"),
        formulaBlock("4.2.4.1.2.7", "formula-4-2-37", f("4.2.37"), p(104, "100", { manual: true }), reg(150, 1015, 220, 25), "a = (A − 2btf)/A ≤ 0,5 [4.2.37]"),
        block("4.2.4.1.2.7", "editorial-008", "paragraph", p(104, "100", { wrap: true }), reg(82.954, 1045, 428.6, 37.6), "dove:\nA è l’area lorda della sezione,\nb è la larghezza delle ali,\ntf è lo spessore delle ali.", "dove: A è l’area lorda della sezione, b è la larghezza delle ali, tf è lo spessore delle ali.", [t("dove: "), m("A", "A"), t(" è l’area lorda della sezione, "), m("b", "b"), t(" è la larghezza delle ali, "), m("tf", "t_f"), t(" è lo spessore delle ali.")]),
        block("4.2.4.1.2.7", "editorial-009", "paragraph", p(104, "100", { wrap: true }), reg(82.954, 1090, 428.6, 17.6), "Per sezioni generiche, la verifica può essere condotta controllando che il momento di progetto sia minore del momento plastico di progetto, ridotto per effetto dello sforzo normale di progetto, MN,y,Rd.", "Per sezioni generiche, la verifica può essere condotta controllando che il momento di progetto sia minore del momento plastico di progetto, ridotto per effetto dello sforzo normale di progetto, MN,y,Rd.", [t("Per sezioni generiche, la verifica può essere condotta controllando che il momento di progetto sia minore del momento plastico di progetto, ridotto per effetto dello sforzo normale di progetto, "), m("MN,y,Rd", "M_{N,y,Rd}"), t(".")]),
    ], ["4.2.33", "4.2.34", "4.2.35", "4.2.36", "4.2.37"]),
    addSubunit("4.2.4.1.2.8", "Presso o tenso flessione biassiale", [
        block("4.2.4.1.2.8", "heading", "heading", p(105, "101", { manual: true }), reg(82.954, 159, 190, 7.476), "4.2.4.1.2.8 Presso o tenso flessione biassiale", "4.2.4.1.2.8 Presso o tenso flessione biassiale"),
        block("4.2.4.1.2.8", "editorial-001", "paragraph", p(105, "101"), reg(82.954, 171, 428.6, 17.6), "La presso- o tenso-flessione biassiale può essere trattata con riferimento a metodi di comprovata validità.", "La presso- o tenso-flessione biassiale può essere trattata con riferimento a metodi di comprovata validità."),
        block("4.2.4.1.2.8", "editorial-002", "paragraph", p(105, "101", { wrap: true }), reg(82.954, 195, 428.6, 27.6), "Per le sezioni ad I o ad H di classe 1 e 2 doppiamente simmetriche, soggette a presso o tenso-flessione biassiale, la condizione di resistenza può essere valutata come:", "Per le sezioni ad I o ad H di classe 1 e 2 doppiamente simmetriche, soggette a presso o tenso-flessione biassiale, la condizione di resistenza può essere valutata come:"),
        formulaBlock("4.2.4.1.2.8", "formula-4-2-38", f("4.2.38"), p(105, "101", { manual: true }), reg(150, 230, 300, 35), "(My,Ed/MN,y,Rd)² + (Mz,Ed/MN,z,Rd)^(5n) ≤ 1 [4.2.38]"),
        block("4.2.4.1.2.8", "editorial-003", "paragraph", p(105, "101", { wrap: true }), reg(82.954, 275, 428.6, 27.6), "con n ≥ 0,2 essendo n = NEd / Npl,Rd. Nel caso in cui n < 0,2, e comunque per sezioni generiche di classe 1 e 2, la verifica può essere condotta cautelativamente controllando che:", "con n ≥ 0,2 essendo n = NEd / Npl,Rd. Nel caso in cui n < 0,2, e comunque per sezioni generiche di classe 1 e 2, la verifica può essere condotta cautelativamente controllando che:", [t("con "), m("n", "n"), t(" ≥ 0,2 essendo "), m("n", "n"), t(" = "), m("NEd", "N_{Ed}"), t(" / "), m("Npl,Rd", "N_{pl,Rd}"), t(". Nel caso in cui "), m("n", "n"), t(" < 0,2, e comunque per sezioni generiche di classe 1 e 2, la verifica può essere condotta cautelativamente controllando che:")]),
        formulaBlock("4.2.4.1.2.8", "formula-4-2-39", f("4.2.39"), p(105, "101", { manual: true }), reg(150, 315, 300, 35), "My,Ed/MN,y,Rd + Mz,Ed/MN,z,Rd ≤ 1 [4.2.39]"),
        block("4.2.4.1.2.8", "editorial-004", "paragraph", p(105, "101", { wrap: true }), reg(82.954, 360, 428.6, 27.6), "Per le sezioni di classe 3, in assenza di azioni di taglio, la verifica a presso o tenso-flessione retta o biassiale è condotta in termini tensionali utilizzando le verifiche elastiche; la tensione agente è calcolata considerando la eventuale presenza dei fori.", "Per le sezioni di classe 3, in assenza di azioni di taglio, la verifica a presso o tenso-flessione retta o biassiale è condotta in termini tensionali utilizzando le verifiche elastiche; la tensione agente è calcolata considerando la eventuale presenza dei fori."),
        block("4.2.4.1.2.8", "editorial-005", "paragraph", p(105, "101", { wrap: true }), reg(82.954, 395, 428.6, 27.6), "Per le sezioni di classe 4, le verifiche devono essere condotte con riferimento alla resistenza elastica (verifica tensionale); si possono utilizzare le proprietà geometriche efficaci della sezione trasversale considerando la eventuale presenza dei fori.", "Per le sezioni di classe 4, le verifiche devono essere condotte con riferimento alla resistenza elastica (verifica tensionale); si possono utilizzare le proprietà geometriche efficaci della sezione trasversale considerando la eventuale presenza dei fori."),
    ], ["4.2.38", "4.2.39"]),
    addSubunit("4.2.4.1.2.9", "Flessione, taglio e sforzo assiale", [
        block("4.2.4.1.2.9", "heading", "heading", p(105, "101", { manual: true }), reg(82.954, 440, 190, 7.476), "4.2.4.1.2.9 Flessione, taglio e sforzo assiale", "4.2.4.1.2.9 Flessione, taglio e sforzo assiale"),
        block("4.2.4.1.2.9", "editorial-001", "paragraph", p(105, "101", { wrap: true }), reg(82.954, 452, 428.6, 17.6), "Nel calcolo del momento flettente resistente devono essere considerati gli effetti di sforzo assiale e taglio, se presenti.", "Nel calcolo del momento flettente resistente devono essere considerati gli effetti di sforzo assiale e taglio, se presenti."),
        block("4.2.4.1.2.9", "editorial-002", "paragraph", p(105, "101", { wrap: true }), reg(82.954, 476, 428.6, 37.6), "Nel caso in cui il taglio sollecitante di progetto, VEd, sia inferiore al 50% della resistenza di progetto a taglio, Vc,Rd, la resistenza a flessione della sezione può essere calcolata con le formule per la tenso/presso flessione. Se la sollecitazione di progetto a taglio supera il 50% della resistenza di progetto a taglio, si assume una tensione di snervamento ridotta per l’interazione tra flessione e taglio: fy,red = (1 − ρ) fyk dove:", "Nel caso in cui il taglio sollecitante di progetto, VEd, sia inferiore al 50% della resistenza di progetto a taglio, Vc,Rd, la resistenza a flessione della sezione può essere calcolata con le formule per la tenso/presso flessione. Se la sollecitazione di progetto a taglio supera il 50% della resistenza di progetto a taglio, si assume una tensione di snervamento ridotta per l’interazione tra flessione e taglio: fy,red = (1 − ρ) fyk dove:", [t("Nel caso in cui il taglio sollecitante di progetto, "), m("VEd", "V_{Ed}"), t(", sia inferiore al 50% della resistenza di progetto a taglio, "), m("Vc,Rd", "V_{c,Rd}"), t(", la resistenza a flessione della sezione può essere calcolata con le formule per la tenso/presso flessione. Se la sollecitazione di progetto a taglio supera il 50% della resistenza di progetto a taglio, si assume una tensione di snervamento ridotta per l’interazione tra flessione e taglio: "), m("fy,red", "f_{y,red}"), t(" = (1 − "), m("ρ", "\\rho"), t(") "), m("fyk", "f_{yk}"), t(" dove:")]),
        formulaBlock("4.2.4.1.2.9", "formula-4-2-40", f("4.2.40"), p(105, "101", { manual: true }), reg(150, 530, 300, 30), "ρ = [2VEd/Vc,Rd − 1]² [4.2.40]"),
        block("4.2.4.1.2.9", "editorial-003", "paragraph", p(105, "101", { wrap: true }), reg(82.954, 570, 428.6, 27.6), "Per le sezioni di classe 3 e classe 4 le verifiche devono essere condotte con riferimento alla resistenza elastica (verifica tensionale); per le sezioni di classe 4 si possono utilizzare le proprietà geometriche efficaci della sezione trasversale.", "Per le sezioni di classe 3 e classe 4 le verifiche devono essere condotte con riferimento alla resistenza elastica (verifica tensionale); per le sezioni di classe 4 si possono utilizzare le proprietà geometriche efficaci della sezione trasversale."),
    ], ["4.2.40"]),
);

await mkdir(unitDirectory, { recursive: true });
await mkdir(assetDirectory, { recursive: true });
const manifest = { $schema: "urn:structural-codes:schema:asset-manifest:v2", schemaVersion: "2.0.0-alpha.1", recordType: "asset-manifest", document: "ntc2018", section: "4.2-step4a", sourceId, status: "transcribed-unreviewed", formulas: formulas.map(([n, unit, page, latex]) => ({ id: f(n), unitId: unitId(unit), officialNumber: n, pdfPage: page, latex })), tables: [table], figures: [] };
await Promise.all([...units.map((unit) => writeFile(join(unitDirectory, `${unit.numbering.official}.json`), `${JSON.stringify(unit, null, 2)}\n`, "utf8")), writeFile(join(assetDirectory, "4.2-step4a.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8")]);
console.log(`NTC 4.2 step4a: generate ${units.length} unità, ${formulas.length} formule e 1 tabella.`);
