/* eslint-disable @typescript-eslint/no-explicit-any, no-useless-escape */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const root = fileURLToPath(new URL("../", import.meta.url));
const sourceId = "gu-so8-2018-ntc";
const workId = "it-mit:dm:2018-01-17:ntc2018";
const expressionId = "it-mit:dm:2018-01-17:ntc2018:original-it";
const ruleVersion = "ntc5-editorial-profile-0.1.0";
const createdAt = "2026-08-09T00:00:00Z";
const unitId = (n: string) => `urn:structural-codes:it:unit:ntc2018:${n}`;
const asset = (kind: "formula" | "table" | "figure", suffix: string) => `urn:structural-codes:it:asset:${kind}:ntc2018:${suffix}`;
const sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");

type Inline = { kind: "text"; value: string } | { kind: "math"; value: string; latex: string };
type Block = { kind: "heading" | "paragraph" | "list-item" | "formula-ref" | "table-ref" | "figure-ref"; page: number; text?: string; raw?: string; assetId?: string; inline?: Inline[] };
type UnitDef = { number: string; title: string; blocks: Block[] };
function inlineMath(text: string): Inline[] {
    const patterns: Array<[RegExp, string]> = [[/γG1/g, "\\gamma_{G1}"], [/γG2/g, "\\gamma_{G2}"], [/γB/g, "\\gamma_B"], [/γQ/g, "\\gamma_Q"], [/γQi/g, "\\gamma_{Qi}"], [/γP/g, "\\gamma_P"], [/γCed/g, "\\gamma_{Ced}"], [/Ψ0/g, "\\Psi_0"], [/Ψ1/g, "\\Psi_1"], [/Ψ2/g, "\\Psi_2"], [/qA1d/g, "q_{A1d}"], [/qA2d/g, "q_{A2d}"], [/δh/g, "\\delta_h"], [/LΦ/g, "L_{\\Phi}"], [/\bV\b/g, "V"], [/\bR\b/g, "R"]];
    const matches: Array<{ start: number; end: number; value: string; latex: string }> = [];
    for (const [pattern, latex] of patterns) { pattern.lastIndex = 0; let match: RegExpExecArray | null; while ((match = pattern.exec(text)) !== null) { const start = match.index; const end = start + match[0].length; if (!matches.some((item) => start < item.end && end > item.start)) matches.push({ start, end, value: match[0], latex }); } }
    matches.sort((a, b) => a.start - b.start); const result: Inline[] = []; let cursor = 0;
    for (const match of matches) { if (match.start > cursor) result.push({ kind: "text", value: text.slice(cursor, match.start) }); result.push({ kind: "math", value: match.value, latex: match.latex }); cursor = match.end; }
    if (cursor < text.length) result.push({ kind: "text", value: text.slice(cursor) }); return result.length ? result : [{ kind: "text", value: text }];
}
const p = (page: number, text: string, raw = text): Block => ({ kind: "paragraph", page, text, raw, inline: inlineMath(text) });
const li = (page: number, text: string, raw = text): Block => ({ kind: "list-item", page, text, raw, inline: inlineMath(text) });
const h = (page: number, number: string, title: string, raw = `${number}. ${title}`): Block => ({ kind: "heading", page, text: `${number} ${title}`, raw });
const ih = (page: number, text: string): Block => ({ kind: "heading", page, text, raw: text });
const ref = (kind: "formula-ref" | "table-ref" | "figure-ref", page: number, suffix: string): Block => ({ kind, page, assetId: asset(kind.replace("-ref", "") as "formula" | "table" | "figure", suffix) });
const U = (number: string, title: string, page: number, blocks: Block[] = []): UnitDef => ({ number, title, blocks: [h(page, number, title), ...blocks] });

const units: UnitDef[] = [
    U("5.2.3.1.3", "SIMULTANEITÀ DELLE AZIONI DA TRAFFICO - VALORI CARATTERISTICI DELLE AZIONI COMBINATE IN GRUPPI DI CARICHI", 181, [
        p(181, "Gli effetti dei carichi verticali dovuti alla presenza dei convogli vanno sempre combinati con le altre azioni derivanti dal traffico ferroviario, adottando i coefficienti indicati in Tab. 5.2.IV."), ref("table-ref", 182, "5.2.iv"),
        p(181, "Il carico verticale, nel caso di ponti con più binari, è quello che si ottiene con i treni specificati nella Tab. 5.2.III."),
        p(181, "Nella valutazione degli effetti di interazione, alle azioni conseguenti all’applicazione dei carichi da traffico ferroviario si adotteranno gli stessi coefficienti parziali dei carichi che li generano."),
        p(181, "I valori fra parentesi indicati nella Tab. 5.2.IV vanno assunti quando l’azione risulta favorevole nei riguardi della verifica che si sta svolgendo."),
        p(182, "Il gruppo 4 è da considerarsi esclusivamente per le verifiche a fessurazione. I valori indicati fra parentesi si assumeranno pari a: (0,6) per impalcati con 2 binari caricati e (0,4) per impalcati con tre o più binari caricati.", "Il gruppo 4 è da considerarsi esclusivamente per le verifiche a fessurazione. I valori indicati fra parentesi si assumeranno pari a:\n(0,6) per impalcati con 2 binari caricati e (0,4) per impalcati con tre o più binari caricati."),
    ]),
    U("5.2.3.1.4", "VALORI RARI E FREQUENTI DELLE AZIONI DA TRAFFICO FERROVIARIO", 182, [p(182, "Le azioni derivanti da ciascuno dei gruppi di carico definiti nella Tab. 5.2.IV sono da intendersi come un’unica azione caratteristica da utilizzarsi nella definizione dei valori rari e frequenti.", "Le azioni derivanti da ciascuno dei gruppi di carico definiti nella Tab. 5.2.IV sono da intendersi come un’unica azione caratteristi-\nca da utilizzarsi nella definizione dei valori rari e frequenti.")]),
    U("5.2.3.1.5", "VALORI QUASI-PERMANENTI DELLE AZIONI DA TRAFFICO FERROVIARIO", 182, [p(182, "I valori quasi permanenti delle azioni da traffico ferroviario possono assumersi uguali a zero ad eccezione delle combinazioni sismiche.", "I valori quasi permanenti delle azioni da traffico ferroviario possono assumersi uguali a zero ad eccezione delle combinazioni si-\smiche.")]),
    U("5.2.3.1.6", "AZIONI DA TRAFFICO FERROVIARIO IN SITUAZIONI TRANSITORIE", 182, [p(182, "Nelle verifiche di progetto per situazioni transitorie dovute alla manutenzione dei binari o del ponte, i valori caratteristici delle azioni da traffico, caso per caso, sono da concordarsi con l’autorità ferroviaria.")]),
    U("5.2.3.2", "VERIFICHE AGLI SLU E SLE", 182, [],),
    U("5.2.3.2.1", "REQUISITI CONCERNENTI GLI SLU", 182, [
        p(182, "Per le verifiche agli stati limite ultimi si adottano i valori dei coefficienti parziali γ in Tab. 5.2.V e i coefficienti di combinazione Ψ in Tab. 5.2.VI.", "Per le verifiche agli stati limite ultimi si adottano i valori dei coefficienti parziali J in Tab. 5.2.V e i coefficienti di combinazione <\nin Tab. 5.2.VI."), ref("table-ref", 182, "5.2.v"), ref("table-ref", 183, "5.2.vi"),
        p(183, "Nella Tab. 5.2.V il significato dei simboli è il seguente:"),
        p(183, "γG1 coefficiente parziale del peso proprio della struttura, del terreno e dell’acqua, quando pertinente;"),
        p(183, "γG2 coefficiente parziale dei pesi propri degli elementi non strutturali;"), p(183, "γB coefficiente parziale del peso proprio del ballast;"),
        p(183, "γQ coefficiente parziale delle azioni variabili da traffico;"), p(183, "γQi coefficiente parziale delle azioni variabili;"), p(183, "γP coefficiente parziale delle azioni di precompressione"),
        p(183, "γCed coefficiente parziale delle azioni di ritiro, viscosità e cedimenti non imposti appositamente."),
        p(183, "Nella Tab. 5.2.VI il significato dei coefficienti di combinazione Ψ è riportato nella tabella stessa."),
    ]),
    U("5.2.3.2.2", "REQUISITI CONCERNENTI GLI SLE", 183, [
        p(183, "L’assetto di una struttura, da valutarsi in base alle combinazioni di carico previste dalla presente norma, deve risultare compatibile con la geometria della struttura stessa in relazione alle esigenze dei convogli ferroviari."),
        p(183, "Per le verifiche agli stati limite d’esercizio si adottano i valori dei coefficienti parziali in Tab. 5.2.VI."), ref("table-ref", 183, "5.2.vii"),
        p(183, "Ove necessario in luogo dei gruppi delle azioni da traffico ferroviario definiti in Tab. 5.2.IV possono considerarsi le singole azioni con i coefficienti di combinazione indicati in Tab. 5.2.VII."),
        p(184, "Per la valutazione degli effetti dell’interazione si usano gli stessi coefficienti Ψ adottati per le azioni che provocano dette interazioni e cioè: temperatura, carichi verticali da traffico ferroviario, frenatura."),
        p(184, "In ogni caso le azioni aerodinamiche devono essere cumulate con l’azione del vento. L’azione risultante dovrà essere maggiore di un valore minimo, funzione della velocità della linea e comunque di 1,5 kN/m² sia nella verifica agli SLE (combinazione caratteristica) sia nella verifica agli SLU con γQ=1,00 e γQi=1,00.", "In ogni caso le azioni aerodinamiche devono essere cumulate con l’azione del vento. L’azione risultante dovrà essere maggiore di\nun valore minimo, funzione della velocità della linea e comunque di 1,5 kN/m² sia nella verifica agli SLE (combinazione caratteri-\nstica) sia nella verifica agli SLU con ·Q = 1,00 e ·Qi=1,00."),
    ]),
    U("5.2.3.2.2.1", "STATI LIMITE DI ESERCIZIO PER LA SICUREZZA DEL TRAFFICO FERROVIARIO", 184, [
        ih(184, "Accelerazioni verticali dell’impalcato"),
        p(184, "Questa verifica è richiesta per opere sulle quali la velocità di esercizio è superiore ai 200 km/h o quando la frequenza propria della struttura non è compresa nei limiti indicati nella Fig. 5.2.7. La verifica, quando necessaria, dovrà essere condotta considerando convogli reali.", "Questa verifica è richiesta per opere sulle quali la velocità di esercizio è superiore ai 200 km/h o quando la frequenza propria del-\nla struttura non è compresa nei limiti indicati nella Fig. 5.2.7. La verifica, quando necessaria, dovrà essere condotta considerando\nconvogli reali."),
        p(184, "In mancanza di ulteriori specificazioni, per ponti con armamento su ballast, non devono registrarsi accelerazioni verticali superiori a 3,5 m/s² nel campo di frequenze da 0 a 20 Hz."),
        ih(184, "Deformazioni torsionali dell’impalcato"),
        p(184, "La torsione dell’impalcato del ponte è calcolata considerando il treno di carico LM 71 incrementato con il corrispondente coefficiente dinamico."),
        p(184, "Il massimo sghembo, misurato su una lunghezza di 3 m e considerando le rotaie solidali all’impalcato (Fig. 5.2.14), non deve eccedere i seguenti valori:"), ref("figure-ref", 184, "5.2.14"),
        li(184, "per V ≤ 120 km/h; t ≤ 4,5 mm/3m"), li(184, "per 120 < V ≤ 200 km/h; t ≤ 3,0 mm/3m"), li(184, "per V > 200 km/h; t ≤ 1,5 mm/3m"),
        p(184, "Per velocità V > 200 km/h si deve inoltre verificare che per convogli reali, moltiplicati per il relativo incremento dinamico, risulti t ≤ 1,2 mm/3m."),
        p(184, "In mancanza di ulteriori specifiche, lo sghembo complessivo dovuto alla geometria del binario (curve di transizione) e quello dovuto alla deformazione dell’impalcato, non deve comunque eccedere i 6 mm/3 m.", "In mancanza di ulteriori specifiche, lo sghembo complessivo dovuto alla geometria del binario (curve di transizione) e quello do-\nvuto alla deformazione dell’impalcato, non deve comunque eccedere i 6 mm/3 m."),
        ih(184, "Inflessione nel piano orizzontale dell’impalcato"),
        p(184, "Considerando la presenza del treno di carico LM 71, incrementato con il corrispondente coefficiente dinamico, l’azione del vento, la forza laterale (serpeggio), la forza centrifuga e gli effetti della variazione di temperatura lineare fra i due lati dell’impalcato stabilita al § 5.2.2.4, l’inflessione nel piano orizzontale dell’impalcato non deve produrre:"),
        li(184, "una variazione angolare maggiore di quella fornita nella successiva Tab. 5.2.VIII;"), li(184, "un raggio di curvatura orizzontale minore dei valori di cui alla citata tabella."),
        p(184, "Il raggio di curvatura, nel caso di impalcati a semplice appoggio, è dato dalla seguente espressione:"), ref("formula-ref", 184, "5.2.11"),
        p(184, "dove δh rappresenta la freccia orizzontale."), ref("table-ref", 184, "5.2.viii"),
        p(185, "La freccia orizzontale deve includere anche l’effetto della deformazione della sottostruttura del ponte (pile, spalle e fondazioni), qualora esso sia sfavorevole alla verifica.", "La freccia orizzontale deve includere anche l’effetto della deformazione della sottostruttura del ponte (pile, spalle e fondazio-\nni), qualora esso sia sfavorevole alla verifica."),
    ]),
    U("5.2.3.2.3", "VERIFICHE ALLO STATO LIMITE DI FATICA", 185, [
        p(185, "Per strutture e elementi strutturali che presentano dettagli sensibili a fenomeni di fatica vanno effettuate opportune verifiche nei confronti di questo fenomeno."),
        p(185, "Le verifiche saranno condotte considerando idonei spettri di carico. La determinazione dell’effettivo spettro di carico da considerare nella verifica del ponte dovrà essere effettuata in base alle caratteristiche funzionali e d’uso della infrastruttura ferroviaria cui l’opera appartiene.", "Le verifiche saranno condotte considerando idonei spettri di carico. La determinazione dell’effettivo spettro di carico da conside-\nrare nella verifica del ponte dovrà essere effettuata in base alle caratteristiche funzionali e d’uso della infrastruttura ferroviaria\ncui l’opera appartiene."),
    ]),
    U("5.2.3.2.4", "VERIFICHE ALLO STATO LIMITE DI FESSURAZIONE", 185, [p(185, "Per assicurare la funzionalità e la durabilità delle strutture viene prefissato uno stato limite di fessurazione commisurato alle condizioni ambientali, di sollecitazione e di ispezionabilità, nonché alla sensibilità delle armature. Tali verifiche vengono condotte per le azioni da traffico gruppo 4, Tab. 5.2.IV.", "Per assicurare la funzionalità e la durabilità delle strutture viene prefissato uno stato limite di fessurazione commisurato alle\ncondizioni ambientali, di sollecitazione e di ispezionabilità, nonché alla sensibilità delle armature. Tali verifiche vengono condot-\nte per le azioni da traffico gruppo 4, Tab. 5.2.IV.")]),
];

const pageRecords = new Map<number, any>();
for (const page of [182, 183, 184, 185]) pageRecords.set(page, JSON.parse(await readFile(join(root, "evidence", sourceId, "pages", `page-${String(page).padStart(4, "0")}.json`), "utf8")));
const pageRegion = (page: number) => ({ coordinateSystem: "pdf-points-top-left", x: 73, y: 75, width: 455, height: Math.min(680, (pageRecords.get(page)?.page?.height ?? 842) - 100) });
function transformations(raw: string, normalized: string): any[] { if (raw === normalized) return []; return [{ operation: "remove-control-character", ruleVersion, note: "Rimossi caratteri di controllo privi di resa visuale." }, { operation: "remove-discretionary-hyphen", ruleVersion, note: "Unite le parole divise esclusivamente dall’andata a capo tipografica." }, { operation: "join-line-wrap", ruleVersion, note: "Rimosse le andate a capo di impaginazione, conservando capoversi ed elenchi." }, { operation: "manual-correction", ruleVersion, note: "Ripristinati i glifi matematici e i caratteri riconoscibili nel render ufficiale." }, { operation: "normalize-whitespace", ruleVersion, note: "Uniformati gli spazi dopo la ricomposizione delle righe." }, { operation: "unicode-nfc", ruleVersion, note: "Testo normalizzato in Unicode NFC." }]; }
function makeBlock(number: string, index: number, def: Block): any { const blockId = `${unitId(number)}#block-${def.kind === "heading" && index === 0 ? "heading" : `editorial-${String(index).padStart(3, "0")}`}`; if (def.kind.endsWith("-ref")) return { blockId, kind: def.kind, origin: "official", assetId: def.assetId, evidence: { sourceId, pdfPage: def.page, printedPage: String(def.page - 4), region: pageRegion(def.page), extraction: { method: "manual-transcription", tool: "codex-source-transcription", toolVersion: ruleVersion }, transformations: [{ operation: "manual-correction", ruleVersion, note: "Asset collocato nel punto normativo originario; resta da revisionare puntualmente." }], rawSha256: sha256(def.assetId ?? blockId), normalizedSha256: sha256(def.assetId ?? blockId) } }; const normalized = def.text ?? ""; const raw = def.raw ?? normalized; return { blockId, kind: def.kind, origin: "official", text: { raw, normalized, normalizationVersion: ruleVersion, inline: def.inline }, evidence: { sourceId, pdfPage: def.page, printedPage: String(def.page - 4), region: pageRegion(def.page), extraction: { method: "pdf-text", tool: "pdfjs-dist", toolVersion: "4.10.38" }, transformations: transformations(raw, normalized), rawSha256: sha256(raw), normalizedSha256: sha256(normalized) } }; }
function parent(n: string): string | null { const p = n.split("."); return p.length === 1 ? null : p.slice(0, -1).join("."); }
function ancestors(n: string): string[] { const p = n.split("."); return Array.from({ length: p.length - 1 }, (_, i) => unitId(p.slice(0, i + 1).join("."))); }
function kind(n: string): string { const d = n.split(".").length; return d === 1 ? "chapter" : d === 2 ? "section" : d === 3 ? "paragraph" : "subparagraph"; }
function makeUnit(def: UnitDef): any { const blocks = def.blocks.map((b, i) => makeBlock(def.number, i, b)); const ids = { formulaIds: blocks.filter((b) => b.assetId?.includes(":formula:")).map((b) => b.assetId), tableIds: blocks.filter((b) => b.assetId?.includes(":table:")).map((b) => b.assetId), figureIds: blocks.filter((b) => b.assetId?.includes(":figure:")).map((b) => b.assetId) }; const issues: any[] = [{ issueId: `ntc2018-${def.number.replaceAll(".", "-")}-source-review`, type: "normalization-review", severity: "blocking", note: "Record trascritto dall’evidence ufficiale ma non ancora confrontato integralmente da un revisore umano con il render della fonte." }]; if (Object.values(ids).some((x) => x.length)) issues.push({ issueId: `ntc2018-${def.number.replaceAll(".", "-")}-assets`, type: "asset-review", severity: "blocking", note: "Formule, tabelle e figure sono collocate nel punto originario; resta obbligatorio il confronto umano puntuale con la fonte ufficiale." }); return { $schema: "urn:structural-codes:schema:canonical-unit:v2", schemaVersion: "2.0.0-alpha.2", recordType: "canonical-unit", id: unitId(def.number), workId, expressionId, kind: kind(def.number), numbering: { official: def.number, sortKey: def.number.split(".").map((x) => x.padStart(3, "0")).join(".") }, title: def.title, titleBlockId: `${unitId(def.number)}#block-heading`, hierarchy: { parentId: parent(def.number) ? unitId(parent(def.number) as string) : null, ancestorIds: ancestors(def.number), position: Number(def.number.split(".").at(-1)) }, validity: { from: "2018-03-22", to: null, status: "in-force", asOf: "2026-08-09" }, blocks, citations: [], relations: [], assets: ids, workflow: { status: "extracted", createdBy: { actorId: "codex:ntc5-step4", kind: "automated-agent", toolVersion: ruleVersion }, createdAt, reviews: [], openIssues: issues } }; }
const cell = (text: string, extra: Record<string, unknown> = {}) => ({ text, ...extra });
const tables: any[] = [
    { id: asset("table", "5.2.iv"), unitId: unitId("5.2.3.1.3"), officialNumber: "5.2.IV", pdfPage: 182, caption: "Tab. 5.2.IV - Valutazione dei carichi da traffico", columnCount: 7, headers: [[cell("Gruppi di carico"), cell("Carico verticale (1)"), cell("Treno scarico"), cell("Frenatura e avviamento"), cell("Centrifuga"), cell("Serpeggio"), cell("Commenti")]], rows: [[cell("Gruppo 1 (2)"), cell("1,0"), cell("-"), cell("0,5 (0,0)"), cell("1,0 (0,0)"), cell("1,0 (0,0)"), cell("massima azione verticale e laterale")], [cell("Gruppo 2 (2)"), cell("-"), cell("1,0"), cell("0,0"), cell("1,0 (0,0)"), cell("1,0 (0,0)"), cell("stabilità laterale")], [cell("Gruppo 3 (2)"), cell("1,0 (0,5)"), cell("-"), cell("1,0"), cell("0,5 (0,0)"), cell("0,5 (0,0)"), cell("massima azione longitudinale")], [cell("Gruppo 4"), cell("0,8 (0,6;0,4)"), cell("-"), cell("0,8 (0,6;0,4)"), cell("0,8 (0,6;0,4)"), cell("0,8 (0,6;0,4)"), cell("Fessurazione")]], notes: ["(1) Includendo tutti i valori (F; α; etc..)", "(2) La simultaneità di due o tre valori caratteristici interi (assunzione di diversi coefficienti pari ad 1,0), sebbene improbabile, è stata considerata come semplificazione per i gruppi di carico 1, 2 e 3 senza che ciò abbia significative conseguenze progettuali.", "I valori campiti in grigio rappresentano l’azione dominante."] },
    { id: asset("table", "5.2.v"), unitId: unitId("5.2.3.2.1"), officialNumber: "5.2.V", pdfPage: 182, caption: "Tab. 5.2.V - Coefficienti parziali di sicurezza per le combinazioni di carico agli SLU", columnCount: 6, headers: [[cell("Azione"), cell("Condizione"), cell("Coefficiente"), cell("EQU(1)"), cell("A1"), cell("A2")]], rows: [[cell("Azioni permanenti"), cell("favorevoli"), cell("γG1"), cell("0,90"), cell("1,00"), cell("1,00")], [cell("Azioni permanenti"), cell("sfavorevoli"), cell("γG1"), cell("1,10"), cell("1,35"), cell("1,00")], [cell("Azioni permanenti non strutturali (2)"), cell("favorevoli"), cell("γG2"), cell("0,00"), cell("0,00"), cell("0,00")], [cell("Azioni permanenti non strutturali (2)"), cell("sfavorevoli"), cell("γG2"), cell("1,50"), cell("1,50"), cell("1,30")], [cell("Ballast (3)"), cell("favorevoli"), cell("γB"), cell("0,90"), cell("1,00"), cell("1,00")], [cell("Ballast (3)"), cell("sfavorevoli"), cell("γB"), cell("1,50"), cell("1,50"), cell("1,30")], [cell("Azioni variabili da traffico (4)"), cell("favorevoli"), cell("γQ"), cell("0,00"), cell("0,00"), cell("0,00")], [cell("Azioni variabili da traffico (4)"), cell("sfavorevoli"), cell("γQ"), cell("1,45"), cell("1,45"), cell("1,25")], [cell("Azioni variabili"), cell("favorevoli"), cell("γQi"), cell("0,00"), cell("0,00"), cell("0,00")], [cell("Azioni variabili"), cell("sfavorevoli"), cell("γQi"), cell("1,50"), cell("1,50"), cell("1,30")], [cell("Precompressione"), cell("favorevole"), cell("γP"), cell("0,90"), cell("1,00"), cell("1,00")], [cell("Precompressione"), cell("sfavorevole"), cell("γP"), cell("1,00 (5)"), cell("1,00 (6)"), cell("1,00")], [cell("Ritiro, viscosità e cedimenti non imposti appositamente"), cell("favorevole"), cell("γCed"), cell("0,00"), cell("0,00"), cell("0,00")], [cell("Ritiro, viscosità e cedimenti non imposti appositamente"), cell("sfavorevole"), cell("γCed"), cell("1,20"), cell("1,20"), cell("1,00")]], notes: ["(1) Equilibrio che non coinvolga i parametri di deformabilità e resistenza del terreno; altrimenti si applicano i valori della colonna A2.", "(2) Nel caso in cui l’intensità dei carichi permanenti non strutturali sia ben definita in fase di progetto, si potranno adottare gli stessi coefficienti validi per le azioni permanenti.", "(3) Quando si prevedano variazioni significative del carico dovuto al ballast, se ne dovrà tener conto esplicitamente nelle verifiche.", "(4) Le componenti delle azioni da traffico sono introdotte in combinazione considerando uno dei gruppi di carico gr della Tab. 5.2.IV.", "(5) 1,30 per instabilità in strutture con precompressione esterna", "(6) 1,20 per effetti locali"] },
    { id: asset("table", "5.2.vi"), unitId: unitId("5.2.3.2.1"), officialNumber: "5.2.VI", pdfPage: 183, caption: "Tab. 5.2.VI - Coefficienti di combinazione Ψ delle azioni", columnCount: 4, headers: [[cell("Azioni"), cell("Ψ0"), cell("Ψ1"), cell("Ψ2")]], rows: [[cell("Azioni singole da traffico - Carico sul rilevato a tergo delle spalle"), cell("0,80"), cell("0,50"), cell("0,0")], [cell("Azioni singole da traffico - Azioni aerodinamiche generate dal transito dei convogli"), cell("0,80"), cell("0,50"), cell("0,0")], [cell("Gruppo di carico gr1"), cell("0,80 (2)"), cell("0,80 (1)"), cell("0,0")], [cell("Gruppo di carico gr2"), cell("0,80 (2)"), cell("0,80 (1)"), cell("-")], [cell("Gruppo di carico gr3"), cell("0,80 (2)"), cell("0,80 (1)"), cell("0,0")], [cell("Gruppo di carico gr4"), cell("1,00"), cell("1,00 (1)"), cell("0,0")], [cell("Azioni del vento FWk"), cell("0,60"), cell("0,50"), cell("0,0")], [cell("Azioni da neve in fase di esecuzione"), cell("0,80"), cell("0,0"), cell("0,0")], [cell("Azioni da neve SLU e SLE"), cell("0,0"), cell("0,0"), cell("0,0")], [cell("Azioni termiche Tk"), cell("0,60"), cell("0,60"), cell("0,50")]], notes: ["(1) 0,80 se è carico solo un binario, 0,60 se sono carichi due binari e 0,40 se sono carichi tre o più binari.", "(2) Quando come azione di base venga assunta quella del vento, i coefficienti Ψ0 relativi ai gruppi di carico delle azioni da traffico vanno assunti pari a 0,0."] },
    { id: asset("table", "5.2.vii"), unitId: unitId("5.2.3.2.2"), officialNumber: "5.2.VII", pdfPage: 183, caption: "Tab. 5.2.VII - Ulteriori coefficienti di combinazione Ψ delle azioni", columnCount: 4, headers: [[cell("Azioni"), cell("Ψ0"), cell("Ψ1"), cell("Ψ2")]], rows: [[cell("Treno di carico LM 71"), cell("0,80 (3)"), cell("(1)"), cell("0,0")], [cell("Treno di carico SW/0"), cell("0,80 (3)"), cell("0,80"), cell("0,0")], [cell("Treno di carico SW/2"), cell("0,00 (3)"), cell("0,80"), cell("0,0")], [cell("Treno scarico"), cell("1,00 (3)"), cell("-"), cell("-")], [cell("Centrifuga"), cell("(2) (3)"), cell("(2)"), cell("(2)")], [cell("Azione laterale (serpeggio)"), cell("1,00 (3)"), cell("0,80"), cell("0,0")]], notes: ["(1) 0,80 se è carico solo un binario, 0,60 se sono carichi due binari e 0,40 se sono carichi tre o più binari.", "(2) Si usano gli stessi coefficienti Ψ adottati per i carichi che provocano dette azioni.", "(3) Quando come azione di base venga assunta quella del vento, i coefficienti Ψ0 relativi ai gruppi di carico delle azioni da traffico vanno assunti pari a 0,0."] },
    { id: asset("table", "5.2.viii"), unitId: unitId("5.2.3.2.2.1"), officialNumber: "5.2.VIII", pdfPage: 184, caption: "Tab. 5.2.VIII - Massima variazione angolare e minimo raggio di curvatura", columnCount: 4, headers: [[cell("Velocità [km/h]"), cell("Variazione angolare massima"), cell("Raggio minimo di curvatura - Singola campata"), cell("Raggio minimo di curvatura - Più campate")]], rows: [[cell("V ≤ 120"), cell("0,0035 rd"), cell("1700 m"), cell("3500 m")], [cell("120 < V ≤ 200"), cell("0,0020 rd"), cell("6000 m"), cell("9500 m")], [cell("200 < V"), cell("0,0015 rd"), cell("14000 m"), cell("17500 m")]], notes: [] },
];
const figures = [{ id: asset("figure", "5.2.14"), unitId: unitId("5.2.3.2.2.1"), officialNumber: "5.2.14", pdfPage: 184, caption: "Fig. 5.2.14 - Sghembo ammissibile", alt: "Schema dello sghembo ammissibile", imagePath: "figures/ntc2018/fig5.2.14.png", region: { coordinateSystem: "pdf-points-top-left", x: 175, y: 245, width: 245, height: 95 }, sha256: "" }];
const formulas = [{ id: asset("formula", "5.2.11"), unitId: unitId("5.2.3.2.2.1"), officialNumber: "5.2.11", pdfPage: 184, latex: "R=\\frac{L^2}{8\\,\\delta_h}" }];
const assetManifest: any = { $schema: "urn:structural-codes:schema:asset-manifest:v2", schemaVersion: "2.0.0-alpha.1", recordType: "asset-manifest", document: "ntc2018", section: "5.1-step4", sourceId, status: "transcribed-unreviewed", formulas, tables, figures };
const pageOutput = join(root, "evidence", sourceId, "pages");
const unitOutput = join(root, "corpus", "units", "ntc2018"); const assetOutput = join(root, "corpus", "assets", "ntc2018", "5.1-step4.json");
await mkdir(unitOutput, { recursive: true });
for (const figure of figures) figure.sha256 = sha256(await readFile(join(root, "corpus", "assets", figure.imagePath)));
for (const def of units) await writeFile(join(unitOutput, `${def.number}.json`), `${JSON.stringify(makeUnit(def), null, 2)}\n`, "utf8");
await writeFile(assetOutput, `${JSON.stringify(assetManifest, null, 2)}\n`, "utf8");
void pageOutput;
console.log(`NTC5 step4: ${units.length} unità e manifest asset scritto.`);
