import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { sha256OfText } from "../src/lib/hash.ts";
const root = fileURLToPath(new URL("../", import.meta.url));
const unitDir = join(root, "corpus", "units", "ntc2018");
const assetDir = join(root, "corpus", "assets", "ntc2018");
const sourceId = "gu-so8-2018-ntc";
const workId = "it-mit:dm:2018-01-17:ntc2018";
const expressionId = "it-mit:dm:2018-01-17:ntc2018:original-it";
const profile = "ntc42-editorial-profile-0.1.0";
const createdAt = "2026-08-09T00:00:00Z";
type Region = { coordinateSystem: "pdf-points-top-left"; x: number; y: number; width: number; height: number };
type Opt = { page: number; printedPage: string; wrap?: boolean; discretionaryHyphen?: boolean; manual?: boolean };
type Inline = { kind: "text" | "math"; value: string; latex?: string };
const uid = (n: string) => "urn:structural-codes:it:unit:ntc2018:" + n;
const fid = (n: string) => "urn:structural-codes:it:asset:formula:ntc2018:" + n;
const tid = (n: string) => "urn:structural-codes:it:asset:table:ntc2018:" + n;
const gid = (n: string) => "urn:structural-codes:it:asset:figure:ntc2018:" + n;
const reg = (x: number, y: number, width: number, height: number): Region => ({ coordinateSystem: "pdf-points-top-left", x, y, width, height });
const p = (page: number, printedPage: string, options: Omit<Opt, "page" | "printedPage"> = {}): Opt => ({ page, printedPage, ...options });
const t = (value: string): Inline => ({ kind: "text", value });
const m = (value: string, latex: string): Inline => ({ kind: "math", value, latex });
function trans(o: Opt) { const a: Array<{ operation: string; ruleVersion: string; note: string }> = []; if (o.wrap) a.push({ operation: "join-line-wrap", ruleVersion: profile, note: "Unite le righe del capoverso e normalizza gli spazi." }, { operation: "normalize-whitespace", ruleVersion: profile, note: "Uniformati gli spazi dopo la ricomposizione." }); if (o.discretionaryHyphen) a.push({ operation: "remove-discretionary-hyphen", ruleVersion: profile, note: "Ricomposte le parole spezzate dal trattino tipografico." }); if (o.manual) a.push({ operation: "manual-correction", ruleVersion: profile, note: "Ripristinati accenti, simboli e matematica confrontati con il render ufficiale." }); if (o.wrap || o.manual) a.push({ operation: "unicode-nfc", ruleVersion: profile, note: "Testo normalizzato in Unicode NFC." }); return a; }
function ev(o: Opt, r: Region, raw: string, normalized: string) { return { sourceId, pdfPage: o.page, printedPage: o.printedPage, region: r, extraction: { method: "pdf-text", tool: "pdfjs-dist", toolVersion: "4.10.38" }, transformations: trans(o), rawSha256: sha256OfText(raw), normalizedSha256: sha256OfText(normalized) }; }
function block(n: string, s: string, kind: "heading" | "paragraph", o: Opt, r: Region, raw: string, normalized: string, inline: Inline[] = [t(normalized)]) { return { blockId: uid(n) + "#block-" + s, kind, origin: "official", text: { raw, normalized, normalizationVersion: profile, inline }, evidence: ev(o, r, raw, normalized) }; }
function formula(n: string, num: string, o: Opt, r: Region) { return { blockId: uid(n) + "#block-formula-" + num.replaceAll(".", "-"), kind: "formula-ref", origin: "official", assetId: fid(num), evidence: { ...ev({ ...o, manual: true }, r, "[" + num + "]", "[" + num + "]"), extraction: { method: "manual-transcription", tool: "codex-source-transcription", toolVersion: profile } } }; }
function assetBlock(n: string, s: string, kind: "table-ref" | "figure-ref", asset: string, o: Opt, r: Region) { const note = kind === "table-ref" ? "Tabella strutturata dal render ufficiale; revisione umana cella per cella ancora obbligatoria." : "Crop raster ufficiale verificato sul render; revisione umana del posizionamento ancora obbligatoria."; return { blockId: uid(n) + "#block-" + s, kind, origin: "official", assetId: asset, evidence: { ...ev({ ...o, manual: true }, r, note, note), extraction: { method: "manual-transcription", tool: "codex-source-transcription", toolVersion: profile } } }; }
function parent(n: string) { const a = n.split("."); return a.length === 1 ? null : uid(a.slice(0, -1).join(".")); }
function ancestors(n: string) { const a = n.split("."); return a.slice(1).map((_, i) => uid(a.slice(0, i + 1).join("."))); }
function unit(n: string, title: string, blocks: unknown[], formulas: string[] = [], tables: string[] = [], figures: string[] = []) { return { $schema: "urn:structural-codes:schema:canonical-unit:v2", schemaVersion: "2.0.0-alpha.2", recordType: "canonical-unit", id: uid(n), workId, expressionId, kind: "subparagraph", numbering: { official: n, sortKey: n.split(".").map((x) => x.padStart(3, "0")).join(".") }, title, titleBlockId: uid(n) + "#block-heading", hierarchy: { parentId: parent(n), ancestorIds: ancestors(n), position: Number(n.split(".").at(-1)) }, validity: { from: "2018-03-22", to: null, status: "in-force", asOf: "2026-08-09" }, blocks, citations: [], relations: [], assets: { formulaIds: formulas.map(fid), tableIds: tables.map(tid), figureIds: figures.map(gid) }, workflow: { status: "extracted", createdBy: { actorId: "codex:ntc42-step4d", kind: "automated-agent", toolVersion: profile }, createdAt, reviews: [], openIssues: [{ issueId: "ntc2018-" + n.replaceAll(".", "-") + "-source-review", type: "normalization-review", severity: "blocking", note: "Record trascritto dall’evidence ufficiale ma non ancora confrontato integralmente da un revisore umano con il render della fonte." }, ...tables.map(() => ({ issueId: "ntc2018-" + n.replaceAll(".", "-") + "-assets", type: "asset-review", severity: "blocking", note: "La tabella è strutturata e richiede verifica umana cella per cella." })), ...figures.map(() => ({ issueId: "ntc2018-" + n.replaceAll(".", "-") + "-figures", type: "asset-review", severity: "blocking", note: "Il crop ufficiale è registrato; resta la revisione umana del posizionamento e della didascalia." }))] } }; }

const tXII = tid("4.2.xii");
const tXIII = tid("4.2.xiii");
const tableXII = { id: tXII, unitId: uid("4.2.4.2.1"), officialNumber: "4.2.XII", pdfPage: 111, caption: "Limiti di deformabilità per gli elementi di impalcato delle costruzioni ordinarie", columnCount: 3, headers: [[{ text: "Elementi strutturali" }, { text: "δmax/L", latex: "\\delta_{max}/L" }, { text: "δ2/L", latex: "\\delta_2/L" }]], rows: [[{ text: "Coperture in generale" }, { text: "1/200", latex: "\\frac{1}{200}" }, { text: "1/250", latex: "\\frac{1}{250}" }], [{ text: "Coperture praticabili" }, { text: "1/250", latex: "\\frac{1}{250}" }, { text: "1/300", latex: "\\frac{1}{300}" }], [{ text: "Solai in generale" }, { text: "1/250", latex: "\\frac{1}{250}" }, { text: "1/300", latex: "\\frac{1}{300}" }], [{ text: "Solai o coperture che reggono intonaco o altro materiale di finitura fragile o tramezzi non flessibili" }, { text: "1/250", latex: "\\frac{1}{250}" }, { text: "1/350", latex: "\\frac{1}{350}" }], [{ text: "Solai che supportano colonne" }, { text: "1/400", latex: "\\frac{1}{400}" }, { text: "1/500", latex: "\\frac{1}{500}" }], [{ text: "Nei casi in cui lo spostamento può compromettere l’aspetto dell’edificio" }, { text: "1/250", latex: "\\frac{1}{250}" }, { text: "" }]], notes: ["In caso di specifiche esigenze tecniche e/o funzionali tali limiti devono essere opportunamente ridotti."] };
const tableXIII = { id: tXIII, unitId: uid("4.2.4.2.2"), officialNumber: "4.2.XIII", pdfPage: 111, caption: "Limiti di deformabilità per costruzioni ordinarie soggette ad azioni orizzontali", columnCount: 3, headers: [[{ text: "Tipologia dell’edificio" }, { text: "δ/h", latex: "\\delta/h" }, { text: "Δ/H", latex: "\\Delta/H" }]], rows: [[{ text: "Edifici industriali monopiano senza carroponte" }, { text: "1/150", latex: "\\frac{1}{150}" }, { text: "/" }], [{ text: "Altri edifici monopiano" }, { text: "1/300", latex: "\\frac{1}{300}" }, { text: "/" }], [{ text: "Edifici multipiano" }, { text: "1/300", latex: "\\frac{1}{300}" }, { text: "1/500", latex: "\\frac{1}{500}" }]], notes: ["In caso di specifiche esigenze tecniche e/o funzionali tali limiti devono essere opportunamente ridotti."] };
const figure23 = { id: gid("4.2.3"), unitId: uid("4.2.4.2.1"), officialNumber: "4.2.3", pdfPage: 110, caption: "Fig. 4.2.3 - Definizione degli spostamenti verticali per le verifiche in esercizio", alt: "Definizione degli spostamenti verticali: monta iniziale, spostamenti δ1 e δ2, spostamento totale e luce L.", imagePath: "figures/ntc2018/fig4.2.3.png", region: reg(75, 450, 440, 70), sha256: "ce801e5da49414dccea38fccb24c8b0e201713ba0e08a22f9f2441ae35133e50" };
const figure24 = { id: gid("4.2.4"), unitId: uid("4.2.4.2.2"), officialNumber: "4.2.4", pdfPage: 111, caption: "Fig. 4.2.4 - Definizione degli spostamenti orizzontali per le verifiche in esercizio", alt: "Definizione degli spostamenti orizzontali di sommità e di piano, con le altezze H e h.", imagePath: "figures/ntc2018/fig4.2.4.png", region: reg(75, 420, 440, 95), sha256: "19818cd8d7daa70248d700d929acc85d74e63aca8bcb7c01ad95b9a468eb966e" };
const units = [
    unit("4.2.4.2.2", "Spostamenti laterali", [
        block("4.2.4.2.2", "heading", "heading", p(110, "106", { manual: true }), reg(82.954, 820, 180, 7.476), "4.2.4.2.2 Spostamenti laterali", "4.2.4.2.2 Spostamenti laterali"),
        block("4.2.4.2.2", "p1", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 833, 428.6, 17.6), "Negli edifici gli spostamenti laterali alla sommità delle colonne per le combinazioni caratteristiche delle azioni devono generalmente limitarsi ad una frazione dell’altezza della colonna e dell’altezza complessiva dell’edificio da valutarsi in funzione degli effetti sugli elementi portati, della qualità del comfort richiesto alla costruzione, delle eventuali implicazioni di una eccessiva deformabilità sul valore dei carichi agenti.", "Negli edifici gli spostamenti laterali alla sommità delle colonne per le combinazioni caratteristiche delle azioni devono generalmente limitarsi ad una frazione dell’altezza della colonna e dell’altezza complessiva dell’edificio da valutarsi in funzione degli effetti sugli elementi portati, della qualità del comfort richiesto alla costruzione, delle eventuali implicazioni di una eccessiva deformabilità sul valore dei carichi agenti."),
        block("4.2.4.2.2", "p2", "paragraph", p(111, "107", { wrap: true }), reg(82.954, 98.93, 428.6, 17.6), "In assenza di più precise indicazioni si possono adottare i limiti per gli spostamenti orizzontali indicati in Tab. 4.2.XIII (Δ spostamento in sommità; δ spostamento relativo di piano – Fig. 4.2.4).", "In assenza di più precise indicazioni si possono adottare i limiti per gli spostamenti orizzontali indicati in Tab. 4.2.XIII (Δ spostamento in sommità; δ spostamento relativo di piano – Fig. 4.2.4).", [t("In assenza di più precise indicazioni si possono adottare i limiti per gli spostamenti orizzontali indicati in Tab. 4.2.XIII ("), m("Δ", "\\Delta"), t(" spostamento in sommità; "), m("δ", "\\delta"), t(" spostamento relativo di piano – Fig. 4.2.4).")]),
        assetBlock("4.2.4.2.2", "table-xiii", "table-ref", tXIII, p(111, "107"), reg(82.954, 306.6, 430, 109)),
        assetBlock("4.2.4.2.2", "figure-4-2-4", "figure-ref", gid("4.2.4"), p(111, "107"), reg(75, 420, 440, 95)),
    ], [], ["4.2.xiii"], ["4.2.4"]),
    unit("4.2.4.2.1", "Spostamenti verticali", [
        block("4.2.4.2.1", "heading", "heading", p(110, "106", { manual: true }), reg(82.954, 570, 180, 7.476), "4.2.4.2.1 Spostamenti verticali", "4.2.4.2.1 Spostamenti verticali"),
        block("4.2.4.2.1", "p1", "paragraph", p(110, "106"), reg(82.954, 583, 428.6, 7.482), "Il valore totale dello spostamento ortogonale all’asse dell’elemento (Fig. 4.2.3) è definito come", "Il valore totale dello spostamento ortogonale all’asse dell’elemento (Fig. 4.2.3) è definito come"),
        formula("4.2.4.2.1", "4.2.60", p(110, "106"), reg(180, 597, 220, 25)),
        assetBlock("4.2.4.2.1", "figure-4-2-3", "figure-ref", gid("4.2.3"), p(110, "106"), reg(75, 450, 440, 70)),
        block("4.2.4.2.1", "p2", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 650, 428.6, 37.6), "essendo: δC la monta iniziale della trave, δ1 lo spostamento elastico dovuto ai carichi permanenti, δ2 lo spostamento elastico dovuto ai carichi variabili, δmax lo spostamento nello stato finale, depurato della monta iniziale = δtot − δC.", "essendo: δC la monta iniziale della trave, δ1 lo spostamento elastico dovuto ai carichi permanenti, δ2 lo spostamento elastico dovuto ai carichi variabili, δmax lo spostamento nello stato finale, depurato della monta iniziale = δtot − δC.", [t("essendo: "), m("δC", "\\delta_C"), t(" la monta iniziale della trave, "), m("δ1", "\\delta_1"), t(" lo spostamento elastico dovuto ai carichi permanenti, "), m("δ2", "\\delta_2"), t(" lo spostamento elastico dovuto ai carichi variabili, "), m("δmax", "\\delta_{max}"), t(" lo spostamento nello stato finale, depurato della monta iniziale = "), m("δtot − δC", "\\delta_{tot}-\\delta_C"), t(".")]),
        block("4.2.4.2.1", "p3", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 695, 428.6, 27.6), "Nel caso di coperture, solai e travi di edifici ordinari, i valori limite di δmax e δ2, riferiti alle combinazioni caratteristiche delle azioni, sono espressi come funzione della luce L dell’elemento.", "Nel caso di coperture, solai e travi di edifici ordinari, i valori limite di δmax e δ2, riferiti alle combinazioni caratteristiche delle azioni, sono espressi come funzione della luce L dell’elemento.", [t("Nel caso di coperture, solai e travi di edifici ordinari, i valori limite di "), m("δmax", "\\delta_{max}"), t(" e "), m("δ2", "\\delta_2"), t(", riferiti alle combinazioni caratteristiche delle azioni, sono espressi come funzione della luce "), m("L", "L"), t(" dell’elemento.")]),
        block("4.2.4.2.1", "p4", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 730, 428.6, 37.6), "I valori di tali limiti sono da definirsi in funzione degli effetti sugli elementi portati, della qualità del comfort richiesto alla costruzione, delle caratteristiche degli elementi strutturali e non strutturali gravanti sull’elemento considerato, delle eventuali implicazioni di una eccessiva deformabilità sul valore dei carichi agenti.", "I valori di tali limiti sono da definirsi in funzione degli effetti sugli elementi portati, della qualità del comfort richiesto alla costruzione, delle caratteristiche degli elementi strutturali e non strutturali gravanti sull’elemento considerato, delle eventuali implicazioni di una eccessiva deformabilità sul valore dei carichi agenti."),
        block("4.2.4.2.1", "p5", "paragraph", p(110, "106", { wrap: true }), reg(82.954, 775, 428.6, 27.6), "In carenza di più precise indicazioni si possono adottare i limiti indicati nella Tab. 4.2.XII, dove L è la luce dell’elemento o, nel caso di mensole, il doppio dello sbalzo.", "In carenza di più precise indicazioni si possono adottare i limiti indicati nella Tab. 4.2.XII, dove L è la luce dell’elemento o, nel caso di mensole, il doppio dello sbalzo.", [t("In carenza di più precise indicazioni si possono adottare i limiti indicati nella Tab. 4.2.XII, dove "), m("L", "L"), t(" è la luce dell’elemento o, nel caso di mensole, il doppio dello sbalzo.")]),
        assetBlock("4.2.4.2.1", "table-xii", "table-ref", tXII, p(111, "107"), reg(82.954, 126, 430, 155)),
    ], ["4.2.60"], ["4.2.xii"], ["4.2.3"]),
    unit("4.2.4.2.3", "Stato limite di vibrazioni", [
        block("4.2.4.2.3", "heading", "heading", p(111, "107", { manual: true }), reg(82.954, 535, 210, 7.476), "4.2.4.2.3 Stato limite di vibrazioni", "4.2.4.2.3 Stato limite di vibrazioni"),
        block("4.2.4.2.3", "p1", "paragraph", p(111, "107", { wrap: true }), reg(82.954, 548, 428.6, 17.6), "Le verifiche devono essere condotte adottando le combinazioni frequenti di progetto e facendo riferimento a normative per la misura e la valutazione degli effetti indotti dalle vibrazioni quali: la UNI 9614, la UNI 9916 ed altre norme di comprovata validità.", "Le verifiche devono essere condotte adottando le combinazioni frequenti di progetto e facendo riferimento a normative per la misura e la valutazione degli effetti indotti dalle vibrazioni quali: la UNI 9614, la UNI 9916 ed altre norme di comprovata validità."),
    ]),
    unit("4.2.4.2.3.1", "Edifici", [
        block("4.2.4.2.3.1", "heading", "heading", p(111, "107", { manual: true }), reg(82.954, 580, 80, 7.476), "4.2.4.2.3.1 Edifici", "4.2.4.2.3.1 Edifici"),
        block("4.2.4.2.3.1", "p1", "paragraph", p(111, "107", { wrap: true }), reg(82.954, 593, 428.6, 17.6), "Nel caso di solai caricati regolarmente da persone, la frequenza naturale più bassa della struttura del solaio non deve in generale essere minore di 3 Hz.", "Nel caso di solai caricati regolarmente da persone, la frequenza naturale più bassa della struttura del solaio non deve in generale essere minore di 3 Hz."),
        block("4.2.4.2.3.1", "p2", "paragraph", p(111, "107", { wrap: true }), reg(82.954, 620, 428.6, 17.6), "Nel caso di solai soggetti a eccitazioni cicliche la frequenza naturale più bassa non deve in generale essere inferiore a 5 Hz.", "Nel caso di solai soggetti a eccitazioni cicliche la frequenza naturale più bassa non deve in generale essere inferiore a 5 Hz."),
        block("4.2.4.2.3.1", "p3", "paragraph", p(111, "107", { wrap: true }), reg(82.954, 647, 428.6, 17.6), "In alternativa a tali limitazioni potrà condursi un controllo di accettabilità della percezione delle vibrazioni.", "In alternativa a tali limitazioni potrà condursi un controllo di accettabilità della percezione delle vibrazioni."),
    ]),
    unit("4.2.4.2.3.2", "Strutture di elevata flessibilità e soggette a carichi ciclici", [
        block("4.2.4.2.3.2", "heading", "heading", p(111, "107", { manual: true }), reg(82.954, 675, 330, 7.476), "4.2.4.2.3.2 Strutture di elevata flessibilità e soggette a carichi ciclici", "4.2.4.2.3.2 Strutture di elevata flessibilità e soggette a carichi ciclici"),
        block("4.2.4.2.3.2", "p1", "paragraph", p(111, "107", { wrap: true }), reg(82.954, 688, 428.6, 17.6), "I controlli di accettabilità della percezione devono essere condotti seguendo metodologie e limitazioni suggerite da normative di comprovata validità.", "I controlli di accettabilità della percezione devono essere condotti seguendo metodologie e limitazioni suggerite da normative di comprovata validità."),
    ]),
    unit("4.2.4.2.3.3", "Oscillazioni prodotte dal vento", [
        block("4.2.4.2.3.3", "heading", "heading", p(111, "107", { manual: true }), reg(82.954, 720, 220, 7.476), "4.2.4.2.3.3 Oscillazioni prodotte dal vento", "4.2.4.2.3.3 Oscillazioni prodotte dal vento"),
        block("4.2.4.2.3.3", "p1", "paragraph", p(111, "107", { wrap: true, discretionaryHyphen: true }), reg(82.954, 733, 428.6, 27.6), "Le strutture di elevata flessibilità, quali edifici alti e snelli, coperture molto ampie, ecc., devono essere verificate per gli effetti indotti dall’azione dinamica del vento sia per le vibrazioni parallele che per quelle perpendicolari all’azione del vento.", "Le strutture di elevata flessibilità, quali edifici alti e snelli, coperture molto ampie, ecc., devono essere verificate per gli effetti indotti dall’azione dinamica del vento sia per le vibrazioni parallele che per quelle perpendicolari all’azione del vento."),
        block("4.2.4.2.3.3", "p2", "paragraph", p(111, "107", { wrap: true }), reg(82.954, 768, 428.6, 27.6), "Le verifiche devono condursi per le vibrazioni indotte dalle raffiche e per quelle indotte dai vortici, utilizzando dati suffragati da opportuna documentazione, o tramite metodi analitici, numerici e/o sperimentali adeguatamente comprovati.", "Le verifiche devono condursi per le vibrazioni indotte dalle raffiche e per quelle indotte dai vortici, utilizzando dati suffragati da opportuna documentazione, o tramite metodi analitici, numerici e/o sperimentali adeguatamente comprovati."),
    ]),
    unit("4.2.4.2.4", "Stato limite di plasticizzazioni locali", [
        block("4.2.4.2.4", "heading", "heading", p(112, "108", { manual: true }), reg(82.954, 98, 250, 7.476), "4.2.4.2.4 Stato limite di plasticizzazioni locali", "4.2.4.2.4 Stato limite di plasticizzazioni locali"),
        block("4.2.4.2.4", "p1", "paragraph", p(112, "108", { wrap: true, discretionaryHyphen: true }), reg(82.954, 111, 428.6, 37.6), "Nelle strutture in acciaio è normale che la presenza di tensioni residue (dovute a processi di fabbricazione, tolleranze, particolarità di alcuni dettagli, variazioni localizzate della temperatura) produca concentrazioni di tensioni e conseguenti plasticizzazioni localizzate. Queste non influenzano la sicurezza dell’opera nei confronti degli stati limite ultimi. Inoltre i criteri di cui al § 4.2.4.1.3 tengono conto dell’influenza di questi parametri nei riguardi dell’instabilità delle membrature.", "Nelle strutture in acciaio è normale che la presenza di tensioni residue (dovute a processi di fabbricazione, tolleranze, particolarità di alcuni dettagli, variazioni localizzate della temperatura) produca concentrazioni di tensioni e conseguenti plasticizzazioni localizzate. Queste non influenzano la sicurezza dell’opera nei confronti degli stati limite ultimi. Inoltre i criteri di cui al § 4.2.4.1.3 tengono conto dell’influenza di questi parametri nei riguardi dell’instabilità delle membrature."),
        block("4.2.4.2.4", "p2", "paragraph", p(112, "108"), reg(82.954, 158, 428.6, 17.6), "In presenza di fenomeni di fatica a basso numero di cicli ci si deve cautelare mediante specifiche verifiche.", "In presenza di fenomeni di fatica a basso numero di cicli ci si deve cautelare mediante specifiche verifiche."),
    ]),
    unit("4.2.5", "VERIFICHE PER SITUAZIONI PROGETTUALI TRANSITORIE", [
        block("4.2.5", "heading", "heading", p(112, "108", { manual: true }), reg(82.954, 190, 320, 7.476), "4.2.5. VERIFICHE PER SITUAZIONI PROGETTUALI TRANSITORIE", "4.2.5 VERIFICHE PER SITUAZIONI PROGETTUALI TRANSITORIE"),
        block("4.2.5", "p1", "paragraph", p(112, "108", { wrap: true }), reg(82.954, 203, 428.6, 37.6), "Per le situazioni costruttive transitorie, come quelle che si hanno durante le fasi della costruzione, dovranno adottarsi tecnologie costruttive e programmi di lavoro che non possano provocare danni permanenti alla struttura o agli elementi strutturali e che comunque non possano riverberarsi sulla sicurezza dell’opera.", "Per le situazioni costruttive transitorie, come quelle che si hanno durante le fasi della costruzione, dovranno adottarsi tecnologie costruttive e programmi di lavoro che non possano provocare danni permanenti alla struttura o agli elementi strutturali e che comunque non possano riverberarsi sulla sicurezza dell’opera."),
        block("4.2.5", "p2", "paragraph", p(112, "108", { wrap: true }), reg(82.954, 248, 428.6, 27.6), "Le entità delle azioni ambientali da prendere in conto saranno determinate in relazione alla durata nel tempo della situazione transitoria e della tecnologia esecutiva.", "Le entità delle azioni ambientali da prendere in conto saranno determinate in relazione alla durata nel tempo della situazione transitoria e della tecnologia esecutiva."),
    ]),
    unit("4.2.6", "VERIFICHE PER SITUAZIONI PROGETTUALI ECCEZIONALI", [
        block("4.2.6", "heading", "heading", p(112, "108", { manual: true }), reg(82.954, 292, 300, 7.476), "4.2.6. VERIFICHE PER SITUAZIONI PROGETTUALI ECCEZIONALI", "4.2.6 VERIFICHE PER SITUAZIONI PROGETTUALI ECCEZIONALI"),
        block("4.2.6", "p1", "paragraph", p(112, "108", { wrap: true }), reg(82.954, 305, 428.6, 27.6), "Per situazioni progettuali eccezionali, il progetto dovrà dimostrare la robustezza della costruzione mediante procedure di scenari di danno per i quali i fattori parziali γM dei materiali possono essere assunti pari all’unità.", "Per situazioni progettuali eccezionali, il progetto dovrà dimostrare la robustezza della costruzione mediante procedure di scenari di danno per i quali i fattori parziali γM dei materiali possono essere assunti pari all’unità.", [t("Per situazioni progettuali eccezionali, il progetto dovrà dimostrare la robustezza della costruzione mediante procedure di scenari di danno per i quali i fattori parziali "), m("γM", "\\gamma_M"), t(" dei materiali possono essere assunti pari all’unità.")]),
    ]),
    unit("4.2.7", "PROGETTAZIONE INTEGRATA DA PROVE E VERIFICA MEDIANTE PROVE", [
        block("4.2.7", "heading", "heading", p(112, "108", { manual: true }), reg(82.954, 350, 350, 7.476), "4.2.7. PROGETTAZIONE INTEGRATA DA PROVE E VERIFICA MEDIANTE PROVE", "4.2.7 PROGETTAZIONE INTEGRATA DA PROVE E VERIFICA MEDIANTE PROVE"),
        block("4.2.7", "p1", "paragraph", p(112, "108", { wrap: true }), reg(82.954, 363, 428.6, 17.6), "La resistenza e la funzionalità di strutture ed elementi strutturali può essere misurata attraverso prove su campioni di adeguata numerosità.", "La resistenza e la funzionalità di strutture ed elementi strutturali può essere misurata attraverso prove su campioni di adeguata numerosità."),
        block("4.2.7", "p2", "paragraph", p(112, "108", { wrap: true }), reg(82.954, 388, 428.6, 37.6), "I risultati delle prove eseguite su opportuni campioni devono essere trattati con i metodi dell’analisi statistica, in modo tale da ricavare parametri significativi quali media, deviazione standard e fattore di asimmetria della distribuzione, sì da caratterizzare adeguatamente un modello probabilistico descrittore delle quantità indagate (variabili aleatorie).", "I risultati delle prove eseguite su opportuni campioni devono essere trattati con i metodi dell’analisi statistica, in modo tale da ricavare parametri significativi quali media, deviazione standard e fattore di asimmetria della distribuzione, sì da caratterizzare adeguatamente un modello probabilistico descrittore delle quantità indagate (variabili aleatorie)."),
        block("4.2.7", "p3", "paragraph", p(112, "108", { wrap: true }), reg(82.954, 433, 428.6, 27.6), "Indicazioni più dettagliate al riguardo e metodi operativi completi per la progettazione integrata da prove possono essere reperiti nella Appendice D della UNI EN 1990:2006.", "Indicazioni più dettagliate al riguardo e metodi operativi completi per la progettazione integrata da prove possono essere reperiti nella Appendice D della UNI EN 1990:2006."),
    ]),
    unit("4.2.8", "UNIONI", [
        block("4.2.8", "heading", "heading", p(112, "108", { manual: true }), reg(82.954, 480, 120, 7.476), "4.2.8. UNIONI", "4.2.8 UNIONI"),
        block("4.2.8", "p1", "paragraph", p(112, "108", { wrap: true }), reg(82.954, 493, 428.6, 37.6), "Nel presente paragrafo sono considerati sistemi di unione elementari, in quanto parti costituenti i collegamenti strutturali tra le membrature in acciaio. In particolare, sono presentati metodi per calcolare le prestazioni resistenti e le relative modalità e regole per la realizzazione dei vari tipi di unione esaminati. Le tipologie di unione analizzate sono quelle realizzate tramite bulloni, chiodi, perni e saldature.", "Nel presente paragrafo sono considerati sistemi di unione elementari, in quanto parti costituenti i collegamenti strutturali tra le membrature in acciaio. In particolare, sono presentati metodi per calcolare le prestazioni resistenti e le relative modalità e regole per la realizzazione dei vari tipi di unione esaminati. Le tipologie di unione analizzate sono quelle realizzate tramite bulloni, chiodi, perni e saldature."),
        block("4.2.8", "p2", "paragraph", p(112, "108", { wrap: true }), reg(82.954, 538, 428.6, 17.6), "Le sollecitazioni agenti nei collegamenti allo stato limite ultimo e allo stato limite di esercizio si devono valutare con i criteri indicati in § 4.2.2.", "Le sollecitazioni agenti nei collegamenti allo stato limite ultimo e allo stato limite di esercizio si devono valutare con i criteri indicati in § 4.2.2."),
        block("4.2.8", "p3", "paragraph", p(112, "108", { wrap: true }), reg(82.954, 563, 428.6, 27.6), "Le sollecitazioni così determinate possono essere distribuite, con criteri elastici oppure plastici, nei singoli elementi costituenti i collegamenti strutturali tra le membrature a condizione che:", "Le sollecitazioni così determinate possono essere distribuite, con criteri elastici oppure plastici, nei singoli elementi costituenti i collegamenti strutturali tra le membrature a condizione che:"),
        block("4.2.8", "l1", "paragraph", p(112, "108", { wrap: true }), reg(88, 598, 420, 27.6), "– le azioni così ripartite fra gli elementi di unione elementari (unioni) del collegamento siano in equilibrio con quelle applicate e soddisfino la condizione di resistenza imposta per ognuno di essi;", "– le azioni così ripartite fra gli elementi di unione elementari (unioni) del collegamento siano in equilibrio con quelle applicate e soddisfino la condizione di resistenza imposta per ognuno di essi;"),
        block("4.2.8", "l2", "paragraph", p(112, "108", { wrap: true, discretionaryHyphen: true }), reg(88, 632, 420, 17.6), "– le deformazioni derivanti da tale distribuzione delle sollecitazioni all’interno degli elementi di unione non superino la loro capacità di deformazione.", "– le deformazioni derivanti da tale distribuzione delle sollecitazioni all’interno degli elementi di unione non superino la loro capacità di deformazione."),
        block("4.2.8", "p4", "paragraph", p(112, "108", { wrap: true }), reg(82.954, 660, 428.6, 37.6), "Per il calcolo della resistenza a taglio delle viti e dei chiodi, per il rifollamento delle piastre collegate e per il precarico dei bulloni, si adottano i fattori parziali γM indicati in Tab. 4.2.XIV.", "Per il calcolo della resistenza a taglio delle viti e dei chiodi, per il rifollamento delle piastre collegate e per il precarico dei bulloni, si adottano i fattori parziali γM indicati in Tab. 4.2.XIV.", [t("Per il calcolo della resistenza a taglio delle viti e dei chiodi, per il rifollamento delle piastre collegate e per il precarico dei bulloni, si adottano i fattori parziali "), m("γM", "\\gamma_M"), t(" indicati in Tab. 4.2.XIV.")]),
        assetBlock("4.2.8", "table-xiv", "table-ref", "urn:structural-codes:it:asset:table:ntc2018:4.2.xiv", p(112, "108"), reg(82.954, 590, 330, 160)),
    ], [], ["4.2.xiv"]),
];
const manifest = { $schema: "urn:structural-codes:schema:asset-manifest:v2", schemaVersion: "2.0.0-alpha.1", recordType: "asset-manifest", document: "ntc2018", section: "4.2-step4d", sourceId, status: "transcribed-unreviewed", formulas: [], tables: [tableXII, tableXIII], figures: [figure23, figure24] };
await mkdir(unitDir, { recursive: true });
await mkdir(assetDir, { recursive: true });
await Promise.all([...units.map((u) => writeFile(join(unitDir, u.numbering.official + ".json"), JSON.stringify(u, null, 2) + "\n", "utf8")), writeFile(join(assetDir, "4.2-step4d.json"), JSON.stringify(manifest, null, 2) + "\n", "utf8")]);
console.log("NTC 4.2 step4d: generate " + units.length + " unità, 0 formule, 2 tabelle e 2 figure.");
