import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { sha256OfText } from "../src/lib/hash.ts";
const root = fileURLToPath(new URL("../", import.meta.url));
const unitDir = join(root, "corpus", "units", "ntc2018");
const assetDir = join(root, "corpus", "assets", "ntc2018");
const sourceId = "gu-so8-2018-ntc";
const workId = "it-mit:dm:2018-01-17:ntc2018";
const expressionId = "it-mit:dm:2018-01-17:ntc2018:original-it";
const profile = "ntc42-editorial-profile-0.1.0";
const createdAt = "2026-08-09T00:00:00Z";
type Region = { coordinateSystem: "pdf-points-top-left"; x: number; y: number; width: number; height: number };
type Opt = { page: number; printedPage: string; wrap?: boolean; discretionaryHyphen?: boolean; manual?: boolean };
type Inline = { kind: "text" | "math"; value: string; latex?: string };
const uid = (n: string) => "urn:structural-codes:it:unit:ntc2018:" + n;
const fid = (n: string) => "urn:structural-codes:it:asset:formula:ntc2018:" + n;
const tid = (n: string) => "urn:structural-codes:it:asset:table:ntc2018:" + n;
const gid = (n: string) => "urn:structural-codes:it:asset:figure:ntc2018:" + n;
const reg = (x: number, y: number, width: number, height: number): Region => ({ coordinateSystem: "pdf-points-top-left", x, y, width, height });
const p = (page: number, printedPage: string, options: Omit<Opt, "page" | "printedPage"> = {}): Opt => ({ page, printedPage, ...options });
const t = (value: string): Inline => ({ kind: "text", value });
const m = (value: string, latex: string): Inline => ({ kind: "math", value, latex });
function trans(o: Opt) { const a: Array<{ operation: string; ruleVersion: string; note: string }> = []; if (o.wrap) a.push({ operation: "join-line-wrap", ruleVersion: profile, note: "Unite le righe del capoverso e normalizza gli spazi." }, { operation: "normalize-whitespace", ruleVersion: profile, note: "Uniformati gli spazi dopo la ricomposizione." }); if (o.discretionaryHyphen) a.push({ operation: "remove-discretionary-hyphen", ruleVersion: profile, note: "Ricomposte le parole spezzate dal trattino tipografico." }); if (o.manual) a.push({ operation: "manual-correction", ruleVersion: profile, note: "Ripristinati accenti, simboli e matematica confrontati con il render ufficiale." }); if (o.wrap || o.manual) a.push({ operation: "unicode-nfc", ruleVersion: profile, note: "Testo normalizzato in Unicode NFC." }); return a; }
function ev(o: Opt, r: Region, raw: string, normalized: string) { return { sourceId, pdfPage: o.page, printedPage: o.printedPage, region: r, extraction: { method: "pdf-text", tool: "pdfjs-dist", toolVersion: "4.10.38" }, transformations: trans(o), rawSha256: sha256OfText(raw), normalizedSha256: sha256OfText(normalized) }; }
function block(n: string, s: string, kind: "heading" | "paragraph", o: Opt, r: Region, raw: string, normalized: string, inline: Inline[] = [t(normalized)]) { return { blockId: uid(n) + "#block-" + s, kind, origin: "official", text: { raw, normalized, normalizationVersion: profile, inline }, evidence: ev(o, r, raw, normalized) }; }
function formula(n: string, num: string, o: Opt, r: Region) { return { blockId: uid(n) + "#block-formula-" + num.replaceAll(".", "-"), kind: "formula-ref", origin: "official", assetId: fid(num), evidence: { ...ev({ ...o, manual: true }, r, "[" + num + "]", "[" + num + "]"), extraction: { method: "manual-transcription", tool: "codex-source-transcription", toolVersion: profile } } }; }
function assetBlock(n: string, s: string, kind: "table-ref" | "figure-ref", asset: string, o: Opt, r: Region) { const note = kind === "table-ref" ? "Tabella strutturata dal render ufficiale; revisione umana cella per cella ancora obbligatoria." : "Crop raster ufficiale verificato sul render; revisione umana del posizionamento ancora obbligatoria."; return { blockId: uid(n) + "#block-" + s, kind, origin: "official", assetId: asset, evidence: { ...ev({ ...o, manual: true }, r, note, note), extraction: { method: "manual-transcription", tool: "codex-source-transcription", toolVersion: profile } } }; }
function parent(n: string) { const a = n.split("."); return a.length === 1 ? null : uid(a.slice(0, -1).join(".")); }
function ancestors(n: string) { const a = n.split("."); return a.slice(1).map((_, i) => uid(a.slice(0, i + 1).join("."))); }
function unit(n: string, title: string, blocks: unknown[], formulas: string[] = [], tables: string[] = [], figures: string[] = []) { return { $schema: "urn:structural-codes:schema:canonical-unit:v2", schemaVersion: "2.0.0-alpha.2", recordType: "canonical-unit", id: uid(n), workId, expressionId, kind: "subparagraph", numbering: { official: n, sortKey: n.split(".").map((x) => x.padStart(3, "0")).join(".") }, title, titleBlockId: uid(n) + "#block-heading", hierarchy: { parentId: parent(n), ancestorIds: ancestors(n), position: Number(n.split(".").at(-1)) }, validity: { from: "2018-03-22", to: null, status: "in-force", asOf: "2026-08-09" }, blocks, citations: [], relations: [], assets: { formulaIds: formulas.map(fid), tableIds: tables.map(tid), figureIds: figures.map(gid) }, workflow: { status: "extracted", createdBy: { actorId: "codex:ntc42-step5", kind: "automated-agent", toolVersion: profile }, createdAt, reviews: [], openIssues: [{ issueId: "ntc2018-" + n.replaceAll(".", "-") + "-source-review", type: "normalization-review", severity: "blocking", note: "Record trascritto dall’evidence ufficiale ma non ancora confrontato integralmente da un revisore umano con il render della fonte." }, ...tables.map(() => ({ issueId: "ntc2018-" + n.replaceAll(".", "-") + "-assets", type: "asset-review", severity: "blocking", note: "La tabella è strutturata e richiede verifica umana cella per cella." })), ...figures.map(() => ({ issueId: "ntc2018-" + n.replaceAll(".", "-") + "-figures", type: "asset-review", severity: "blocking", note: "Il crop ufficiale è registrato; resta la revisione umana del posizionamento." }))] } }; }
const tables = {
    xiv: {
        id: tid("4.2.xiv"), unitId: uid("4.2.8"), officialNumber: "4.2.XIV", pdfPage: 112, caption: "Coefficienti di sicurezza per la verifica delle unioni", columnCount: 2, headers: [],
        rows: [
            [{ text: "Resistenza dei bulloni" }, { text: "γM2 = 1,25", latex: "\\gamma_{M2}=1{,}25", rowSpan: 5 }],
            [{ text: "Resistenza dei chiodi" }],
            [{ text: "Resistenza delle connessioni a perno" }],
            [{ text: "Resistenza delle saldature a parziale penetrazione e a cordone d’angolo" }],
            [{ text: "Resistenza dei piatti a contatto" }],
            [{ text: "Resistenza a scorrimento: per SLU" }, { text: "γM3 = 1,25", latex: "\\gamma_{M3}=1{,}25" }],
            [{ text: "per SLE" }, { text: "γM3 = 1,10", latex: "\\gamma_{M3}=1{,}10" }],
            [{ text: "Resistenza delle connessioni a perno allo stato limite di esercizio" }, { text: "γM6,ser = 1,0", latex: "\\gamma_{M6,ser}=1{,}0" }],
            [{ text: "Precarico di bullone ad alta resistenza con serraggio controllato" }, { text: "γM7 = 1,0", latex: "\\gamma_{M7}=1{,}0" }],
            [{ text: "Precarico di bullone ad alta resistenza con serraggio non controllato" }, { text: "γM7 = 1,10", latex: "\\gamma_{M7}=1{,}10" }],
        ], notes: [],
    },
    xv: {
        id: tid("4.2.xv"), unitId: uid("4.2.8.1.1"), officialNumber: "4.2.XV", pdfPage: 113, caption: "Classi funzionali per i bulloni", columnCount: 2, headers: [],
        rows: [
            [{ text: "K0", latex: "K0" }, { text: "Nessun requisito sul fattore k", latex: "\\text{Nessun requisito sul fattore }k" }],
            [{ text: "K1", latex: "K1" }, { text: "Campo di variabilità del fattore ki del singolo elemento tra minimo e massimo dichiarati sulla confezione", latex: "\\text{Campo di variabilità del fattore }k_i\\text{ del singolo elemento tra minimo e massimo dichiarati sulla confezione}" }],
            [{ text: "K2", latex: "K2" }, { text: "Valore medio km del fattore e suo coefficiente di variazione Vk dichiarati sulla confezione", latex: "\\text{Valore medio }k_m\\text{ del fattore e suo coefficiente di variazione }V_k\\text{ dichiarati sulla confezione}" }],
        ], notes: [],
    },
    xvi: {
        id: tid("4.2.xvi"), unitId: uid("4.2.8.1.1"), officialNumber: "4.2.XVI", pdfPage: 113, caption: "Coppie di serraggio per i bulloni 8.8", columnCount: 7,
        headers: [
            [{ text: "Viti 8.8 – Momento di serraggio M [N m]", colSpan: 7 }],
            [{ text: "Vite" }, { text: "k=0,10", latex: "k=0{,}10" }, { text: "k=0,12", latex: "k=0{,}12" }, { text: "k=0,14", latex: "k=0{,}14" }, { text: "k=0,16", latex: "k=0{,}16" }, { text: "Fp,C [kN]", latex: "F_{p,C}\\,[\\mathrm{kN}]" }, { text: "Ares [mm²]", latex: "A_{res}\\,[\\mathrm{mm^2}]" }],
        ], rows: [["M12", "56,6", "68,0", "79,3", "90,6", "47,2", "84,3"], ["M14", "90,2", "108", "126", "144", "64,4", "115"], ["M16", "141", "169", "197", "225", "87,9", "157"], ["M18", "194", "232", "271", "310", "108", "192"], ["M20", "274", "329", "384", "439", "137", "245"], ["M22", "373", "448", "523", "597", "170", "303"], ["M24", "474", "569", "664", "759", "198", "353"], ["M27", "694", "833", "972", "1110", "257", "459"], ["M30", "942", "1131", "1319", "1508", "314", "561"], ["M36", "1647", "1976", "2306", "2635", "457", "817"]].map((row) => row.map((text) => ({ text }))), notes: [],
    },
    xvii: {
        id: tid("4.2.xvii"), unitId: uid("4.2.8.1.1"), officialNumber: "4.2.XVII", pdfPage: 113, caption: "Coppie di serraggio per bulloni 10.9", columnCount: 7,
        headers: [
            [{ text: "Viti 10.9 – Momento di serraggio M [N m]", colSpan: 7 }],
            [{ text: "Vite" }, { text: "k=0,10", latex: "k=0{,}10" }, { text: "k=0,12", latex: "k=0{,}12" }, { text: "k=0,14", latex: "k=0{,}14" }, { text: "k=0,16", latex: "k=0{,}16" }, { text: "Fp,C [kN]", latex: "F_{p,C}\\,[\\mathrm{kN}]" }, { text: "Ares [mm²]", latex: "A_{res}\\,[\\mathrm{mm^2}]" }],
        ], rows: [["M12", "70,8", "85,0", "99,1", "113", "59,0", "84,3"].map((text) => ({ text })), ["M14", "113", "135", "158", "180", "80,5", "115"].map((text) => ({ text })), ["M16", "176", "211", "246", "281", "110", "157"].map((text) => ({ text })), ["M18", "242", "290", "339", "387", "134", "192"].map((text) => ({ text })), ["M20", "343", "412", "480", "549", "172", "245"].map((text) => ({ text })), ["M22", "467", "560", "653", "747", "212", "303"].map((text) => ({ text })), ["M24", "593", "712", "830", "949", "247", "353"].map((text) => ({ text })), ["M27", "868", "1041", "1215", "1388", "321", "459"].map((text) => ({ text })), ["M30", "1178", "1414", "1649", "1885", "393", "561"].map((text) => ({ text })), ["M36", "2059", "2471", "2882", "3294", "572", "817"].map((text) => ({ text }))], notes: [],
    },
    xviii: {
        id: tid("4.2.xviii"), unitId: uid("4.2.8.1.1"), officialNumber: "4.2.XVIII", pdfPage: 114, caption: "Posizione dei fori per unioni bullonate e chiodate", columnCount: 5,
        headers: [
            [{ text: "Distanze e interassi (Fig. 4.2.5)", rowSpan: 2 }, { text: "Minimo", rowSpan: 2 }, { text: "Massimo", colSpan: 3 }],
            [{ text: "Unioni esposte a fenomeni corrosivi o ambientali" }, { text: "Unioni non esposte a fenomeni corrosivi o ambientali" }, { text: "Unioni di elementi in acciaio resistente alla corrosione (UNI EN10025-5)" }],
        ],
        rows: [
            [{ text: "e1", latex: "e_1" }, { text: "1,2 d0", latex: "1{,}2d_0" }, { text: "4t+40 mm", latex: "4t+40\\,\\mathrm{mm}" }, { text: "–" }, { text: "max(8t;12 mm)", latex: "\\max(8t;12\\,\\mathrm{mm})" }],
            [{ text: "e2", latex: "e_2" }, { text: "1,2 d0", latex: "1{,}2d_0" }, { text: "4t+40 mm", latex: "4t+40\\,\\mathrm{mm}" }, { text: "–" }, { text: "max(8t;125 mm)", latex: "\\max(8t;125\\,\\mathrm{mm})" }],
            [{ text: "p1", latex: "p_1" }, { text: "2,2 d0", latex: "2{,}2d_0" }, { text: "min(14t;200 mm)", latex: "\\min(14t;200\\,\\mathrm{mm})" }, { text: "min(14t;200 mm)", latex: "\\min(14t;200\\,\\mathrm{mm})" }, { text: "min(14t;175 mm)", latex: "\\min(14t;175\\,\\mathrm{mm})" }],
            [{ text: "p1,0", latex: "p_{1,0}" }, { text: "–" }, { text: "min(14t;200 mm)", latex: "\\min(14t;200\\,\\mathrm{mm})" }, { text: "–" }, { text: "–" }],
            [{ text: "p1,i", latex: "p_{1,i}" }, { text: "–" }, { text: "min(28t;400 mm)", latex: "\\min(28t;400\\,\\mathrm{mm})" }, { text: "–" }, { text: "–" }],
            [{ text: "p2", latex: "p_2" }, { text: "2,4 d0", latex: "2{,}4d_0" }, { text: "min(14t;200 mm)", latex: "\\min(14t;200\\,\\mathrm{mm})" }, { text: "min(14t;200 mm)", latex: "\\min(14t;200\\,\\mathrm{mm})" }, { text: "min(14t;175 mm)", latex: "\\min(14t;175\\,\\mathrm{mm})" }],
        ], notes: ["La tabella fa riferimento agli schemi di unione della Fig. 4.2.5."],
    },
};
const figure = { id: gid("4.2.5"), unitId: uid("4.2.8.1.1"), officialNumber: "4.2.5", pdfPage: 114, caption: "Fig. 4.2.5 - Disposizione dei fori per la realizzazione di unioni bullonate o chiodate", alt: "Schemi di disposizione dei fori e relative distanze e interassi per unioni bullonate o chiodate.", imagePath: "figures/ntc2018/fig4.2.5.png", region: reg(75, 535, 450, 145), sha256: "ad181b9eae35719a950ed534c6a651efa1beb0c9808c3fcc55ffc9f1ec6409d2" };
const units = [
    unit("4.2.8.1", "UNIONI CON BULLONI, CHIODI E PERNI SOGGETTI A CARICHI STATICI", [
        block("4.2.8.1", "heading", "heading", p(113, "109", { manual: true }), reg(82.954, 98, 420, 7.476), "4.2.8.1 U NIONI CON BULLONI , CHIODI E PERNI SOGGETTI A CARICHI STATICI", "4.2.8.1 UNIONI CON BULLONI, CHIODI E PERNI SOGGETTI A CARICHI STATICI"),
        block("4.2.8.1", "p1", "paragraph", p(113, "109"), reg(82.954, 111, 428.6, 7.482), "Le unioni realizzate con bulloni si distinguono in “non precaricate” e “precaricate”.", "Le unioni realizzate con bulloni si distinguono in “non precaricate” e “precaricate”."),
        block("4.2.8.1", "p2", "paragraph", p(113, "109", { wrap: true, discretionaryHyphen: true }), reg(82.954, 124, 428.6, 17.6), "Le unioni realizzate con chiodi si considerano sempre “non precaricate” e i chiodi devono essere preferibilmente impegnati a taglio.", "Le unioni realizzate con chiodi si considerano sempre “non precaricate” e i chiodi devono essere preferibilmente impegnati a taglio."),
        block("4.2.8.1", "p3", "paragraph", p(113, "109"), reg(82.954, 150, 428.6, 7.482), "I perni delle cerniere sono sollecitati a taglio e flessione.", "I perni delle cerniere sono sollecitati a taglio e flessione."),
    ]),
    unit("4.2.8.1.1", "Unioni con bulloni e chiodi", [
        block("4.2.8.1.1", "heading", "heading", p(113, "109", { manual: true }), reg(82.954, 180, 190, 7.476), "4.2.8.1.1 Unioni con bulloni e chiodi", "4.2.8.1.1 Unioni con bulloni e chiodi"),
        block("4.2.8.1.1", "p1", "paragraph", p(113, "109", { wrap: true }), reg(82.954, 193, 428.6, 17.6), "Nei collegamenti con bulloni “non precaricati” gli assiemi Vite/Dado/Rondella devono essere conformi a quanto specificato nel § 11.3.4.6.1.", "Nei collegamenti con bulloni “non precaricati” gli assiemi Vite/Dado/Rondella devono essere conformi a quanto specificato nel § 11.3.4.6.1."),
        block("4.2.8.1.1", "p2", "paragraph", p(113, "109", { wrap: true }), reg(82.954, 218, 428.6, 17.6), "Nei collegamenti con bulloni “precaricati” gli assiemi Vite/Dado/Rondella devono essere conformi a quanto specificato nel § 11.3.4.6.2.", "Nei collegamenti con bulloni “precaricati” gli assiemi Vite/Dado/Rondella devono essere conformi a quanto specificato nel § 11.3.4.6.2."),
        block("4.2.8.1.1", "p3", "paragraph", p(113, "109", { wrap: true }), reg(82.954, 243, 428.6, 27.6), "Nelle unioni con bulloni ad alta resistenza delle classi 8.8 e 10.9, precaricati con serraggio controllato, per giunzioni ad attrito, le viti, i dadi e le rondelle devono essere forniti dal medesimo produttore. Il momento di serraggio M per tali unioni è pari a:", "Nelle unioni con bulloni ad alta resistenza delle classi 8.8 e 10.9, precaricati con serraggio controllato, per giunzioni ad attrito, le viti, i dadi e le rondelle devono essere forniti dal medesimo produttore. Il momento di serraggio M per tali unioni è pari a:"),
        formula("4.2.8.1.1", "4.2.61", p(113, "109"), reg(180, 277, 250, 25)),
        block("4.2.8.1.1", "p4", "paragraph", p(113, "109", { wrap: true }), reg(82.954, 310, 428.6, 17.6), "dove: d è il diametro nominale della vite, Ares è l’area resistente della vite e ftbk è la resistenza a rottura del materiale della vite.", "dove: d è il diametro nominale della vite, Ares è l’area resistente della vite e ftbk è la resistenza a rottura del materiale della vite.", [t("dove: "), m("d", "d"), t(" è il diametro nominale della vite, "), m("Ares", "A_{res}"), t(" è l’area resistente della vite e "), m("ftbk", "f_{tbk}"), t(" è la resistenza a rottura del materiale della vite.")]),
        block("4.2.8.1.1", "p5", "paragraph", p(113, "109", { wrap: true }), reg(82.954, 335, 428.6, 27.6), "Il valore del fattore k è indicato sulle targhette delle confezioni (dei bulloni, oppure delle viti) per le tre classi funzionali specificate nella seguente Tabella 4.2.XV.", "Il valore del fattore k è indicato sulle targhette delle confezioni (dei bulloni, oppure delle viti) per le tre classi funzionali specificate nella seguente Tabella 4.2.XV."),
        assetBlock("4.2.8.1.1", "table-xv", "table-ref", tables.xv.id, p(113, "109"), reg(82.954, 311, 428.6, 105)),
        block("4.2.8.1.1", "p6", "paragraph", p(113, "109", { wrap: true }), reg(82.954, 430, 428.6, 27.6), "Nel caso il momento di serraggio non sia riportato sulle targhette delle confezioni, ma compaia il solo fattore k secondo la classe funzionale, si può fare riferimento alle seguenti Tabelle 4.2.XVI e 4.2.XVII, che si riferiscono rispettivamente alle viti di classe 8.8 e 10.9.", "Nel caso il momento di serraggio non sia riportato sulle targhette delle confezioni, ma compaia il solo fattore k secondo la classe funzionale, si può fare riferimento alle seguenti Tabelle 4.2.XVI e 4.2.XVII, che si riferiscono rispettivamente alle viti di classe 8.8 e 10.9."),
        assetBlock("4.2.8.1.1", "table-xvi", "table-ref", tables.xvi.id, p(113, "109"), reg(82.954, 419, 330, 145)),
        assetBlock("4.2.8.1.1", "table-xvii", "table-ref", tables.xvii.id, p(113, "109"), reg(82.954, 574, 330, 145)),
        block("4.2.8.1.1", "p7", "paragraph", p(114, "110", { wrap: true }), reg(82.954, 99, 428.6, 37.6), "Nelle tabelle sono riportati: la dimensione della vite MXX, l’area resistente della vite Ares in mm², la forza di precarico Fp,C = 0,7·Ares·ftbk in kN ed i valori del momento di serraggio M in Nm, corrispondenti a differenti valori del fattore k. Poiché il momento di serraggio è funzione lineare del fattore k, la interpolazione per righe è immediata.", "Nelle tabelle sono riportati: la dimensione della vite MXX, l’area resistente della vite Ares in mm², la forza di precarico Fp,C = 0,7·Ares·ftbk in kN ed i valori del momento di serraggio M in Nm, corrispondenti a differenti valori del fattore k. Poiché il momento di serraggio è funzione lineare del fattore k, la interpolazione per righe è immediata.", [t("Nelle tabelle sono riportati: la dimensione della vite MXX, l’area resistente della vite "), m("Ares", "A_{res}"), t(" in mm², la forza di precarico "), m("Fp,C = 0,7·Ares·ftbk", "F_{p,C}=0{,}7\\cdot A_{res}\\cdot f_{tbk}"), t(" in kN ed i valori del momento di serraggio M in Nm, corrispondenti a differenti valori del fattore k. Poiché il momento di serraggio è funzione lineare del fattore k, la interpolazione per righe è immediata.")]),
        block("4.2.8.1.1", "p8", "paragraph", p(114, "110"), reg(82.954, 145, 428.6, 7.482), "E’ consigliabile utilizzare, per quanto possibile, lotti di produzione di bulloni omogenei.", "E’ consigliabile utilizzare, per quanto possibile, lotti di produzione di bulloni omogenei."),
        block("4.2.8.1.1", "p9", "paragraph", p(114, "110", { wrap: true }), reg(82.954, 160, 428.6, 17.6), "Nel caso di carichi dinamici e/o vibrazione è opportuno predisporre sistemi antisvitamento reperibili in norme di comprovata validità tecnica.", "Nel caso di carichi dinamici e/o vibrazione è opportuno predisporre sistemi antisvitamento reperibili in norme di comprovata validità tecnica."),
        block("4.2.8.1.1", "p10", "paragraph", p(114, "110", { wrap: true, discretionaryHyphen: true }), reg(82.954, 185, 428.6, 17.6), "Nel caso di utilizzo di bulloneria con classe funzionale K1 o K2, tutti i bulloni “non precaricati” devono essere adeguatamente serrati.", "Nel caso di utilizzo di bulloneria con classe funzionale K1 o K2, tutti i bulloni “non precaricati” devono essere adeguatamente serrati."),
        block("4.2.8.1.1", "p11", "paragraph", p(114, "110"), reg(82.954, 210, 428.6, 7.482), "Il serraggio dei bulloni deve essere eseguito in accordo alla norma UNI EN 1090-2:2011.", "Il serraggio dei bulloni deve essere eseguito in accordo alla norma UNI EN 1090-2:2011."),
        block("4.2.8.1.1", "p12", "paragraph", p(114, "110", { wrap: true }), reg(82.954, 225, 428.6, 37.6), "Nei giunti con bulloni ad alta resistenza “precaricati” la resistenza ad attrito dipende dalle modalità di preparazione delle superfici a contatto, dalle modalità di esecuzione e dal gioco foro-bullone. In via semplificativa la resistenza di progetto allo scorrimento di un bullone ad attrito si calcolerà assumendo una forza di precarico pari al 70% della resistenza ultima a trazione del bullone. Il valore della forza di “precarico” da assumere nelle unioni progettate ad attrito, per lo stato limite di servizio oppure per lo stato limite ultimo è pari quindi a", "Nei giunti con bulloni ad alta resistenza “precaricati” la resistenza ad attrito dipende dalle modalità di preparazione delle superfici a contatto, dalle modalità di esecuzione e dal gioco foro-bullone. In via semplificativa la resistenza di progetto allo scorrimento di un bullone ad attrito si calcolerà assumendo una forza di precarico pari al 70% della resistenza ultima a trazione del bullone. Il valore della forza di “precarico” da assumere nelle unioni progettate ad attrito, per lo stato limite di servizio oppure per lo stato limite ultimo è pari quindi a"),
        formula("4.2.8.1.1", "4.2.62", p(114, "110"), reg(180, 272, 250, 25)),
        block("4.2.8.1.1", "p13", "paragraph", p(114, "110"), reg(82.954, 307, 428.6, 7.482), "dove Ares è l’area resistente della vite del bullone", "dove Ares è l’area resistente della vite del bullone", [t("dove "), m("Ares", "A_{res}"), t(" è l’area resistente della vite del bullone")]),
        block("4.2.8.1.1", "p14", "paragraph", p(114, "110", { wrap: true, discretionaryHyphen: true }), reg(82.954, 322, 428.6, 17.6), "La posizione dei fori per le unioni bullonate o chiodate deve rispettare le limitazioni presentate nella Tab. 4.2.XVIII, che fa riferimento agli schemi di unione riportati nella Fig. 4.2.5.", "La posizione dei fori per le unioni bullonate o chiodate deve rispettare le limitazioni presentate nella Tab. 4.2.XVIII, che fa riferimento agli schemi di unione riportati nella Fig. 4.2.5."),
        assetBlock("4.2.8.1.1", "table-xviii", "table-ref", tables.xviii.id, p(114, "110"), reg(82.954, 333, 430, 155)),
        block("4.2.8.1.1", "p15", "paragraph", p(114, "110", { wrap: true }), reg(82.954, 490, 428.6, 27.6), "L’instabilità locale del piatto posto tra i bulloni/chiodi non deve essere considerata se (p1/t) < [9(235/fy)0,5]: in caso contrario si assumerà una lunghezza di libera inflessione pari a 0,6·p1. t è lo spessore minimo degli elementi esterni collegati.", "L’instabilità locale del piatto posto tra i bulloni/chiodi non deve essere considerata se (p1/t) < [9(235/fy)0,5]: in caso contrario si assumerà una lunghezza di libera inflessione pari a 0,6·p1. t è lo spessore minimo degli elementi esterni collegati.", [t("L’instabilità locale del piatto posto tra i bulloni/chiodi non deve essere considerata se "), m("(p1/t) < [9(235/fy)0,5]", "\\left(\\frac{p_1}{t}\\right)<\\left[9\\left(\\frac{235}{f_y}\\right)^{0{,}5}\\right]"), t(": in caso contrario si assumerà una lunghezza di libera inflessione pari a "), m("0,6·p1", "0{,}6\\cdot p_1"), t(". "), m("t", "t"), t(" è lo spessore minimo degli elementi esterni collegati.")]),
        block("4.2.8.1.1", "p16", "paragraph", p(114, "110", { wrap: true }), reg(82.954, 525, 428.6, 37.6), "I fori devono avere diametro uguale a quello del bullone maggiorato al massimo di 1 mm, per bulloni sino a 20 mm di diametro, e di 1,5 mm per bulloni di diametro maggiore di 20 mm. Si può derogare da tali limiti quando eventuali assestamenti sotto i carichi di servizio non comportino il superamento dei limiti di deformabilità o di servizio. Quando necessario, è possibile adottare “accoppiamenti di precisione” in cui il gioco foro-bullone non dovrà superare 0,3 mm per bulloni sino a 20 mm di diametro e 0,5 mm per bulloni di diametro superiore, o altri accorgimenti di riconosciuta validità.", "I fori devono avere diametro uguale a quello del bullone maggiorato al massimo di 1 mm, per bulloni sino a 20 mm di diametro, e di 1,5 mm per bulloni di diametro maggiore di 20 mm. Si può derogare da tali limiti quando eventuali assestamenti sotto i carichi di servizio non comportino il superamento dei limiti di deformabilità o di servizio. Quando necessario, è possibile adottare “accoppiamenti di precisione” in cui il gioco foro-bullone non dovrà superare 0,3 mm per bulloni sino a 20 mm di diametro e 0,5 mm per bulloni di diametro superiore, o altri accorgimenti di riconosciuta validità."),
        block("4.2.8.1.1", "p17", "paragraph", p(114, "110"), reg(82.954, 570, 428.6, 7.482), "Per fori asolati o maggiorati devono essere utilizzate le indicazioni riportate in UNI EN 1993-1-8.", "Per fori asolati o maggiorati devono essere utilizzate le indicazioni riportate in UNI EN 1993-1-8."),
        assetBlock("4.2.8.1.1", "figure-4-2-5", "figure-ref", figure.id, p(114, "110"), reg(75, 535, 450, 145)),
    ], ["4.2.61", "4.2.62"], ["4.2.xv", "4.2.xvi", "4.2.xvii", "4.2.xviii"], ["4.2.5"]),
];
const formulaRows = [["4.2.61", "4.2.8.1.1", 113, "M=k\\cdot d\\cdot F_{p,c}=k\\cdot d\\cdot0{,}7\\cdot A_{res}\\cdot f_{tbk}"], ["4.2.62", "4.2.8.1.1", 114, "F_{p,Cd}=0{,}7\\cdot\\frac{f_{tbk}\\cdot A_{res}}{\\gamma_{M7}}"]] as const;
const manifest = { $schema: "urn:structural-codes:schema:asset-manifest:v2", schemaVersion: "2.0.0-alpha.1", recordType: "asset-manifest", document: "ntc2018", section: "4.2-step5", sourceId, status: "transcribed-unreviewed", formulas: formulaRows.map(([n, u, page, latex]) => ({ id: fid(n), unitId: uid(u), officialNumber: n, pdfPage: page, latex })), tables: [tables.xiv, tables.xv, tables.xvi, tables.xvii, tables.xviii], figures: [figure] };
await mkdir(unitDir, { recursive: true });
await mkdir(assetDir, { recursive: true });
await Promise.all([...units.map((u) => writeFile(join(unitDir, u.numbering.official + ".json"), JSON.stringify(u, null, 2) + "\n", "utf8")), writeFile(join(assetDir, "4.2-step5.json"), JSON.stringify(manifest, null, 2) + "\n", "utf8")]);
console.log("NTC 4.2 step5: generate " + units.length + " unità, 2 formule, 5 tabelle e 1 figura.");
