import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { sha256OfText } from "../src/lib/hash.ts";

const root = fileURLToPath(new URL("../", import.meta.url));
const unitDirectory = join(root, "corpus", "units", "circ2019");
const assetDirectory = join(root, "corpus", "assets", "circ2019");
const sourceId = "circ-7-2019";
const workId = "it-mit:circ:2019-01-21:7-csllpp";
const expressionId = "it-mit:circ:2019-01-21:7-csllpp:original-it";
const profile = "circ42-editorial-profile-0.1.0";
const createdAt = "2026-08-09T00:00:00Z";
const unitNumber = "C4.2.4.1.4.5";

type Region = { coordinateSystem: "pdf-points-top-left"; x: number; y: number; width: number; height: number };
type Inline = { kind: "text" | "math"; value: string; latex?: string };
type FormulaRow = { number: string; page: number; latex: string; raw: string; region: Region };
type GeneratedBlock = { blockId: string; kind: string; origin: "official"; text?: { raw: string; normalized: string; normalizationVersion: string; inline: Inline[] }; evidence: { rawSha256: string; normalizedSha256: string; [key: string]: unknown }; assetId?: string };

const uid = (number: string) => `urn:structural-codes:it:unit:circ2019:${number.toLowerCase()}`;
const formulaId = (number: string) => `urn:structural-codes:it:asset:formula:circ2019:${number.toLowerCase()}`;
const reg = (x: number, y: number, width: number, height: number): Region => ({ coordinateSystem: "pdf-points-top-left", x, y, width, height });
const text = (value: string): Inline => ({ kind: "text", value });
const math = (value: string, latex: string): Inline => ({ kind: "math", value, latex });
const hash = (value: string) => sha256OfText(value);
function evidence(page: number, raw: string, normalized: string, region: Region, manual = false) {
    return { sourceId, pdfPage: page, printedPage: String(page - 4), region, extraction: { method: manual ? "manual-transcription" : "pdf-text", tool: manual ? "codex-source-transcription" : "pdfjs-dist", toolVersion: manual ? profile : "4.10.38" }, transformations: [{ operation: "join-line-wrap", ruleVersion: profile, note: "Ricomposte le righe tipografiche appartenenti allo stesso capoverso; la formula resta un blocco distinto." }, ...(raw !== normalized ? [{ operation: "manual-correction", ruleVersion: profile, note: "Ripristinati accenti, apostrofi, simboli e notazione matematica confrontati con i render ufficiali." }] : []), { operation: "unicode-nfc", ruleVersion: profile, note: "Testo normalizzato in Unicode NFC." }], rawSha256: hash(raw), normalizedSha256: hash(normalized) };
}
function block(suffix: string, kind: "heading" | "paragraph", page: number, normalized: string, inline: Inline[], region: Region): GeneratedBlock { return { blockId: `${uid(unitNumber)}#block-${suffix}`, kind, origin: "official", text: { raw: normalized, normalized, normalizationVersion: profile, inline }, evidence: evidence(page, normalized, normalized, region) }; }
function formulaBlock(suffix: string, formula: FormulaRow): GeneratedBlock { return { blockId: `${uid(unitNumber)}#block-${suffix}`, kind: "formula-ref", origin: "official", assetId: formulaId(formula.number), evidence: evidence(formula.page, formula.raw, formula.raw, formula.region, true) }; }

const formula99: FormulaRow = { number: "C4.2.99", page: 134, latex: "D=D_{\\sigma}+D_{\\tau}\\le1{,}0", raw: "D = Dσ + Dτ ≤ 1,0 [C4.2.99]", region: reg(175, 235, 250, 45) };
const blocks: GeneratedBlock[] = [
    block("heading", "heading", 133, "C4.2.4.1.4.5. Metodi di verifica", [text("C4.2.4.1.4.5. Metodi di verifica")], reg(73.9, 690, 450, 25)),
    block("p1", "paragraph", 133, "Nelle verifiche a fatica le tensioni da considerare devono essere coerenti con quelle alle quali è riferita la curva S-N del dettaglio. Di solito, le curve S-N dei dettagli costruttivi riportate nelle normative sono riferite alle tensioni nominali e pertanto ad esse si deve generalmente far riferimento. Per dettagli costruttivi particolarmente complessi o innovativi, per i quali si proceda ad uno studio ad hoc, potrebbe essere necessario riferirsi alle tensioni di picco, misurate o determinate con specifici protocolli sperimentali. In questo caso, le tensioni devono essere calcolate per via teorica o numerica con le stesse modalità adottate sperimentalmente.", [text("Nelle verifiche a fatica le tensioni da considerare devono essere coerenti con quelle alle quali è riferita la curva S-N del dettaglio. Di solito, le curve S-N dei dettagli costruttivi riportate nelle normative sono riferite alle tensioni nominali e pertanto ad esse si deve generalmente far riferimento. Per dettagli costruttivi particolarmente complessi o innovativi, per i quali si proceda ad uno studio ad hoc, potrebbe essere necessario riferirsi alle tensioni di picco, misurate o determinate con specifici protocolli sperimentali. In questo caso, le tensioni devono essere calcolate per via teorica o numerica con le stesse modalità adottate sperimentalmente.")], reg(73.9, 715, 450, 65)),
    block("p2", "paragraph", 134, "Nell’associare al dettaglio in esame la corrispondente curva S-N di resistenza a fatica è consentito tener conto degli effetti benefici di eventuali trattamenti termici o meccanici di distensione, sulla base della letteratura consolidata o di adeguata sperimentazione.", [text("Nell’associare al dettaglio in esame la corrispondente curva S-N di resistenza a fatica è consentito tener conto degli effetti benefici di eventuali trattamenti termici o meccanici di distensione, sulla base della letteratura consolidata o di adeguata sperimentazione.")], reg(73.9, 75, 450, 30)),
    block("p3", "paragraph", 134, "Per i dettagli costruttivi dei quali non sia nota la curva di resistenza a fatica le escursioni tensionali potranno riferirsi alle tensioni geometriche o di picco, cioè alle tensioni principali nel metallo base in prossimità della potenziale lesione, secondo le modalità e le limitazioni specifiche del metodo, nell’ambito della meccanica della frattura.", [text("Per i dettagli costruttivi dei quali non sia nota la curva di resistenza a fatica le escursioni tensionali potranno riferirsi alle tensioni geometriche o di picco, cioè alle tensioni principali nel metallo base in prossimità della potenziale lesione, secondo le modalità e le limitazioni specifiche del metodo, nell’ambito della meccanica della frattura.")], reg(73.9, 115, 450, 35)),
    block("p4", "paragraph", 134, "Nel caso di verifica a danneggiamento, sulla base del danno D si può definire uno spettro di tensione equivalente, ad ampiezza di tensione costante, Δσ_eq,d (o Δτ_eq,d), in grado di produrre, nello stesso numero di cicli, n_tot = Σ n_i, un danneggiamento uguale a quello prodotto dallo spettro di tensione di progetto, oppure, in alternativa, un delta di tensione convenzionale Δσ_Ed,d in grado di produrre in 2×10⁶ cicli, lo stesso danneggiamento prodotto dallo spettro di tensione di progetto.", [text("Nel caso di verifica a danneggiamento, sulla base del danno "), math("D", "D"), text(" si può definire uno spettro di tensione equivalente, ad ampiezza di tensione costante, "), math("Δσ_eq,d (o Δτ_eq,d)", "\\Delta\\sigma_{eq,d}\\; (\\text{o }\\Delta\\tau_{eq,d})"), text(", in grado di produrre, nello stesso numero di cicli, "), math("n_tot = Σ n_i", "n_{tot}=\\sum n_i"), text(", un danneggiamento uguale a quello prodotto dallo spettro di tensione di progetto, oppure, in alternativa, un delta di tensione convenzionale "), math("Δσ_Ed,d", "\\Delta\\sigma_{Ed,d}"), text(" in grado di produrre in "), math("2×10⁶", "2\\cdot10^6"), text(" cicli, lo stesso danneggiamento prodotto dallo spettro di tensione di progetto.")], reg(73.9, 155, 450, 75)),
    block("p5", "paragraph", 134, "Nel caso di variazioni simultanee di tensioni normali e tangenziali, la valutazione della resistenza a fatica dovrà considerare i loro effetti congiunti adottando idonei criteri di combinazione del danno.", [text("Nel caso di variazioni simultanee di tensioni normali e tangenziali, la valutazione della resistenza a fatica dovrà considerare i loro effetti congiunti adottando idonei criteri di combinazione del danno.")], reg(73.9, 235, 450, 25)),
    block("p6", "paragraph", 134, "Nel caso di variazioni non simultanee del campo di tensioni normali e tangenziali si potranno sommare i danneggiamenti Dσ e Dτ prodotti dai cicli di tensione normale e dai cicli di tensione tangenziale, valutati separatamente con la formula [4.2.57] del § 4.2.4.1.4 delle NTC, controllando che", [text("Nel caso di variazioni non simultanee del campo di tensioni normali e tangenziali si potranno sommare i danneggiamenti "), math("Dσ e Dτ", "D_{\\sigma}\\text{ e }D_{\\tau}"), text(" prodotti dai cicli di tensione normale e dai cicli di tensione tangenziale, valutati separatamente con la formula [4.2.57] del § 4.2.4.1.4 delle NTC, controllando che")], reg(73.9, 265, 450, 45)),
    formulaBlock("formula-99", formula99),
];

const parent = uid("C4.2.4.1.4");
const unit = { $schema: "urn:structural-codes:schema:canonical-unit:v2", schemaVersion: "2.0.0-alpha.2", recordType: "canonical-unit", id: uid(unitNumber), workId, expressionId, kind: "subparagraph", numbering: { official: unitNumber, sortKey: unitNumber.replace(/^C/, "").split(".").map((part) => part.padStart(3, "0")).join(".") }, title: "Metodi di verifica", titleBlockId: `${uid(unitNumber)}#block-heading`, hierarchy: { parentId: parent, ancestorIds: [uid("C4.2"), uid("C4.2.4"), uid("C4.2.4.1"), parent], position: 5 }, validity: { from: null, to: null, status: "unknown", asOf: "2026-08-09" }, blocks, citations: [], relations: [], assets: { formulaIds: [formulaId(formula99.number)], tableIds: [], figureIds: [] }, workflow: { status: "extracted", createdBy: { actorId: "codex:circ42-step2q", kind: "automated-agent", toolVersion: profile }, createdAt, reviews: [], openIssues: [{ issueId: "circ2019-C4-2-4-1-4-5-source-review", type: "normalization-review", severity: "blocking", note: "Record trascritto dall’evidence ufficiale ma non ancora confrontato integralmente da un revisore umano con i render delle pagine fonte." }, { issueId: "circ2019-C4-2-4-1-4-5-assets-review", type: "asset-review", severity: "blocking", note: "La formula C4.2.99 richiede revisione umana indipendente." }] } };
const manifest = { $schema: "urn:structural-codes:schema:asset-manifest:v2", schemaVersion: "2.0.0-alpha.1", recordType: "asset-manifest", document: "circ2019", section: "C4.2-step2q", sourceId, status: "transcribed-unreviewed", formulas: [{ id: formulaId(formula99.number), unitId: uid(unitNumber), officialNumber: formula99.number, pdfPage: formula99.page, latex: formula99.latex }], tables: [], figures: [] };
await mkdir(unitDirectory, { recursive: true });
await mkdir(assetDirectory, { recursive: true });
await Promise.all([writeFile(join(unitDirectory, `${unitNumber.toLowerCase()}.json`), `${JSON.stringify(unit, null, 2)}\n`, "utf8"), writeFile(join(assetDirectory, "C4.2-step2q.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8")]);
console.log("Circolare C4.2 step2q: generate 1 unità e 1 formula.");
