import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("../", import.meta.url));

type FormulaSeed = {
    number: string;
    officialNumber?: string | null;
    unit: string;
    page: number;
    latex: string;
};

const ntc: FormulaSeed[] = [
    { number: "2.2.1", unit: "2.3", page: 40, latex: "R_d \\ge E_d" },
    { number: "2.2.2", unit: "2.3", page: 40, latex: "C_d \\ge E_d" },
    { number: "2.4.1", unit: "2.4.3", page: 41, latex: "V_R = V_N \\cdot C_U" },
    {
        number: "2.5.1",
        unit: "2.5.3",
        page: 43,
        latex: "\\gamma_{G1}\\cdot G_1+\\gamma_{G2}\\cdot G_2+\\gamma_P\\cdot P+\\gamma_{Q1}\\cdot Q_{k1}+\\gamma_{Q2}\\cdot\\psi_{02}\\cdot Q_{k2}+\\gamma_{Q3}\\cdot\\psi_{03}\\cdot Q_{k3}+\\ldots",
    },
    { number: "2.5.2", unit: "2.5.3", page: 43, latex: "G_1+G_2+P+Q_{k1}+\\psi_{02}\\cdot Q_{k2}+\\psi_{03}\\cdot Q_{k3}+\\ldots" },
    { number: "2.5.3", unit: "2.5.3", page: 43, latex: "G_1+G_2+P+\\psi_{11}\\cdot Q_{k1}+\\psi_{22}\\cdot Q_{k2}+\\psi_{23}\\cdot Q_{k3}+\\ldots" },
    { number: "2.5.4", unit: "2.5.3", page: 43, latex: "G_1+G_2+P+\\psi_{21}\\cdot Q_{k1}+\\psi_{22}\\cdot Q_{k2}+\\psi_{23}\\cdot Q_{k3}+\\ldots" },
    { number: "2.5.5", unit: "2.5.3", page: 43, latex: "E+G_1+G_2+P+\\psi_{21}\\cdot Q_{k1}+\\psi_{22}\\cdot Q_{k2}+\\ldots" },
    { number: "2.5.6", unit: "2.5.3", page: 43, latex: "G_1+G_2+P+A_d+\\psi_{21}\\cdot Q_{k1}+\\psi_{22}\\cdot Q_{k2}+\\ldots" },
    { number: "2.5.7", unit: "2.5.3", page: 43, latex: "G_1+G_2+\\sum_j\\psi_{2j}\\cdot Q_{kj}" },
    { number: "3.1.1", unit: "3.1.4.1", page: 48, latex: "\\alpha_A=\\frac{5}{7}\\psi_0+\\frac{10}{A}\\le 1{,}0" },
    { number: "3.1.2", unit: "3.1.4.1", page: 48, latex: "\\alpha_n=\\frac{2+(n-2)\\psi_0}{n}" },
    { number: "3.2.0", unit: "3.2.1", page: 50, latex: "T_R=-\\frac{V_R}{\\ln(1-P_{VR})}=-\\frac{C_UV_N}{\\ln(1-P_{VR})}" },
    { number: "3.2.1", unit: "3.2.2", page: 50, latex: "V_{S,eq}=\\frac{H}{\\displaystyle\\sum_{i=1}^{N}\\frac{h_i}{V_{S,i}}}" },
    {
        number: "3.2.2",
        unit: "3.2.3.2.1",
        page: 51,
        latex: "\\begin{aligned}0\\le T<T_B\\quad&S_e(T)=a_g\\cdot S\\cdot\\eta\\cdot F_o\\cdot\\left[\\frac{T}{T_B}+\\frac{1}{\\eta\\cdot F_o}\\left(1-\\frac{T}{T_B}\\right)\\right]\\\\T_B\\le T<T_C\\quad&S_e(T)=a_g\\cdot S\\cdot\\eta\\cdot F_o\\\\T_C\\le T<T_D\\quad&S_e(T)=a_g\\cdot S\\cdot\\eta\\cdot F_o\\cdot\\left(\\frac{T_C}{T}\\right)\\\\T_D\\le T\\quad&S_e(T)=a_g\\cdot S\\cdot\\eta\\cdot F_o\\cdot\\left(\\frac{T_C\\cdot T_D}{T^2}\\right)\\end{aligned}",
    },
    { number: "3.2.3", unit: "3.2.3.2.1", page: 52, latex: "S=S_S\\cdot S_T" },
    { number: "3.2.4", unit: "3.2.3.2.1", page: 52, latex: "\\eta=\\sqrt{\\frac{10}{5+\\xi}}\\ge0{,}55" },
    { number: "3.2.5", unit: "3.2.3.2.1", page: 52, latex: "T_C=C_C\\cdot T_C^*" },
    { number: "3.2.6", unit: "3.2.3.2.1", page: 52, latex: "T_B=\\frac{T_C}{3}" },
    { number: "3.2.7", unit: "3.2.3.2.1", page: 52, latex: "T_D=4{,}0\\cdot\\frac{a_g}{g}+1{,}6" },
    {
        number: "3.2.8",
        unit: "3.2.3.2.2",
        page: 53,
        latex: "\\begin{aligned}0\\le T<T_B\\quad&S_{ve}(T)=a_g\\cdot S\\cdot\\eta\\cdot F_v\\cdot\\left[\\frac{T}{T_B}+\\frac{1}{\\eta\\cdot F_o}\\left(1-\\frac{T}{T_B}\\right)\\right]\\\\T_B\\le T<T_C\\quad&S_{ve}(T)=a_g\\cdot S\\cdot\\eta\\cdot F_v\\\\T_C\\le T<T_D\\quad&S_{ve}(T)=a_g\\cdot S\\cdot\\eta\\cdot F_v\\cdot\\left(\\frac{T_C}{T}\\right)\\\\T_D\\le T\\quad&S_{ve}(T)=a_g\\cdot S\\cdot\\eta\\cdot F_v\\cdot\\left(\\frac{T_C\\cdot T_D}{T^2}\\right)\\end{aligned}",
    },
    { number: "3.2.9", unit: "3.2.3.2.2", page: 53, latex: "F_v=1{,}35\\cdot F_o\\cdot\\left(\\frac{a_g}{g}\\right)^{0{,}5}" },
    { number: "3.2.10", unit: "3.2.3.2.3", page: 53, latex: "S_{De}(T)=S_e(T)\\times\\left(\\frac{T}{2\\pi}\\right)^2" },
    {
        number: "3.2.11",
        unit: "3.2.3.2.3",
        page: 54,
        latex: "\\begin{aligned}T_E<T\\le T_F\\quad&S_{De}(T)=0{,}025\\cdot a_g\\cdot S\\cdot T_C\\cdot T_D\\cdot\\left[F_o\\cdot\\eta+\\left(1-F_o\\cdot\\eta\\right)\\cdot\\frac{T-T_E}{T_F-T_E}\\right]\\\\T>T_F\\quad&S_{De}(T)=d_g\\end{aligned}",
    },
    { number: "3.2.12", unit: "3.2.3.3", page: 54, latex: "\\begin{aligned}d_g&=0{,}025\\cdot a_g\\cdot S\\cdot T_C\\cdot T_D\\\\v_g&=0{,}16\\cdot a_g\\cdot S\\cdot T_C\\end{aligned}" },
    { number: "3.2.13", unit: "3.2.4.2", page: 55, latex: "d_{ij\\mathrm{max}}=1{,}25\\sqrt{d_{gi}^2+d_{gj}^2}" },
    { number: "3.2.14", unit: "3.2.4.2", page: 55, latex: "d_{ij}(x)=d_{ij0}+\\left(d_{ij\\mathrm{max}}-d_{ij0}\\right)\\left[1-e^{-1{,}25(x/v_s)^{0{,}7}}\\right]" },
    { number: "3.2.15", unit: "3.2.4.2", page: 55, latex: "d_{ij0}=1{,}25\\left|d_{gi}-d_{gj}\\right|" },
    {
        number: "3.2.16",
        unit: "3.2.4.2",
        page: 55,
        latex: "\\begin{aligned}d_{ij}(x)&=\\frac{d_{ij\\mathrm{max}}}{v_s}\\cdot2{,}3x&&\\text{per sottosuolo tipo D,}\\\\d_{ij}(x)&=\\frac{d_{ij\\mathrm{max}}}{v_s}\\cdot3{,}0x&&\\text{per sottosuolo di tipo diverso da D.}\\end{aligned}",
    },
    { number: "3.3.1", unit: "3.3.1", page: 56, latex: "v_b=v_{b,0}\\cdot c_a" },
    {
        number: "3.3.1.b",
        unit: "3.3.1",
        page: 56,
        latex: "c_a=\\begin{cases}1&\\text{per }a_s\\le a_0\\\\1+k_s\\left(\\dfrac{a_s}{a_0}-1\\right)&\\text{per }a_0<a_s\\le1500\\,\\mathrm{m}\\end{cases}",
    },
    { number: "3.3.2", unit: "3.3.2", page: 57, latex: "v_r=v_b\\cdot c_r" },
    { number: "3.3.3", unit: "3.3.2", page: 57, latex: "c_r=0{,}75\\sqrt{1-0{,}2\\times\\ln\\left[-\\ln\\left(1-\\frac{1}{T_R}\\right)\\right]}" },
    { number: "3.3.4", unit: "3.3.4", page: 58, latex: "p=q_r\\,c_e\\,c_p\\,c_d" },
    { number: "3.3.5", unit: "3.3.5", page: 58, latex: "p_f=q_r\\,c_e\\,c_f" },
    { number: "3.3.6", unit: "3.3.6", page: 58, latex: "q_r=\\frac{1}{2}\\rho v_r^2" },
    {
        number: "3.3.7",
        unit: "3.3.7",
        page: 58,
        latex: "c_e(z)=\\begin{cases}k_r^2c_t\\ln(z/z_0)\\left[7+c_t\\ln(z/z_0)\\right]&z\\ge z_{min}\\\\c_e(z_{min})&z<z_{min}\\end{cases}",
    },
    { number: "3.4.1", unit: "3.4.1", page: 61, latex: "q_s=q_{sk}\\cdot\\mu_i\\cdot C_E\\cdot C_t" },
    {
        number: "3.4.2",
        unit: "3.4.2",
        page: 62,
        latex: "\\begin{aligned}q_{sk}&=1{,}50\\,\\mathrm{kN/m^2}&a_s&\\le200\\,\\mathrm{m}\\\\q_{sk}&=1{,}39\\left[1+\\left(a_s/728\\right)^2\\right]\\,\\mathrm{kN/m^2}&a_s&>200\\,\\mathrm{m}\\end{aligned}",
    },
    {
        number: "3.4.3",
        unit: "3.4.2",
        page: 62,
        latex: "\\begin{aligned}q_{sk}&=1{,}50\\,\\mathrm{kN/m^2}&a_s&\\le200\\,\\mathrm{m}\\\\q_{sk}&=1{,}35\\left[1+\\left(a_s/602\\right)^2\\right]\\,\\mathrm{kN/m^2}&a_s&>200\\,\\mathrm{m}\\end{aligned}",
    },
    {
        number: "3.4.4",
        unit: "3.4.2",
        page: 62,
        latex: "\\begin{aligned}q_{sk}&=1{,}00\\,\\mathrm{kN/m^2}&a_s&\\le200\\,\\mathrm{m}\\\\q_{sk}&=0{,}85\\left[1+\\left(a_s/481\\right)^2\\right]\\,\\mathrm{kN/m^2}&a_s&>200\\,\\mathrm{m}\\end{aligned}",
    },
    {
        number: "3.4.5",
        unit: "3.4.2",
        page: 62,
        latex: "\\begin{aligned}q_{sk}&=0{,}60\\,\\mathrm{kN/m^2}&a_s&\\le200\\,\\mathrm{m}\\\\q_{sk}&=0{,}51\\left[1+\\left(a_s/481\\right)^2\\right]\\,\\mathrm{kN/m^2}&a_s&>200\\,\\mathrm{m}\\end{aligned}",
    },
    { number: "3.5.1", unit: "3.5.2", page: 64, latex: "T_{\\min}=-15-4\\cdot a_s/1000" },
    { number: "3.5.2", unit: "3.5.2", page: 64, latex: "T_{\\max}=42-6\\cdot a_s/1000" },
    { number: "3.5.3", unit: "3.5.2", page: 64, latex: "T_{\\min}=-8-6\\cdot a_s/1000" },
    { number: "3.5.4", unit: "3.5.2", page: 64, latex: "T_{\\max}=42-2\\cdot a_s/1000" },
    { number: "3.5.5", unit: "3.5.2", page: 64, latex: "T_{\\min}=-8-7\\cdot a_s/1000" },
    { number: "3.5.6", unit: "3.5.2", page: 64, latex: "T_{\\max}=42-0{,}3\\cdot a_s/1000" },
    { number: "3.5.7", unit: "3.5.2", page: 64, latex: "T_{\\min}=-2-9\\cdot a_s/1000" },
    { number: "3.5.8", unit: "3.5.2", page: 64, latex: "T_{\\max}=42-2\\cdot a_s/1000" },
    { number: "3.6.1", unit: "3.6.1.1", page: 66, latex: "q_{f,d}=q_f\\cdot\\delta_{q1}\\cdot\\delta_{q2}\\cdot\\delta_n" },
    { number: "3.6.2", unit: "3.6.1.5.1", page: 68, latex: "\\theta_g=20+345\\log_{10}(8t+1)\\,[{}^\\circ\\mathrm{C}]" },
    { number: "3.6.3", unit: "3.6.1.5.1", page: 68, latex: "\\theta_g=1080\\left(1-0{,}325\\cdot e^{-0{,}167t}-0{,}675\\cdot e^{-2{,}5t}\\right)+20\\,[{}^\\circ\\mathrm{C}]" },
    { number: "3.6.4", unit: "3.6.1.5.1", page: 68, latex: "\\theta_g=660\\left(1-0{,}687\\cdot e^{-0{,}32t}-0{,}313\\cdot e^{-3{,}8t}\\right)+20\\,[{}^\\circ\\mathrm{C}]" },
    { number: "3.6.5a", unit: "3.6.2.3", page: 69, latex: "p_d=3+p_v" },
    { number: "3.6.5b", unit: "3.6.2.3", page: 69, latex: "p_d=3+\\frac{p_v}{2}+\\frac{0{,}04}{(A_v/V)^2}" },
    { number: "3.6.6", unit: "3.6.2.3", page: 69, latex: "0{,}05\\,\\mathrm{m}^{-1}\\le\\frac{A_v}{V}\\le0{,}15\\,\\mathrm{m}^{-1}" },
    { number: "3.6.7", unit: "3.6.3.3.1", page: 70, latex: "F_{d,y}=0{,}50F_{d,x}" },
    { number: "3.6.8", unit: "3.6.3.3.1", page: 70, latex: "F=rF_{d,x}" },
    { number: "3.6.9", unit: "3.6.3.3.1", page: 70, latex: "F=5W" },
];

const circ: FormulaSeed[] = [
    {
        number: "C3.2.1",
        officialNumber: "C.3.2.1",
        unit: "c3.2.1",
        page: 48,
        latex: "T_R=-\\frac{V_R}{\\ln(1-P_{VR})}=-\\frac{C_UV_N}{\\ln(1-P_{VR})}",
    },
    {
        number: "C3.2.2",
        officialNumber: "C.3.2.2",
        unit: "c3.2.1",
        page: 49,
        latex: "R=\\frac{T_{R,b}}{T_{R,a}}=\\frac{-V_N/\\ln(1-P_{VR}/C_U)}{-C_UV_N/\\ln(1-P_{VR})}=\\frac{\\ln(1-P_{VR})}{C_U\\ln(1-P_{VR}/C_U)}",
    },
    {
        number: "C3.2.3",
        officialNumber: "C.3.2.3",
        unit: "c3.2.1",
        page: 49,
        latex: "R=1=\\frac{\\ln(1-P^*_{VR})}{C_U\\ln(1-P_{VR}/C_U)}\\Rightarrow\\ln(1-P^*_{VR})=C_U\\ln(1-P_{VR}/C_U)\\Rightarrow P^*_{VR}=1-\\left(1-\\frac{P_{VR}}{C_U}\\right)^{C_U}",
    },
    {
        number: "C3.2.4",
        unit: "c3.2.2",
        page: 51,
        latex: "V_{S,eq}=\\frac{H}{\\displaystyle\\sum_{j=1}^{N}\\frac{h_j}{V_{S,j}}}=\\frac{\\displaystyle\\sum_{j=1}^{N}h_j}{\\displaystyle\\sum_{j=1}^{N}\\frac{h_j}{V_{S,j}}}",
    },
    {
        number: "C3.2.5",
        unit: "c3.2.3.6",
        page: 54,
        latex: "\\rho_{X,Y}=\\frac{\\displaystyle\\int_{t_1}^{t_2}X(t)Y(t)\\,dt}{\\sqrt{\\displaystyle\\int_{t_1}^{t_2}X^2(t)\\,dt\\;\\displaystyle\\int_{t_1}^{t_2}Y^2(t)\\,dt}}",
    },
    {
        number: "C3.3.1",
        unit: "c3.3.2",
        page: 54,
        latex: "v_b(T_R)=\\alpha_Rv_b",
    },
    {
        number: "C3.3.2",
        unit: "c3.3.2",
        page: 54,
        latex: "\\alpha_R=0{,}75\\sqrt{1-0{,}2\\ln\\left[-\\ln\\left(1-\\frac{1}{T_R}\\right)\\right]}",
    },
    {
        number: "C3.3.3",
        unit: "c3.3.8",
        page: 55,
        latex: "c_{pe,A}=c_{pe,1}-\\left(c_{pe,1}-c_{pe,10}\\right)\\log_{10}(A)",
    },
    {
        number: "C3.3.4",
        unit: "c3.3.8.3",
        page: 71,
        latex: "c_{pe}=c_{pe0}\\psi_{\\lambda\\alpha}",
    },
    {
        number: "C3.3.5",
        unit: "c3.3.8.3",
        page: 71,
        latex: "c_{pe0}(\\alpha_p)=\\begin{cases}1-(1-c_{pm})\\sin^2\\left(\\dfrac{\\pi\\alpha_p}{2\\alpha_m}\\right)&0^\\circ\\le\\alpha_p\\le\\alpha_m\\\\c_{pb}-(c_{pb}-c_{pm})\\cos^2\\left[\\dfrac{\\pi}{2}\\dfrac{\\alpha_p-\\alpha_m}{\\alpha_b-\\alpha_m}\\right]&\\alpha_m\\le\\alpha_p\\le\\alpha_b\\\\c_{pb}&\\alpha_b\\le\\alpha_p\\le180^\\circ\\end{cases}",
    },
    {
        number: "C3.3.6",
        unit: "c3.3.8.3",
        page: 71,
        latex: "\\psi_{\\lambda\\alpha}=\\begin{cases}1&0^\\circ\\le\\alpha_p\\le\\alpha_m\\\\\\psi_\\lambda+(1-\\psi_\\lambda)\\cos\\left[\\dfrac{\\pi}{2}\\left(\\dfrac{\\alpha_p-\\alpha_m}{\\alpha_b-\\alpha_m}\\right)\\right]&\\alpha_m\\le\\alpha_p\\le\\alpha_b\\\\\\psi_\\lambda&\\alpha_b\\le\\alpha_p\\le180^\\circ\\end{cases}",
    },
    {
        number: "C3.3.7",
        unit: "c3.3.8.6.1",
        page: 74,
        latex: "\\varphi=\\frac{S_p}{S}",
    },
    {
        number: "C3.3.8",
        unit: "c3.3.8.6.1",
        page: 74,
        latex: "c_p=\\begin{cases}2-\\dfrac{4}{3}\\varphi&0\\le\\varphi<0{,}3\\\\1{,}6&0{,}3\\le\\varphi\\le0{,}8\\\\2{,}4-\\varphi&0{,}8<\\varphi\\le1\\end{cases}",
    },
    {
        number: "C3.3.8.7.unnumbered-1",
        officialNumber: null,
        unit: "c3.3.8.7",
        page: 74,
        latex: "c_p=\\begin{cases}2{,}4&\\text{per torri con elementi tubolari a sezione circolare}\\\\2{,}8&\\text{per torri con elementi aventi sezione di forma diversa dalla circolare}\\end{cases}",
    },
    {
        number: "C3.3.9",
        unit: "c3.3.11",
        page: 75,
        latex: "n_s=\\frac{St\\,v_m}{b}",
    },
    {
        number: "C3.3.10",
        unit: "c3.3.11",
        page: 75,
        latex: "v_{cr,i}=\\frac{n_i b}{St}",
    },
    {
        number: "C3.3.11",
        unit: "c3.3.11",
        page: 75,
        latex: "v_{cr,i}<v_{m,l}",
    },
    {
        number: "C3.3.12",
        unit: "c3.3.11",
        page: 75,
        latex: "Sc=\\frac{4\\pi m\\xi}{\\rho b^2}",
    },
    {
        number: "C3.4.1",
        unit: "c3.4.2",
        page: 76,
        latex: "q_{sn}=q_{sk}\\left\\{\\frac{1-v\\dfrac{\\sqrt{6}}{\\pi}\\left[\\ln\\left(-\\ln(1-P_n)\\right)+0{,}57722\\right]}{1-2{,}5923v}\\right\\}",
    },
    {
        number: "C3.4.2",
        unit: "c3.4.3.2",
        page: 77,
        latex: "L_c=2W-\\frac{W^2}{L}",
    },
    {
        number: "C3.4.3",
        unit: "c3.4.3.2",
        page: 77,
        latex: "\\mu_1=0{,}8\\,C_{e,F}",
    },
    {
        number: "C3.4.4",
        unit: "c3.4.3.2",
        page: 77,
        latex: "C_{e,F}=\\begin{cases}1{,}0&\\text{per }L_c<50\\,\\mathrm{m}\\\\1{,}25-0{,}25e^{-(L_c-50\\,\\mathrm{m})/(200\\,\\mathrm{m})}&\\text{altrimenti}\\end{cases}",
    },
    {
        number: "C3.4.5",
        unit: "c3.4.3.3.2",
        page: 79,
        latex: "\\mu_w=\\frac{b_1+b_2}{2h}\\le\\frac{\\gamma h}{q_{sk}}",
    },
    {
        number: "C3.4.3.3.1.unnumbered-1",
        officialNumber: null,
        unit: "c3.4.3.3.1",
        page: 78,
        latex: "\\begin{aligned}\\beta>60^\\circ&:\\quad\\mu_3=0\\\\\\beta\\le60^\\circ&:\\quad\\mu_3=0{,}2+10h/b,\\quad\\mu_3\\le2{,}0\\end{aligned}",
    },
    {
        number: "C3.4.3.3.2.unnumbered-1",
        officialNumber: null,
        unit: "c3.4.3.3.2",
        page: 79,
        latex: "\\begin{aligned}\\mu_1&=0{,}8\\\\\\mu_2&=\\mu_s+\\mu_w\\end{aligned}",
    },
    {
        number: "C3.4.3.3.2.unnumbered-2",
        officialNumber: null,
        unit: "c3.4.3.3.2",
        page: 79,
        latex: "0{,}8\\le\\mu_w\\le4{,}0,\\qquad l_s=2h,\\quad5\\,\\mathrm{m}\\le l_s\\le15\\,\\mathrm{m}",
    },
    {
        number: "C3.4.3.3.4.unnumbered-1",
        officialNumber: null,
        unit: "c3.4.3.3.4",
        page: 79,
        latex: "\\mu_1=0{,}8,\\qquad\\mu_2=\\frac{\\gamma h}{q_{sk}},\\quad0{,}8\\le\\mu_2\\le2{,}0",
    },
    {
        number: "C3.4.3.3.4.unnumbered-2",
        officialNumber: null,
        unit: "c3.4.3.3.4",
        page: 80,
        latex: "l_s=2h,\\qquad5\\,\\mathrm{m}\\le l_s\\le15\\,\\mathrm{m}",
    },
    {
        number: "C3.4.6",
        unit: "c3.4.3.3.5",
        page: 80,
        latex: "q_{se}=\\frac{kq_s^2}{\\gamma}",
    },
    {
        number: "C3.4.7",
        unit: "c3.4.3.3.6",
        page: 80,
        latex: "F_s=q_s b\\sin\\alpha",
    },
    { number: "C4.1.1", unit: "c4.1.1.1", page: 86, latex: "\\overline{M}_{Ed}\\le\\overline{M}_{Rd}" },
    { number: "C4.1.2", unit: "c4.1.2.2.2", page: 90, latex: "p^*=\\zeta p_f+(1-\\zeta)p" },
    { number: "C4.1.3", unit: "c4.1.2.2.2", page: 90, latex: "\\zeta=1-c\\beta^2" },
    { number: "C4.1.4", unit: "c4.1.2.2.2", page: 90, latex: "\\frac{l}{h}\\le K\\left[11+\\frac{0{,}015f_{ck}}{\\rho+\\rho'}\\right]\\left[\\frac{500A_{s,eff}}{f_{yk}A_{s,calc}}\\right]" },
    {
        number: "C4.1.5",
        officialNumber: "C4.1.5 e 4.1.14",
        unit: "c4.1.2.2.4.5",
        page: 91,
        latex: "w_k=1{,}7\\,\\varepsilon_{sm}\\,\\Delta_{sm}",
    },
    { number: "C4.1.6", unit: "c4.1.2.2.4.5", page: 91, latex: "\\varepsilon_{sm}=\\frac{\\sigma_s-k_t\\dfrac{f_{ctm}}{\\rho_{eff}}\\left(1+\\alpha_e\\rho_{eff}\\right)}{E_s}\\ge0{,}6\\frac{\\sigma_s}{E_s}" },
    { number: "C4.1.7", unit: "c4.1.2.2.4.5", page: 92, latex: "\\Delta_{sm}=\\frac{k_3c+k_1k_2k_4\\dfrac{\\phi}{\\rho_{eff}}}{1{,}7}" },
    { number: "C4.1.8", unit: "c4.1.2.2.4.5", page: 92, latex: "\\phi_{eq}=\\frac{n_1\\phi_1^2+n_2\\phi_2^2}{n_1\\phi_1+n_2\\phi_2}" },
    { number: "C4.1.9", unit: "c4.1.2.2.4.5", page: 92, latex: "k_2=\\frac{\\varepsilon_1+\\varepsilon_2}{2\\varepsilon_1}" },
    { number: "C4.1.10", unit: "c4.1.2.2.4.5", page: 92, latex: "\\Delta_{sm}=0{,}75(h-x)" },
    { number: "C4.1.11", unit: "c4.1.2.3.4.2", page: 93, latex: "N_{Rd}=0{,}8A_cf_{cd}+A_{s,tot}f_{yd}" },
    { number: "C4.1.12", unit: "c4.1.12.1.1.1", page: 97, latex: "f_{lctm}=0{,}30\\,f_{lck}^{2/3}\\eta_1\\quad\\text{per calcestruzzo di classe }\\le LC\\,50/55" },
    { number: "C4.1.13", unit: "c4.1.12.1.1.1", page: 97, latex: "f_{lctm}=2{,}12\\ln\\left[1+\\left(f_{lcm}/10\\right)\\right]\\eta_1\\quad\\text{per calcestruzzo di classe }>LC\\,50/55" },
    { number: "C4.1.12.eta1", officialNumber: null, unit: "c4.1.12.1.1.1", page: 97, latex: "\\eta_1=0{,}40+0{,}60\\frac{\\rho}{2200}" },
    {
        number: "C4.1.12.flcm",
        officialNumber: null,
        unit: "c4.1.12.1.1.1",
        page: 97,
        latex: "f_{lcm}=\\begin{cases}22\\,\\mathrm{N/mm^2}&\\text{per }LC\\,16/20\\\\f_{lck}+8\\,\\mathrm{N/mm^2}&\\text{per }f_{lck}>20\\,\\mathrm{N/mm^2}\\end{cases}",
    },
    { number: "C4.1.14.a", unit: "c4.1.12.1.1.1", page: 97, latex: "f_{lctk,0{,}05}=0{,}7f_{lctm}" },
    { number: "C4.1.14.b", unit: "c4.1.12.1.1.1", page: 97, latex: "f_{lctk,0{,}95}=1{,}3f_{lctm}" },
    { number: "C4.1.15", unit: "c4.1.12.1.1.1", page: 97, latex: "f_{lctd}=0{,}85\\frac{f_{lctk}}{\\gamma_C}" },
    { number: "C4.1.16", unit: "c4.1.12.1.1.2", page: 97, latex: "E_{lcm}=22000\\left[\\frac{f_{lcm}}{10}\\right]^{0{,}3}\\eta_E\\quad\\mathrm{N/mm^2}" },
    { number: "C4.1.16.etae", officialNumber: null, unit: "c4.1.12.1.1.2", page: 97, latex: "\\eta_E=\\left(\\frac{\\rho}{2200}\\right)^2" },
    {
        number: "C4.1.13.strains.le50",
        officialNumber: null,
        unit: "c4.1.12.1.3.1",
        page: 98,
        latex: "\\begin{aligned}\\varepsilon_{c2}&=0{,}20\\%\\\\\\varepsilon_{c3}&=0{,}175\\%\\\\\\varepsilon_{cu}&=\\eta_1\\,0{,}35\\%,\\qquad \\eta_1=0{,}40+0{,}60\\frac{\\rho}{2200}\\end{aligned}",
    },
    {
        number: "C4.1.13.strains.55",
        officialNumber: null,
        unit: "c4.1.12.1.3.1",
        page: 98,
        latex: "\\begin{aligned}\\varepsilon_{c2}&=0{,}22\\%\\\\\\varepsilon_{c3}&=0{,}18\\%\\\\\\varepsilon_{cu}&=\\eta_1\\,0{,}31\\%\\end{aligned}",
    },
    { number: "C4.1.17", unit: "c4.1.12.1.3.2.1", page: 98, latex: "V_{lRd,c}=\\left[\\frac{0{,}15\\,\\eta_1k\\left(100\\rho_lf_{lck}\\right)^{1/3}}{\\gamma_C}+0{,}15\\sigma_{cp}\\right]b_wd\\ge\\left(\\nu_{l,min}+0{,}15\\sigma_{cp}\\right)b_wd" },
    {
        number: "C4.1.17.parameters",
        officialNumber: null,
        unit: "c4.1.12.1.3.2.1",
        page: 98,
        latex: "\\begin{aligned}\\eta_1&=0{,}40+0{,}60\\frac{\\rho}{2200}\\\\k&=1+\\left(\\frac{200}{d}\\right)^{1/2}\\le2\\\\\\nu_{l,min}&=0{,}030\\,k^{3/2}f_{lck}^{1/2}\\end{aligned}",
    },
    { number: "C4.1.18", unit: "c4.1.12.1.3.2.1", page: 98, latex: "V_{Ed}\\le0{,}5\\eta_1b_wd\\nu_1f_{lcd}" },
    { number: "C4.1.19", unit: "c4.1.12.1.3.2.1", page: 98, latex: "\\nu_1=0{,}5\\eta_1\\left(1-\\frac{f_{lck}}{250}\\right)" },
];

async function writeManifest(
    document: "ntc2018" | "circ2019",
    sourceId: string,
    seeds: FormulaSeed[],
): Promise<void> {
    const manifest = {
        $schema: "urn:structural-codes:schema:asset-manifest:v2",
        schemaVersion: "2.0.0-alpha.1",
        recordType: "asset-manifest",
        document,
        section: "core-editorial",
        sourceId,
        status: "transcribed-unreviewed",
        formulas: seeds.map(({ number, officialNumber, unit, page, latex }) => ({
            id: `urn:structural-codes:it:asset:formula:${document}:${number.toLowerCase()}`,
            unitId: `urn:structural-codes:it:unit:${document}:${unit}`,
            officialNumber: officialNumber === undefined ? number : officialNumber,
            pdfPage: page,
            latex,
        })),
        tables: [],
        figures: [],
    };
    const output = join(repoRoot, "corpus", "assets", document, "core-editorial.json");
    await mkdir(dirname(output), { recursive: true });
    await writeFile(output, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
}

await Promise.all([
    writeManifest("ntc2018", "gu-so8-2018-ntc", ntc),
    writeManifest("circ2019", "circ-7-2019", circ),
]);
console.log(`core-formula-manifests: ${ntc.length + circ.length} formule`);
