/* eslint-disable @typescript-eslint/no-explicit-any */
import{createHash}from"node:crypto";import{readFile,writeFile}from"node:fs/promises";import{join}from"node:path";import{fileURLToPath}from"node:url";
type P={kind:"text"|"em"|"strong"|"math";value:string;latex?:string};type B={blockId:string;kind:string;listMarker?:"bullet"|"dash"|"none";text?:{raw?:string;normalized:string;inline?:P[]};evidence?:{pdfPage?:number;normalizedSha256?:string;transformations?:any[]}};type U={blocks:B[]};const root=fileURLToPath(new URL("../",import.meta.url)),dir=join(root,"corpus","units","ntc2018"),profile="ntc7-format-audit-step5-0.1.0";
function ok(v:unknown,m:string):asserts v{if(!v)throw new Error(m)}function find(u:U,s:string){const b=u.blocks.find(x=>x.text?.normalized.startsWith(s));ok(b?.text,s);return b as B&{text:NonNullable<B["text"]>}}const ps=(b:ReturnType<typeof find>)=>b.text.inline??[{kind:"text" as const,value:b.text.normalized}];
function set(b:ReturnType<typeof find>,p:P[]){p=p.filter(x=>x.value);ok(p.map(x=>x.value).join("")===b.text.normalized,b.blockId);b.text.inline=p}function replace(b:ReturnType<typeof find>,s:string,p:P,n=1){const a=ps(b),seen=a.filter(x=>x.kind===p.kind&&x.value===p.value&&x.latex===p.latex).length;if(seen===n)return;ok(seen===0,s);let k=0;const out:P[]=[];for(const x of a){if(x.kind!=="text"){out.push(x);continue}let c=0;while(c<x.value.length){const i=x.value.indexOf(s,c);if(i<0||k===n){out.push({kind:"text",value:x.value.slice(c)});break}out.push({kind:"text",value:x.value.slice(c,i)},p);k++;c=i+s.length}}ok(k===n,`${s}:${k}`);set(b,out)}const style=(b:ReturnType<typeof find>,kind:"em"|"strong",v:string,n=1)=>replace(b,v,{kind,value:v},n);
function marker(u:U){for(const b of u.blocks){if(b.kind!=="list-item"||!b.text||(b.evidence?.pdfPage??0)<250||(b.evidence?.pdfPage??0)>259)continue;const r=(b.text.raw??"").trimStart(),n=b.text.normalized.trimStart();b.listMarker=/^(?:x|\u0083)\s/u.test(r)?"bullet":(/^(?:-|–|ȭ)\s/u.test(r)||/^[-–ȭ]\s/u.test(n)?"dash":"none")}}
function fixCorrupt(b:ReturnType<typeof find>){if(!b.text.normalized.startsWith("ȭ "))return;b.text.normalized=`- ${b.text.normalized.slice(2)}`;b.text.inline=ps(b).map(x=>({...x,value:x.value.replace(/^ȭ /u,"- ")}));set(b,b.text.inline);if(b.evidence){b.evidence.normalizedSha256=createHash("sha256").update(b.text.normalized).digest("hex");b.evidence.transformations??=[];b.evidence.transformations.push({operation:"manual-correction",ruleVersion:profile,note:"Ripristinato il trattino di elenco verificato nel PDF ufficiale al posto del glifo corrotto."})}}
async function edit(n:string,cb:(u:U)=>void=()=>undefined){const p=join(dir,`${n}.json`),u=JSON.parse(await readFile(p,"utf8")) as U;marker(u);cb(u);marker(u);await writeFile(p,`${JSON.stringify(u,null,2)}\n`)}

await edit("7.5.6",u=>{for(const b of u.blocks.filter(x=>x.kind==="list-item"&&(x.evidence?.pdfPage??0)===251)){ok(b.text,b.blockId);if(b.text.normalized.startsWith("ȭ "))fixCorrupt(b as ReturnType<typeof find>)}});
await edit("7.6");await edit("7.6.2.1",u=>{for(const m of ["a)","b)","c)","d)","e)"])style(find(u,`${m} `),"em",m)});await edit("7.6.4.3");
await edit("7.7",u=>{for(const label of ["duttilità statica","nodi semi-rigidi","nodi rigidi","unioni con mezzi di unione a gambo cilindrico","nodi di carpenteria"])style(find(u,label),"strong",label)});
await edit("7.7.1",u=>{for(const m of ["a)","b)"])style(find(u,`${m} `),"em",m)});await edit("7.7.2",u=>{for(const m of ["a)","b)","c)"]){const matches=u.blocks.filter(x=>x.kind==="list-item"&&x.text?.normalized.startsWith(`${m} `));for(const b of matches)style(b as ReturnType<typeof find>,"em",m)}});
for(const n of ["7.6.1.1","7.6.1.2","7.6.1.3","7.6.4.1","7.6.4.2","7.6.4.4","7.6.5.1","7.6.5.2","7.6.5.3","7.6.5.4","7.6.6.1","7.6.6.2","7.6.6.3","7.6.6.4","7.6.6.5","7.6.7","7.6.8"])await edit(n);

const ap=join(root,"corpus","assets","ntc2018","7.6-step1.json"),a=JSON.parse(await readFile(ap,"utf8"));for(const f of a.figures){const token=f.caption.includes(" – ")?" – ":" - ",prefix=`Fig. ${f.officialNumber}${token}`;ok(f.caption.startsWith(prefix),f.caption);f.captionInline=[{kind:"strong",value:prefix},{kind:"em",value:f.caption.slice(prefix.length)}]}
for(const t of a.tables){if(t.officialNumber==="7.6.II"){t.captionInline=[{kind:"em",value:"Valori limite del rapporto "},{kind:"math",value:"x/d",latex:"x/d"},{kind:"em",value:" per le travi composte, al variare del fattore "},{kind:"math",value:"q_0",latex:"q_0"}]}else t.captionInline=[{kind:"em",value:t.caption}];ok(t.captionInline.map((x:P)=>x.value).join("")===t.caption,t.officialNumber)}await writeFile(ap,`${JSON.stringify(a,null,2)}\n`);console.log("fix-ntc7-format-step5: pagine PDF 250-259 aggiornate");
