export const CHATNTC_EPISTEMIC_POLICY = Object.freeze({
  version: "chatntc-epistemic-v2" as const,
  normativeSource: "structural-codes" as const,
  officialPdfIsEditorialAuthority: true,
  modelMemoryIsNormativeSource: false,
  generalEngineeringKnowledgeAllowed: true,
  engineeringReasoningRequiresNormativeCitation: false,
  preserveDocumentDistinction: true,
  interpretationIsPrescription: false,
  coordinatedReadingIsInterpretation: true,
  normativeAttributionBasis: "available-normative-content" as const,
  canonicalReferenceImpliesSemanticSupport: false,
  hierarchicalScopePreservationRequired: true,
  abstentionOnInsufficientEvidence: true,
  inventedCitationsAllowed: false,
  citationScope: "canonical-corpus-references" as const,
  validationScope: "integrity-provenance-reference-resolution" as const,
  semanticEntailmentVerified: false,
  externalSourcesEnabled: false,
});

export const CHATNTC_DEFAULT_RETRIEVAL = Object.freeze({
  maxPrimaryUnits: 5,
  maxRelatedUnits: 5,
  maxChildrenPerUnit: 2,
  maxEvidenceCharacters: 48_000,
  maxUnitCharacters: 9_000,
  includeParents: true,
  includeCrossReferences: true,
  includeExplicitRelations: true,
  includeProposedRelations: true,
});
